-- CREACIÓN DE JUZGADO noveno mercantil
INSERT INTO TRIALS.TBL_JUZGADOS(PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE, N_ESTADO)
VALUES(350, 0, 'Juzgado Noveno mercantil', 200, 1, 0);

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 350, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Providencia precautoria';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 350, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Medios preparatorios a Juicio';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 350, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oral Ejecutivo';