-- se insertan juzgados civiles y mercantiles de la base histoirica junto con su clave y su table ubi:

INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO PRIMERO ESPECIALIZADO EN MATERIA CIVIL', 300, 109, 2, 2, 0, NULL, 1101, 'ubicaciones_pue_pc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO SEGUNDO ESPECIALIZADO EN MATERIA CIVIL', 300, 109, 2, 2, 0, NULL, 1102, 'ubicaciones_pue_sc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO TERCERO ESPECIALIZADO EN MATERIA CIVIL', 300, 109, 2, 2, 0, NULL, 1103, 'ubicaciones_pue_tc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO CUARTO ESPECIALIZADO EN MATERIA CIVIL', 300, 109, 2, 2, 0, NULL, 1104, 'ubicaciones_pue_cc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO QUINTO ESPECIALIZADO EN MATERIA CIVIL', 300, 109, 1, 2, 0, NULL, 1105, 'ubicaciones_pue_qc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO SEXTO ESPECIALIZADO EN MATERIA MERCANTIL', 200, 109, 0, 2, 0, NULL, 1106, 'ubicaciones06',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO SEPTIMO ESPECIALIZADO EN MATERIA MERCANTIL', 200, 109, 0, 2, 0, NULL, 1107, 'ubicaciones07',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO OCTAVO ESPECIALIZADO EN MATERIA MERCANTIL', 200, 109, 0, 2, 0, NULL, 1108, 'ubicaciones08',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO DECIMO ESPECIALIZADO EN MATERIA MERCANTIL', 200, 109, 0, 2, 0, NULL, 1110, 'ubicaciones10',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO DECIMO PRIMERO ESPECIALIZADO MERCANTIL', 200, 109, 0, 2, 0, NULL, 1111, 'ubicaciones11',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO DECIMO SEGUNDO ESPECIALIZADO MERCANTIL', 200, 109, 2, 2, 0, NULL, 1112, 'ubicaciones12',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO PRIMERO DE LO CIVIL DE CHOLULA', 300, 109, 0, 2, 0, NULL, 4050, 'ubicaciones_ch_pc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO SEGUNDO DE LO CIVIL DE CHOLULA', 300, 109, 0, 2, 0, NULL, 4051, 'ubicaciones_ch_sc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO PRIMERO DE LO CIVIL DE HUEJOTZINGO', 300, 109, 0, 2, 0, NULL, 4030, 'ubicaciones_huejo_pc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO SEGUNDO DE LO CIVIL DE HUEJOTZINGO', 300, 109, 0, 2, 0, NULL, 4031, 'ubicaciones_huejo_sc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO PRIMERO DE LO CIVIL TEHUACAN', 300, 109, 1, 2, 0, NULL, 4070, 'ubicaciones_th_pc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO SEGUNDO DE LO CIVIL TEHUACAN', 300, 109, 1, 2, 0, NULL, 4071, 'ubicaciones_th_sc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'PRIMERA SALA CIVIL PUEBLA', 300, 109, 1, 2, 1, NULL, 101, 'ubicaciones_1sala_c',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'SEGUNDA SALA CIVIL PUEBLA', 300, 109, 2, 2, 1, NULL, 102, 'ubicaciones_2sala_c',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'TERCERA SALA CIVIL PUEBLA', 300, 109, 2, 2, 1, NULL, 103, 'ubicaciones_3sala_c',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'CUARTA SALA CIVIL PUEBLA', 300, 109, 1, 2, 1, NULL, 104, 'ubicaciones_4sala_c',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'QUINTA SALA CIVIL PUEBLA', 300, 109, 2, 2, 1, NULL, 105, 'ubicaciones_5sala_c',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'SALA ESPECIALIZADA EN MATERIA CONSTITUCIONAL (SALA CIVIL)', 300, 109, 1, 2, 1, NULL, 106, 'ubicaciones_6sala_c',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO SUPERNUMERARIO ATLIXCO', 300, 109, 2, 2, 0, NULL, 4012, 'ubicaciones_ats',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO SUPERNUMERARIO CHOLULA', 300, 109, 2, 2, 0, NULL, 4054, 'ubicaciones_ch_su',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO DE LO CIVIL ATLIXCO', 300, 109, NULL, 2, 0, NULL, 4010, 'ubicaciones_atc',0);
INSERT INTO trials.tbl_juzgados (pn_id, n_version, s_nombre, fn_materia, fn_sede, n_contador_asignaciones, n_max_asignaciones, n_instancia, s_nomenclatura, s_clave_juzgado, s_tabla_ubi, n_estado) VALUES (nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'JUZGADO CIVIL TEPEACA', 300, 109, NULL, 2, 0, NULL, 5850, 'ubicaciones_tepea',0);

