ALTER TABLE TRIALS.TBL_SEDES ADD COLUMN FN_PERSONA INTEGER;

ALTER TABLE TRIALS.TBL_SEDES
ADD CONSTRAINT fk_persona
FOREIGN KEY (FN_PERSONA)
REFERENCES TRIALS.TBL_PERSONAS (PN_ID);

ALTER TABLE TRIALS.TBL_PERSONAS
ALTER COLUMN S_CURP DROP NOT NULL;

ALTER TABLE TRIALS.TBL_PERSONAS
ALTER COLUMN N_SEXO DROP NOT NULL;

ALTER TABLE TRIALS.TBL_PERSONAS
ALTER COLUMN T_FECHA_NACIMIENTO DROP NOT NULL;

