CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_SOLICITUDES_PRORROGAS START WITH 1;
ALTER SEQUENCE TRIALS.SEQ_SOLICITUDES_PRORROGAS INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_SOLICITUDES_PRORROGAS;
CREATE TABLE TRIALS.TBL_SOLICITUDES_PRORROGAS
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_MOTIVO_PRORROGA        VARCHAR(250) NOT NULL,
    S_RESPUESTA_SOLICITUD        VARCHAR(250) NOT NULL,
    N_ESTADO        INT          NOT NULL,
    T_FECHA_PRORROGA TIMESTAMP NOT NULL,
    T_FECHA_AUTORIZADA TIMESTAMP NOT NULL,
    FN_MOVIMIENTO    INT          NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER,
    
    FOREIGN KEY (FN_MOVIMIENTO) REFERENCES TRIALS.TBL_MOVIMIENTOS(PN_ID)
);


-- elimina campos de movimiento : 
ALTER TABLE trials.tbl_movimientos
DROP COLUMN s_motivo_prorroga;

ALTER TABLE trials.tbl_movimientos
DROP COLUMN n_estado_prorroga;

ALTER TABLE trials.tbl_movimientos
DROP COLUMN t_fecha_prorroga;
