ALTER TABLE TRIALS.TBL_SEDES ADD COLUMN S_LATITUDE VARCHAR(80) NULL;

ALTER TABLE TRIALS.TBL_SEDES ADD COLUMN S_LONGITUDE VARCHAR(80) NULL;

ALTER TABLE TRIALS.TBL_SEDES ADD COLUMN S_PHOTO VARCHAR(100) NULL;