-- Providencia precautoria
INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Actor', 349, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Demandado', 349, 0);

-- Medios preparatorios a Juicio
INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Actor', 350, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Demandado', 350, 0);

-- Oral Ejecutivo
INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Actor', 351, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Demandado', 351, 0);