ALTER TABLE TRIALS.TBL_PERSONAS
ADD FOREIGN KEY (FN_JUZGADO)
REFERENCES TRIALS.TBL_JUZGADOS (PN_ID)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

CREATE INDEX IDX_PERSONAS_JUZGADO2 ON TRIALS.TBL_PERSONAS (FN_JUZGADO);

ALTER TABLE TRIALS.TBL_PERSONAS
ADD FOREIGN KEY (FN_ESTADO_CIVIL)
REFERENCES TRIALS.TBL_ESTADO_CIVIL (PN_ID)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

CREATE INDEX IDX_PERSONAS_ESTADOCIVIL3 ON TRIALS.TBL_PERSONAS (FN_ESTADO_CIVIL);

ALTER TABLE TRIALS.TBL_PERSONAS
ADD FOREIGN KEY (FN_ESCOLARIDAD)
REFERENCES TRIALS.TBL_ESCOLARIDADES (PN_ID)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

CREATE INDEX IDX_PERSONAS_ESCOLARIDADES4 ON TRIALS.TBL_PERSONAS (FN_ESCOLARIDAD);

ALTER TABLE TRIALS.TBL_PERSONAS
ADD FOREIGN KEY (FN_DOMICILIO)
REFERENCES TRIALS.TBL_DOMICILIOS (PN_ID)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

CREATE INDEX IDX_PERSONAS_DOMICILIOS5 ON TRIALS.TBL_PERSONAS (FN_DOMICILIO);