ALTER TABLE trials.tbl_personas ADD COLUMN fn_oficialia INT;

ALTER TABLE TRIALS.TBL_PERSONAS
ADD FOREIGN KEY (FN_OFICIALIA)
REFERENCES TRIALS.TBL_OFICIALIAS (PN_ID)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

CREATE INDEX IDX_PERSONAS_OFICIALIA1 ON TRIALS.TBL_PERSONAS (FN_OFICIALIA);