DROP TABLE IF EXISTS TRIALS.TBL_REL_JUZGADO_ESPECIALIDAD;
DROP SEQUENCE IF EXISTS TRIALS.SEQ_REL_JUZGADO_ESPECIALIDAD_ID;

DROP TABLE IF EXISTS TRIALS.TBL_ESPECIALIDADES;
DROP SEQUENCE IF EXISTS TRIALS.SEQ_ESPECIALIDADES_ID;

CREATE TABLE TRIALS.TBL_JUZGADO_TIPOJUICIO
(
    FN_JUZGADO    INT NOT NULL,
    FN_TIPOJUICIO INT NOT NULL,

    FOREIGN KEY (FN_JUZGADO) REFERENCES TRIALS.TBL_JUZGADOS (PN_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (FN_TIPOJUICIO) REFERENCES TRIALS.TBL_TIPO_JUICIO (PN_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT UC_JUZGADO_TIPOJUICIO UNIQUE (FN_JUZGADO, FN_TIPOJUICIO)
);

CREATE INDEX IDX_JUZGADO_TIPOJUICIO1 ON TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO);
CREATE INDEX IDX_JUZGADO_TIPOJUICIO2 ON TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_TIPOJUICIO);