DROP TABLE IF EXISTS TRIALS.TBL_OFICIALIAS_MATERIAS;
DROP SEQUENCE IF EXISTS TRIALS.SEQ_REL_OFICIALIAS_MATERIAS_ID;

CREATE TABLE TRIALS.TBL_OFICIALIAS_MATERIAS
(
    FN_OFICIALIA    INT NOT NULL,
    FN_MATERIA      INT NOT NULL,

    FOREIGN KEY (FN_OFICIALIA) REFERENCES TRIALS.TBL_OFICIALIAS (PN_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (FN_MATERIA) REFERENCES TRIALS.TBL_MATERIAS (PN_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT UC_OFICIALIAS_MATERIAS UNIQUE (FN_OFICIALIA, FN_MATERIA)
);

CREATE INDEX IDX_OFICIALIASMATERIAS_OFICIALIA1 ON TRIALS.TBL_OFICIALIAS_MATERIAS (FN_OFICIALIA);
CREATE INDEX IDX_OFICIALIASMATERIAS_MATERIA2 ON TRIALS.TBL_OFICIALIAS_MATERIAS (FN_MATERIA);