ALTER TABLE TRIALS.TBL_OFICIALIAS ADD COLUMN FN_JUZGADO INT;

ALTER TABLE TRIALS.TBL_OFICIALIAS
ADD FOREIGN KEY (FN_JUZGADO)
REFERENCES TRIALS.TBL_JUZGADOS (PN_ID)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

CREATE INDEX IDX_OFICIALIAS_JUZGADO1 ON TRIALS.TBL_OFICIALIAS (FN_JUZGADO);

ALTER TABLE TRIALS.TBL_OFICIALIAS
ALTER COLUMN NOMBRE TYPE VARCHAR(60);