INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Victimas', 318, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Imputados', 318, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Ministerio Publico', 318, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Tercero Involucrado', 318, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Victimario - Promovente', 318, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Imputado - Abogado patrono', 318, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Imputado - Abogado autorizado pero no patrono', 318, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Promovente', 318, 0);
