-- creación de mensajero. --
INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Julian', 'Gutierrez', '', '', 1, 'mensajero@mensajero.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, '436ca573-7026-47b4-90b3-18a1762dd4d3', 3, 8
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';
