UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = Null
WHERE UPPER(S_NOMBRE) = 'PENAL';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = 6
WHERE UPPER(S_NOMBRE) = 'CARPETA DE EJECUCIÓN';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = 5
WHERE UPPER(S_NOMBRE) = 'CARPETA DE JUICIO';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = 0
WHERE UPPER(S_NOMBRE) = 'CAUSAS PENALES CON DETENIDO';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = 0
WHERE UPPER(S_NOMBRE) = 'CAUSAS PENALES POR ORDEN DE APREHENSIÓN';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = 0
WHERE UPPER(S_NOMBRE) = 'CAUSAS PENALES SIN DETENIDO';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = Null
WHERE UPPER(S_NOMBRE) = 'EXPEDIENTILLO DE ACTUACIONES S/N';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = 2
WHERE UPPER(S_NOMBRE) = 'EXPEDIENTILLO DE CONTROL DE ACTOS DE INVESTIGACIÓN';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = Null
WHERE UPPER(S_NOMBRE) = 'EXPEDIENTILLO DE CONTROL JUDICIAL';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = 3
WHERE UPPER(S_NOMBRE) = 'EXPEDIENTILLO DE EXHORTO';

UPDATE TRIALS.TBL_TIPO_JUICIO
SET N_TIPO_CAUSA = Null
WHERE UPPER(S_NOMBRE) = 'OTROS';
