
INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (34, 'Reasignación de expediente', 'ADMINISTRADOR_SISTEMA,ADMINISTRADOR_JUZGADO,CAPTURISTA', '/api/workflow/reasignacionExpediente',8,3);