-- SE ACTUALIZA N_MAX_ASIGNACIONES Y SE COLOCA NOMENCLATURA DE JUZGADOS.

UPDATE TRIALS.TBL_JUZGADOS
SET N_MAX_ASIGNACIONES = 5, S_NOMENCLATURA = 'PUEBLA'
WHERE S_NOMBRE IN ('Juzgado 1 penal TEST', 'Juzgado 1 Justicia para adolescentes TEST');