UPDATE TRIALS.TBL_MENUS
SET S_ROL = 'OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,SECRETARIO,PROYECTISTA,SECRETARIO,ENCARGADO_SALA,ADMINISTRADOR_JUZGADO,OFICIAL_MAYOR_OFICIALIA'
WHERE S_LINK = 'api/workflow/oficio';


UPDATE TRIALS.TBL_MENUS
SET S_ROL = 'OFICIAL_MAYOR_OFICIALIA,OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,TECNICO_JUZGADO,SECRETARIO,ENCARGADO_SALA,DILIGENCIARIO,JUEZ,ADMINISTRADOR_JUZGADO,PROYECTISTA'
WHERE S_LINK = 'api/bandeja/oficios';

