-- SE AGREGA REGISTRO PARA EL JUZGADO PENAL --
INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS(PN_ID, FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR)
VALUES(nextval('TRIALS.SEQ_JUZGADO_FOLIOS_ID'), 8, 0, 1, 2025);