INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Victimas', 307, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Imputados', 307, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Ministerio Publico', 307, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Tercer Involucrado', 307, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Victimario - Promovente', 307, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Imputado - Abogado patrono', 307, 0);

INSERT INTO TRIALS.TBL_TIPO_PARTES(PN_ID, N_VERSION, S_NOMBRE, FN_TIPO_JUICIO, N_ESTADO)
VALUES(nextval('TRIALS.SEQ_TIPO_PARTES_ID'), 0, 'Imputado - Abogado autorizado pero no patrono', 307, 0);