--Insertar tipo de juicio hijos
INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Causas Penales con Detenido', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Causas Penales sin Detenido', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Causas Penales por Orden De Aprehensión', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo de Control Judicial', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo de Control De Actos De Investigación', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo De Exhorto', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Carpetas De Ejecución', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Carpetas De Juicio', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo De Actuaciones S/N', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Otros', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

--penal adolescente
INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Causas Penales con Detenido', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Causas Penales sin Detenido', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Causas Penales por Orden De Aprehensión', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo de Control Judicial', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo de Control De Actos De Investigación', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo De Exhorto', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Carpetas De Ejecución', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Carpetas De Juicio', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo De Actuaciones S/N', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Otros', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) '), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Justicia para adolescentes (ORAL) ')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES';