INSERT INTO TRIALS.TBL_TIPO_AUDIENCIA(PN_ID, n_VERSION, S_NOMBRE, N_ESTADO, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_AUDIENCIA_ID'), 0, TA.S_NOMBRE, 0, 400
FROM TRIALS.TBL_TIPO_AUDIENCIA TA 
JOIN TRIALS.TBL_MATERIAS MATERIA ON TA.FN_MATERIA = MATERIA.PN_ID AND MATERIA.S_NOMBRE = 'PENAL';