-- CREACIÓN DE JUZGADO PENAL
INSERT INTO TRIALS.TBL_JUZGADOS(PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE, N_ESTADO)
VALUES(8, 0, 'Juzgado 1 Justicia para adolescentes TEST', 400, 1, 0);

-- ASIGNACIÓN DE TIPOS DE JUICIOS
INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO(FN_JUZGADO, FN_TIPOJUICIO)
VALUES
    (8, 318);
