-- Corrección de oficio
UPDATE TRIALS.TBL_MENUS
SET S_ROL = 'OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,SECRETARIO,PROYECTISTA,SECRETARIO,ENCARGADO_SALA,ADMINISTRADOR_JUZGADO,OFICIAL_MAYOR_OFICIALIA'
WHERE S_LINK = 'api/workflow/oficio';


UPDATE TRIALS.TBL_MENUS
SET S_ROL = 'OFICIAL_MAYOR_OFICIALIA,OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,TECNICO_JUZGADO,SECRETARIO,ENCARGADO_SALA,DILIGENCIARIO,JUEZ,ADMINISTRADOR_JUZGADO,PROYECTISTA'
WHERE S_LINK = 'api/bandeja/oficios';

-- Corrección de conceptos:
UPDATE TRIALS.TBL_MENUS
SET S_NOMBRE = 'Motivos de turnado'
WHERE S_LINK = 'api/core/conceptos';

-- corrección menu oara administrador del juzgado:
UPDATE TRIALS.TBL_MENUS
SET S_ROL = 'ADMINISTRADOR_SISTEMA'
WHERE S_NOMBRE IN ('Sedes', 'Instituciones','Oficialías', 'Órgano jurisdiccional', 'Salas');

-- Corrección menu para oficial mayor juzgado en menu.
UPDATE TRIALS.TBL_MENUS
SET S_ROL = 'OFICIAL_MAYOR_OFICIALIA,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO,OFICIAL_MAYOR_JUZGADO'
WHERE S_NOMBRE = 'Historial';