ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE ADD COLUMN FN_PERSONA INTEGER;
ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE ADD COLUMN N_ESTADO_ENVIO INTEGER;

ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE 
ADD CONSTRAINT fk_documento_persona_mensajero 
FOREIGN KEY (FN_PERSONA) 
REFERENCES TRIALS.TBL_PERSONAS (PN_ID);