ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE
ADD COLUMN N_TIPO_SENTENCIA INTEGER;

ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE
ADD COLUMN N_TIPO_RESOLUCION INTEGER;

ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE
ADD COLUMN S_TIPO_EXTRACTO_SENTENCIA TEXT;

