
DROP TABLE IF EXISTS TRIALS.TBL_PAISES;

CREATE TABLE TRIALS.TBL_PAISES(
    PN_ID       INT NOT NULL PRIMARY KEY,
    s_key     VARCHAR(2) NOT NULL,
    S_NOMBRE_OFICIAL VARCHAR(250) NOT NULL,
    S_NOMBRE_COMUN   VARCHAR(250) NOT NULL
);

INSERT INTO TRIALS.TBL_PAISES (PN_ID, s_key, S_NOMBRE_OFICIAL, S_NOMBRE_COMUN)
VALUES
  (1, 'GS', 'Georgia del Sur y las Islas Sandwich del Sur', 'Islas Georgias del Sur y Sandwich del Sur'),
    (2, 'GD', 'Granada', 'Grenada'),
    (3, 'CH', 'Confederación Suiza', 'Suiza'),
    (4, 'SL', 'República de Sierra Leona', 'Sierra Leone'),
    (5, 'HU', 'Hungría', 'Hungría'),
    (6, 'TW', 'República de China en Taiwán', 'Taiwán'),
    (7, 'WF', 'Territorio de las Islas Wallis y Futuna', 'Wallis y Futuna'),
    (8, 'BB', 'Barbados', 'Barbados'),
    (9, 'PN', 'Grupo de Islas Pitcairn', 'Islas Pitcairn'),
    (10, 'CI', 'República de Côte Ivoire', 'Costa de Marfil'),
    (11, 'TN', 'República de Túnez', 'Túnez'),
    (12, 'IT', 'República Italiana', 'Italia'),
    (13, 'BJ', 'República de Benin', 'Benín'),
    (14, 'ID', 'República de Indonesia', 'Indonesia'),
    (15, 'CV', 'República de Cabo Verde', 'Cabo Verde'),
    (16, 'KN', 'Federación de San Cristóbal y Nevis', 'San Cristóbal y Nieves'),
    (17, 'LA', 'República Democrática Popular Lao', 'Laos'),
    (18, 'BQ', 'Bonaire, San Eustaquio y Saba', 'Caribe Neerlandés'),
    (19, 'UG', 'República de Uganda', 'Uganda'),
    (20, 'AD', 'Principado de Andorra', 'Andorra'),
    (21, 'BI', 'República de Burundi', 'Burundi'),
    (22, 'ZA', 'República de Sudáfrica', 'Sudáfrica'),
    (23, 'FR', 'República francesa', 'Francia'),
    (24, 'LY', 'Estado de Libia', 'Libia'),
    (25, 'MX', 'Estados Unidos Mexicanos', 'México'),
    (26, 'GA', 'República de Gabón', 'Gabón'),
    (27, 'MP', 'Mancomunidad de las Islas Marianas del Norte', 'Islas Marianas del Norte'),
    (28, 'MK', 'República de Macedonia del Norte', 'Macedonia del Norte'),
    (29, 'CN', 'República Popular de China', 'China'),
    (30, 'YE', 'República de Yemen', 'Yemen'),
    (31, 'BL', 'Colectividad de San Barthélemy', 'San Bartolomé'),
    (32, 'GG', 'Bailía de Guernsey', 'Guernsey'),
    (33, 'SB', 'Islas Salomón', 'Islas Salomón'),
    (34, 'SJ', 'Svalbard og Jan Mayen', 'Islas Svalbard y Jan Mayen'),
    (35, 'FO', 'Islas Feroe', 'Islas Faroe'),
    (36, 'UZ', 'República de Uzbekistán', 'Uzbekistán'),
    (37, 'EG', 'República Árabe de Egipto', 'Egipto'),
    (38, 'SN', 'República de Senegal', 'Senegal'),
    (39, 'LK', 'República Democrática Socialista de Sri Lanka', 'Sri Lanka'),
    (40, 'PS', 'Estado de Palestina', 'Palestina'),
    (41, 'BD', 'República Popular de Bangladesh', 'Bangladesh'),
    (42, 'PE', 'República de Perú', 'Perú'),
    (43, 'SG', 'República de Singapur', 'Singapur'),
    (44, 'TR', 'República de Turquía', 'Turquía'),
    (45, 'AF', 'República Islámica de Afganistán', 'Afganistán'),
    (46, 'AW', 'Aruba', 'Aruba'),
    (47, 'CK', 'Islas Cook', 'Islas Cook'),
    (48, 'GB', 'Reino Unido de Gran Bretaña e Irlanda del Norte', 'Reino Unido'),
    (49, 'ZM', 'República de Zambia', 'Zambia'),
    (50, 'FI', 'República de Finlandia', 'Finlandia'),
    (51, 'NE', 'República de Níger', 'Níger'),
    (52, 'CX', 'Territorio de la Isla de Navidad', 'Isla de Navidad'),
    (53, 'TK', 'Tokelau', 'Islas Tokelau'),
    (54, 'GW', 'República de Guinea-Bissau', 'Guinea-Bisáu'),
    (55, 'AZ', 'República de Azerbaiyán', 'Azerbaiyán'),
    (56, 'RE', 'Isla de la Reunión', 'Reunión'),
    (57, 'DJ', 'República de Djibouti', 'Djibouti'),
    (58, 'KP', 'República Popular Democrática de Corea', 'Corea del Norte'),
    (59, 'MU', 'República de Mauricio', 'Mauricio'),
    (60, 'MS', 'Montserrat', 'Montserrat'),
    (61, 'VI', 'Islas Vírgenes de los Estados Unidos', 'Islas Vírgenes de los Estados Unidos'),
    (62, 'CO', 'República de Colombia', 'Colombia'),
    (63, 'GR', 'República Helénica', 'Grecia'),
    (64, 'HR', 'República de Croacia', 'Croacia'),
    (65, 'MA', 'Reino de Marruecos', 'Marruecos'),
    (66, 'DZ', 'República Argelina Democrática y Popular', 'Argelia'),
    (67, 'AQ', 'Antártida', 'Antártida'),
    (68, 'NL', 'Países Bajos', 'Países Bajos'),
    (69, 'SD', 'República de Sudán', 'Sudán'),
    (70, 'FJ', 'República de Fiji', 'Fiyi'),
    (71, 'LI', 'Principado de Liechtenstein', 'Liechtenstein'),
    (72, 'NP', 'República Democrática Federal de Nepal', 'Nepal'),
    (73, 'PR', 'Asociado de Puerto Rico', 'Puerto Rico'),
    (74, 'GE', 'Georgia', 'Georgia'),
    (75, 'PK', 'República Islámica de Pakistán', 'Pakistán'),
    (76, 'MC', 'Principado de Mónaco', 'Mónaco'),
    (77, 'BW', 'República de Botswana', 'Botswana'),
    (78, 'LB', 'República Libanesa', 'Líbano'),
    (79, 'PG', 'Estado Independiente de Papúa Nueva Guinea', 'Papúa Nueva Guinea'),
    (80, 'YT', 'Departamento de Mayotte', 'Mayotte'),
    (81, 'DO', 'República Dominicana', 'República Dominicana'),
    (82, 'NF', 'Territorio de la Isla Norfolk', 'Isla de Norfolk'),
    (83, 'BV', 'Isla Bouvet', 'Isla Bouvet'),
    (84, 'QA', 'Estado de Qatar', 'Catar'),
    (85, 'MG', 'República de Madagascar', 'Madagascar'),
    (86, 'IN', 'República de la India', 'India'),
    (87, 'SY', 'República Árabe Siria', 'Siria'),
    (88, 'ME', 'Montenegro', 'Montenegro'),
    (89, 'SZ', 'Reino de eSwatini', 'Suazilandia'),
    (90, 'PY', 'República de Paraguay', 'Paraguay'),
    (91, 'SV', 'República de El Salvador', 'El Salvador'),
    (92, 'UA', 'Ucrania', 'Ucrania'),
    (93, 'IM', 'Isla de Man', 'Isla de Man'),
    (94, 'NA', 'República de Namibia', 'Namibia'),
    (95, 'AE', 'Emiratos Árabes Unidos', 'Emiratos Árabes Unidos'),
    (96, 'BG', 'República de Bulgaria', 'Bulgaria'),
    (97, 'GL', 'Groenlandia', 'Groenlandia'),
    (98, 'DE', 'República Federal de Alemania', 'Alemania'),
    (99, 'KH', 'Reino de Camboya', 'Camboya'),
    (100, 'IQ', 'República de Irak', 'Irak'),
    (101, 'TF', 'Territorio del Francés Tierras australes y antárticas', 'Tierras Australes y Antárticas Francesas'),
    (102, 'SE', 'Reino de Suecia', 'Suecia'),
    (103, 'CU', 'República de Cuba', 'Cuba'),
    (104, 'KG', 'República Kirguisa', 'Kirguizistán'),
    (105, 'RU', 'Federación de Rusia', 'Rusia'),
    (106, 'MY', 'Malasia', 'Malasia'),
    (107, 'ST', 'República Democrática de Santo Tomé y Príncipe', 'Santo Tomé y Príncipe'),
    (108, 'CY', 'República de Chipre', 'Chipre'),
    (109, 'CA', 'Canadá', 'Canadá'),
    (110, 'MW', 'República de Malawi', 'Malawi'),
    (111, 'SA', 'Reino de Arabia Saudita', 'Arabia Saudí'),
    (112, 'BA', 'Bosnia y Herzegovina', 'Bosnia y Herzegovina'),
    (113, 'ET', 'República Democrática Federal de Etiopía', 'Etiopía'),
    (114, 'ES', 'Reino de España', 'España'),
    (115, 'SI', 'República de Eslovenia', 'Eslovenia'),
    (116, 'OM', 'Sultanato de Omán', 'Omán'),
    (117, 'PM', 'San Pedro y Miquelón', 'San Pedro y Miquelón'),
    (118, 'MO', 'Macao, Región Administrativa Especial de la República Popular China', 'Macao'),
    (119, 'SM', 'Serenísima República de San Marino', 'San Marino'),
    (120, 'LS', 'Reino de Lesotho', 'Lesotho'),
    (121, 'MH', 'República de las Islas Marshall', 'Islas Marshall'),
    (122, 'SX', 'Sint Maarten', 'Sint Maarten'),
    (123, 'IS', 'Islandia', 'Islandia'),
    (124, 'LU', 'Gran Ducado de Luxemburgo', 'Luxemburgo'),
    (125, 'AR', 'República Argentina', 'Argentina'),
    (126, 'TC', 'Islas Turcas y Caicos', 'Islas Turks y Caicos'),
    (127, 'NR', 'República de Nauru', 'Nauru'),
    (128, 'CC', 'Territorio de los (Keeling) Islas Cocos', 'Islas Cocos o Islas Keeling'),
    (129, 'EH', 'República Árabe Saharaui Democrática', 'Sahara Occidental'),
    (130, 'DM', 'Mancomunidad de Dominica', 'Dominica'),
    (131, 'CR', 'República de Costa Rica', 'Costa Rica'),
    (132, 'AU', 'Mancomunidad de Australia', 'Australia'),
    (133, 'TH', 'Reino de Tailandia', 'Tailandia'),
    (134, 'HT', 'República de Haití', 'Haití'),
    (135, 'TV', 'Tuvalu', 'Tuvalu'),
    (136, 'HN', 'República de Honduras', 'Honduras'),
    (137, 'GQ', 'República de Guinea Ecuatorial', 'Guinea Ecuatorial'),
    (138, 'LC', 'Santa Lucía', 'Santa Lucía'),
    (139, 'PF', 'Polinesia francés', 'Polinesia Francesa'),
    (140, 'BY', 'República de Belarús', 'Bielorrusia'),
    (141, 'LV', 'República de Letonia', 'Letonia'),
    (142, 'PW', 'República de Palau', 'Palau'),
    (143, 'GP', 'Guadalupe', 'Guadalupe'),
    (144, 'PH', 'República de las Filipinas', 'Filipinas'),
    (145, 'GI', 'Gibraltar', 'Gibraltar'),
    (146, 'DK', 'Reino de Dinamarca', 'Dinamarca'),
    (147, 'CM', 'República de Camerún', 'Camerún'),
    (148, 'GN', 'República de Guinea', 'Guinea'),
    (149, 'BH', 'Reino de Bahrein', 'Bahrein'),
    (150, 'SR', 'República de Suriname', 'Surinam'),
    (151, 'CD', 'República Democrática del Congo', 'Congo (Rep. Dem.)'),
    (152, 'SO', 'República Federal de Somalia', 'Somalia'),
    (153, 'CZ', 'República Checa', 'Chequia'),
    (154, 'NC', 'Nueva Caledonia', 'Nueva Caledonia'),
    (155, 'VU', 'República de Vanuatu', 'Vanuatu'),
    (156, 'SH', 'Santa Elena, Ascensión y Tristán de Acuña', 'Santa Elena, Ascensión y Tristán de Acuña'),
    (157, 'TG', 'República de Togo', 'Togo'),
    (158, 'VG', 'Islas Vírgenes', 'Islas Vírgenes del Reino Unido'),
    (159, 'KE', 'República de Kenya', 'Kenia'),
    (160, 'NU', 'Niue', 'Niue'),
    (161, 'HM', 'Islas Heard y McDonald', 'Islas Heard y McDonald'),
    (162, 'RW', 'República de Rwanda', 'Ruanda'),
    (163, 'EE', 'República de Estonia', 'Estonia'),
    (164, 'RO', 'Rumania', 'Rumania'),
    (165, 'TT', 'República de Trinidad y Tobago', 'Trinidad y Tobago'),
    (166, 'GY', 'República Cooperativa de Guyana', 'Guyana'),
    (167, 'TL', 'República Democrática de Timor-Leste', 'Timor Oriental'),
    (168, 'VN', 'República Socialista de Vietnam', 'Vietnam'),
    (169, 'UY', 'República Oriental del Uruguay', 'Uruguay'),
    (170, 'VA', 'Ciudad del Vaticano', 'Ciudad del Vaticano'),
    (171, 'HK', 'Hong Kong Región Administrativa Especial de la República Popular China', 'Hong Kong'),
    (172, 'AT', 'República de Austria', 'Austria'),
    (173, 'AG', 'Antigua y Barbuda', 'Antigua y Barbuda'),
    (174, 'TM', 'Turkmenistán', 'Turkmenistán'),
    (175, 'MZ', 'República de Mozambique', 'Mozambique'),
    (176, 'PA', 'República de Panamá', 'Panamá'),
    (177, 'FM', 'Estados Federados de Micronesia', 'Micronesia'),
    (178, 'IE', 'República de Irlanda', 'Irlanda'),
    (179, 'CW', 'País de Curazao', 'Curazao'),
    (180, 'GF', 'Guayana', 'Guayana Francesa'),
    (181, 'NO', 'Reino de Noruega', 'Noruega'),
    (182, 'AX', 'Islas Åland', 'Alandia'),
    (183, 'CF', 'República Centroafricana', 'República Centroafricana'),
    (184, 'BF', 'Burkina Faso', 'Burkina Faso'),
    (185, 'ER', 'Estado de Eritrea', 'Eritrea'),
    (186, 'TZ', 'República Unida de Tanzania', 'Tanzania'),
    (187, 'KR', 'República de Corea', 'Corea del Sur'),
    (188, 'JO', 'Reino Hachemita de Jordania', 'Jordania'),
    (189, 'MR', 'República Islámica de Mauritania', 'Mauritania'),
    (190, 'LT', 'República de Lituania', 'Lituania'),
    (191, 'UM', 'Estados Unidos Islas menores alejadas de', 'Islas Ultramarinas Menores de Estados Unidos'),
    (192, 'SK', 'República Eslovaca', 'República Eslovaca'),
    (193, 'AO', 'República de Angola', 'Angola'),
    (194, 'KZ', 'República de Kazajstán', 'Kazajistán'),
    (195, 'MD', 'República de Moldova', 'Moldavia'),
    (196, 'ML', 'República de Malí', 'Mali'),
    (197, 'FK', 'Islas Malvinas', 'Islas Malvinas'),
    (198, 'AM', 'República de Armenia', 'Armenia'),
    (199, 'WS', 'Estado Independiente de Samoa', 'Samoa'),
    (200, 'JE', 'Bailía de Jersey', 'Jersey'),
    (201, 'JP', 'Japón', 'Japón'),
    (202, 'BO', 'Estado Plurinacional de Bolivia', 'Bolivia'),
    (203, 'CL', 'República de Chile', 'Chile'),
    (204, 'US', 'Estados Unidos de América', 'Estados Unidos'),
    (205, 'VC', 'San Vicente y las Granadinas', 'San Vicente y Granadinas'),
    (206, 'BM', 'Bermuda', 'Bermudas'),
    (207, 'SC', 'República de las Seychelles', 'Seychelles'),
    (208, 'IO', 'Territorio Británico del Océano Índico', 'Territorio Británico del Océano Índico'),
    (209, 'GT', 'República de Guatemala', 'Guatemala'),
    (210, 'EC', 'República del Ecuador', 'Ecuador'),
    (211, 'MQ', 'Martinica', 'Martinica'),
    (212, 'TJ', 'República de Tayikistán', 'Tayikistán'),
    (213, 'MT', 'República de Malta', 'Malta'),
    (214, 'GM', 'República de Gambia', 'Gambia'),
    (215, 'NG', 'República Federal de Nigeria', 'Nigeria'),
    (216, 'BS', 'Commonwealth de las Bahamas', 'Bahamas'),
    (217, 'XK', 'República de Kosovo', 'Kosovo'),
    (218, 'KW', 'Estado de Kuwait', 'Kuwait'),
    (219, 'MV', 'República de las Maldivas', 'Maldivas'),
    (220, 'SS', 'República de Sudán del Sur', 'Sudán del Sur'),
    (221, 'IR', 'República Islámica de Irán', 'Irán'),
    (222, 'AL', 'República de Albania', 'Albania'),
    (223, 'BR', 'República Federativa del Brasil', 'Brasil'),
    (224, 'RS', 'República de Serbia', 'Serbia'),
    (225, 'BZ', 'Belice', 'Belice'),
    (226, 'MM', 'República de la Unión de Myanmar', 'Myanmar'),
    (227, 'BT', 'Reino de Bután', 'Bután'),
    (228, 'VE', 'República Bolivariana de Venezuela', 'Venezuela'),
    (229, 'LR', 'República de Liberia', 'Liberia'),
    (230, 'JM', 'Jamaica', 'Jamaica'),
    (231, 'PL', 'República de Polonia', 'Polonia'),
    (232, 'KY', 'Islas Caimán', 'Islas Caimán'),
    (233, 'BN', 'Nación de Brunei, Morada de la Paz', 'Brunei'),
    (234, 'KM', 'Unión de las Comoras', 'Comoras'),
    (235, 'GU', 'Guam', 'Guam'),
    (236, 'TO', 'Reino de Tonga', 'Tonga'),
    (237, 'KI', 'República Independiente y Soberano de Kiribati', 'Kiribati'),
    (238, 'GH', 'República de Ghana', 'Ghana'),
    (239, 'TD', 'República de Chad', 'Chad'),
    (240, 'ZW', 'República de Zimbabue', 'Zimbabue'),
    (241, 'MF', 'Saint Martin', 'Saint Martin'),
    (242, 'MN', 'Mongolia', 'Mongolia'),
    (243, 'PT', 'República Portuguesa', 'Portugal'),
    (244, 'AS', 'Samoa Americana', 'Samoa Americana'),
    (245, 'CG', 'República del Congo', 'Congo'),
    (246, 'BE', 'Reino de Bélgica', 'Bélgica'),
    (247, 'IL', 'Estado de Israel', 'Israel'),
    (248, 'NZ', 'Nueva Zelanda', 'Nueva Zelanda'),
    (249, 'NI', 'República de Nicaragua', 'Nicaragua'),
    (250, 'AI', 'Anguila', 'Anguilla');