INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (26, 'Libro de Gobierno', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO,ENCARGADO_SALA,JUEZ,OFICIAL_MAYOR_JUZGADO,OFICIAL_MAYOR_OFICIALIA,SECRETARIO,TECNICO_JUZGADO', '', 5, null);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (27, 'Buscador', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO,ENCARGADO_SALA,JUEZ,OFICIAL_MAYOR_JUZGADO,OFICIAL_MAYOR_OFICIALIA,SECRETARIO,TECNICO_JUZGADO', 'api/workflow/librogobierno', 1, 26);
