ALTER TABLE TRIALS.TBL_DOMICILIOS ADD COLUMN S_LATITUD VARCHAR(13);

ALTER TABLE TRIALS.TBL_DOMICILIOS ADD COLUMN S_LONGITUD VARCHAR(13);

ALTER TABLE TRIALS.TBL_DOMICILIOS ADD COLUMN S_CIUDAD VARCHAR(60);
