ALTER TABLE TRIALS.TBL_NOTIFICACIONES
    DROP COLUMN IF EXISTS T_FECHA_PUBLICACION,
    DROP COLUMN IF EXISTS T_FECHA_RESOLUCION,
    DROP COLUMN IF EXISTS S_CONCEPTO,
    DROP COLUMN IF EXISTS N_TIPO,
    DROP COLUMN IF EXISTS FN_CARPETA,
    DROP COLUMN IF EXISTS FN_LISTA;

ALTER TABLE TRIALS.TBL_NOTIFICACIONES
    ADD COLUMN FN_DOCUMENTO INT NOT NULL;

CREATE INDEX IF NOT EXISTS IDX_NOTIFICACIONES_DOCUMENTO ON TRIALS.TBL_NOTIFICACIONES (FN_DOCUMENTO);

ALTER TABLE TRIALS.TBL_NOTIFICACIONES
    ADD CONSTRAINT FK_NOTIFICACIONES_DOCUMENTO
    FOREIGN KEY (FN_DOCUMENTO) REFERENCES TRIALS.TBL_DOCUMENTOS (PN_ID);