ALTER TABLE TRIALS.TBL_NOTIFICACIONES
ADD COLUMN FN_LISTA INT,
ADD CONSTRAINT FK_LISTA FOREIGN KEY (FN_LISTA) REFERENCES TRIALS.TBL_LISTA_ESTRADOS(PN_ID);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICACIONES_FN_LISTA ON TRIALS.TBL_NOTIFICACIONES (FN_LISTA);

ALTER TABLE TRIALS.TBL_LISTA_ESTRADOS
ADD COLUMN T_FECHA_VENCIMIENTO TIMESTAMP NULL;

ALTER TABLE TRIALS.TBL_NOTIFICACIONES
ADD COLUMN N_TIPO INT;

ALTER TABLE TRIALS.TBL_NOTIFICACIONES
ADD COLUMN FN_CARPETA INT NOT NULL;

ALTER TABLE TRIALS.TBL_NOTIFICACIONES
ADD CONSTRAINT FK_CARPETA FOREIGN KEY (FN_CARPETA) REFERENCES TRIALS.TBL_CARPETAS(PN_ID);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICACIONES_FN_CARPETA ON TRIALS.TBL_NOTIFICACIONES (FN_CARPETA);


