ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS ADD COLUMN N_TIPO_NOTIFICACION INT;

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS ADD COLUMN S_CORREO_NOTIFICACION VARCHAR(50);

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS ADD COLUMN FN_DOMICILIO INT
REFERENCES TRIALS.TBL_DOMICILIOS (PN_ID);