DROP SEQUENCE IF EXISTS TRIALS.SEQ_AUDIENCIA_ID;
CREATE SEQUENCE TRIALS.SEQ_AUDIENCIA_ID START WITH 100 increment by 1;

DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOC_DETALLE_ID;
CREATE SEQUENCE TRIALS.SEQ_DOC_DETALLE_ID START WITH 100 increment by 1;

DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOC_CONTENIDO_ID;
CREATE SEQUENCE TRIALS.SEQ_DOC_CONTENIDO_ID START WITH 100 increment by 1;