ALTER TABLE TRIALS.TBL_PERSONA_DETALLE
ADD COLUMN FN_DOMICILIO INT;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE
ADD CONSTRAINT FN_DOMICILIO
FOREIGN KEY (FN_DOMICILIO) REFERENCES TRIALS.TBL_DOMICILIOS(PN_ID);

CREATE INDEX IDX_FN_DOMICILIO ON  TRIALS.TBL_PERSONA_DETALLE(FN_DOMICILIO);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE
RENAME COLUMN N_PAIS_NACIMIENTO TO S_PAIS_NACIMIENTO;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE
ALTER COLUMN S_PAIS_NACIMIENTO TYPE VARCHAR(100);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE 
ALTER COLUMN FN_PERSONA_DOCUMENTO DROP NOT NULL;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE 
ALTER COLUMN FN_LENGUA_INDIGENA DROP NOT NULL;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE 
ALTER COLUMN FN_NACIONALIDAD DROP NOT NULL;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE 
ALTER COLUMN FN_ESCOLARIDAD DROP NOT NULL;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE 
ALTER COLUMN FN_DOCUMENTO_IDENTIFICACION DROP NOT NULL;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE 
DROP COLUMN S_RAZON_SOCIAL;