DROP SEQUENCE IF EXISTS TRIALS.SEQ_LISTA_ESTRADOS_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_LISTA_ESTRADOS_ID START WITH 2;
ALTER SEQUENCE TRIALS.SEQ_LISTA_ESTRADOS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_LISTA_ESTRADOS;

CREATE TABLE TRIALS.TBL_LISTA_ESTRADOS
(
   PN_ID                 INT            NOT NULL PRIMARY KEY,
   T_FECHA_ALTA          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
   S_USUARIO_ALTA        VARCHAR(50) NOT NULL
);


