ALTER TABLE TRIALS.TBL_LISTA_ESTRADOS
  DROP COLUMN IF EXISTS S_USUARIO_ALTA;

ALTER TABLE TRIALS.TBL_LISTA_ESTRADOS
  ADD COLUMN FN_PERSONA INT NOT NULL;

ALTER TABLE TRIALS.TBL_LISTA_ESTRADOS
  ADD CONSTRAINT FK_LISTA_ESTRADOS_PERSONA
  FOREIGN KEY (FN_PERSONA)
  REFERENCES TRIALS.TBL_PERSONAS (PN_ID)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;
