ALTER TABLE TRIALS.TBL_DOMICILIOS
ADD COLUMN FN_PAIS_RESIDENCIA INT;

ALTER TABLE TRIALS.TBL_DOMICILIOS ADD CONSTRAINT FK_PAIS_RESIDENCIA
FOREIGN KEY (FN_PAIS_RESIDENCIA) REFERENCES TRIALS.TBL_PAISES(PN_ID);

CREATE INDEX IF NOT EXISTS IDX_FN_PAIS_RESIDENCIA ON TRIALS.TBL_DOMICILIOS (FN_PAIS_RESIDENCIA);

-- Modificar calle
ALTER TABLE TRIALS.TBL_DOMICILIOS ALTER COLUMN S_CALLE DROP NOT NULL;