ALTER TABLE trials.tbl_documentos
RENAME COLUMN FN_ACUERDO_RESPUESTA TO FN_DOCUMENTO_RELACIONADO;

ALTER TABLE TRIALS.TBL_DOCUMENTOS
DROP CONSTRAINT FK_ACUERDO_RESPUESTA;

ALTER TABLE TRIALS.TBL_DOCUMENTOS
ADD CONSTRAINT FK_DOCUMENTO_RELACIONADO
FOREIGN KEY (FN_DOCUMENTO_RELACIONADO)
REFERENCES TRIALS.TBL_DOCUMENTOS(PN_ID);