DROP SEQUENCE IF EXISTS TRIALS.SEQ_NOTIFICACIONES_DETALLES_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_NOTIFICACIONES_DETALLES_ID START WITH 50;
ALTER SEQUENCE TRIALS.SEQ_NOTIFICACIONES_DETALLES_ID INCREMENT BY 1;

CREATE TABLE TRIALS.TBL_NOTIFICACIONES_DETALLE
(
   PN_ID                 INT            NOT NULL PRIMARY KEY,
   FN_NOTIFICACION       INT            NOT NULL REFERENCES TRIALS.TBL_NOTIFICACIONES (PN_ID),
   FN_PERSONA_DOCUMENTO  INT            NOT NULL REFERENCES TRIALS.TBL_PERSONAS_DOCUMENTOS (PN_ID)
);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICACIONES_DETALLES1 ON TRIALS.TBL_NOTIFICACIONES_DETALLE (FN_NOTIFICACION);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICACIONES_DETALLES2 ON TRIALS.TBL_NOTIFICACIONES_DETALLE (FN_PERSONA_DOCUMENTO);