ALTER TABLE TRIALS.TBL_PERSONA_DETALLE
ADD COLUMN FN_EN_REPRESENTACION_DE int;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ADD CONSTRAINT FN_EN_REPRESENTACION_DE
FOREIGN KEY (FN_EN_REPRESENTACION_DE) REFERENCES TRIALS.TBL_PERSONAS_DOCUMENTOS (pn_id)
ON DELETE CASCADE;

CREATE INDEX IDX_FN_EN_REPRESENTACION_DE
ON TRIALS.TBL_PERSONA_DETALLE (FN_EN_REPRESENTACION_DE);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE
ADD COLUMN B_RECIBE_PERCEPCIONES Boolean;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE
RENAME COLUMN S_PAIS_NACIMIENTO TO FN_PAIS_NACIMIENTO;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE
ALTER COLUMN FN_PAIS_NACIMIENTO TYPE INT USING FN_PAIS_NACIMIENTO::INTEGER;;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE
ADD CONSTRAINT FK_FN_PAIS_NACIMIENTO
FOREIGN KEY (FN_PAIS_NACIMIENTO)
REFERENCES TRIALS.TBL_PAISES(PN_ID);

CREATE INDEX IF NOT EXISTS IDX_FN_PAIS_NACIMIENTO
ON TRIALS.TBL_PERSONA_DETALLE (FN_PAIS_NACIMIENTO);

-- CAMBIAR LOS ENUMS POR VARCHAR 

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE RENAME COLUMN N_TIPO_DOMICILIO TO S_TIPO_DOMICILIO;
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ALTER COLUMN S_TIPO_DOMICILIO TYPE VARCHAR(70);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE RENAME COLUMN N_DISCAPACIDAD TO S_DISCAPACIDAD;
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ALTER COLUMN S_DISCAPACIDAD TYPE VARCHAR(70);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE RENAME COLUMN N_ESTADO_CIVIL TO S_ESTADO_CIVIL;
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ALTER COLUMN S_ESTADO_CIVIL TYPE VARCHAR(70);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE RENAME COLUMN N_CONDICION_MIGRATORIA TO S_CONDICION_MIGRATORIA;   
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ALTER COLUMN S_CONDICION_MIGRATORIA TYPE VARCHAR(70);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE RENAME COLUMN N_GRUPO_VULNERABLE TO S_GRUPO_VULNERABLE;
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ALTER COLUMN S_GRUPO_VULNERABLE TYPE VARCHAR(70);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE RENAME COLUMN N_PROFESION_OFICIO TO S_PROFESION_OFICIO;
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ALTER COLUMN S_PROFESION_OFICIO TYPE VARCHAR(70);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE RENAME COLUMN N_INGRESO_MENSUAL_NETO TO S_INGRESO_MENSUAL_NETO;
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ALTER COLUMN S_INGRESO_MENSUAL_NETO TYPE VARCHAR(70);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE RENAME COLUMN N_FRECUENCIA_INGRESO TO S_FRECUENCIA_INGRESO;
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ALTER COLUMN S_FRECUENCIA_INGRESO TYPE VARCHAR(70);

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE RENAME COLUMN N_TIPO_DEFENSOR TO S_TIPO_DEFENSOR;
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ALTER COLUMN S_TIPO_DEFENSOR TYPE VARCHAR(70);

-- Agregar los faltantes
ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ADD COLUMN B_HABLA_LENGUA_INDIGENA BOOLEAN;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ADD COLUMN B_PERTENECE_GRUPO_VULNERABLE BOOLEAN;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ADD COLUMN B_TIENE_BIENES BOOLEAN;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ADD COLUMN B_TIENE_SENIAS_PARTICULARES BOOLEAN;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ADD COLUMN B_PERTENECE_GRUPO_ETNICO BOOLEAN;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ADD COLUMN B_TIENE_RELIGION BOOLEAN;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ADD COLUMN B_TIENE_DEPENDIENTES_ECONOMICOS BOOLEAN;

ALTER TABLE TRIALS.TBL_PERSONA_DETALLE ADD COLUMN B_HABLA_LENGUA_EXTRANJERA BOOLEAN;





