UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Incidente de nulidad' WHERE PN_ID = 1;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Amparo' WHERE PN_ID = 2;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Pruebas actor' WHERE PN_ID = 3;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Pruebas demandado' WHERE PN_ID = 4;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Tercerías ' WHERE PN_ID = 5;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Actuación' WHERE PN_ID = 6;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Reclamación' WHERE PN_ID = 7;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Queja' WHERE PN_ID = 8;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Apelación' WHERE PN_ID = 9;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'P. Tercería actor' WHERE PN_ID = 10;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'P. Tercería demandado' WHERE PN_ID = 11;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Providencia precautoria' WHERE PN_ID = 12;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Responsabilidad' WHERE PN_ID = 13;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Falta de personalidad' WHERE PN_ID = 14;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Cancelación de embargo' WHERE PN_ID = 15;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I.  Lanzamiento' WHERE PN_ID = 16;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Amparo directo' WHERE PN_ID = 17;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. De modificación' WHERE PN_ID = 18;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Tercería excluyente de dominio' WHERE PN_ID = 19;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. De tachas' WHERE PN_ID = 20;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Penal' WHERE PN_ID = 21;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Petición de herencia ' WHERE PN_ID = 22;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Remoción albacea' WHERE PN_ID = 23;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Objeción' WHERE PN_ID = 24;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Innominado' WHERE PN_ID = 25;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Reducción' WHERE PN_ID = 26;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Remoción' WHERE PN_ID = 27;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Modificación de pensión' WHERE PN_ID = 28;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Acumulación' WHERE PN_ID = 29;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Errores y atentados' WHERE PN_ID = 30;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Objeción de pruebas' WHERE PN_ID = 31;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Declinatoria' WHERE PN_ID = 32;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Improcedencia de la via' WHERE PN_ID = 33;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Declaratoria por incompetencia' WHERE PN_ID = 34;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Sentencia de nulidad de actuaciones' WHERE PN_ID = 35;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Pruebas actor excluyente' WHERE PN_ID = 36;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Liquidación de sentencia' WHERE PN_ID = 37;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Tercería coadyugante' WHERE PN_ID = 38;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Planilla de gastos y costos' WHERE PN_ID = 39;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Tercería excluyente de preferencias' WHERE PN_ID = 40;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Legajo de personal' WHERE PN_ID = 41;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Legajo de oficios' WHERE PN_ID = 42;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Reducción de embargo' WHERE PN_ID = 43;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'T. Autorización judicial' WHERE PN_ID = 44;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Ampliación de embargo' WHERE PN_ID = 45;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Falta de personalidad ' WHERE PN_ID = 46;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Prescripción' WHERE PN_ID = 47;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Reposición de documento' WHERE PN_ID = 48;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Aclaración Sentencia' WHERE PN_ID = 49;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Inmatriculación' WHERE PN_ID = 50;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Pruebas colidante' WHERE PN_ID = 51;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Sentencia definitiva' WHERE PN_ID = 52;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Otorgamiento de escritura pública' WHERE PN_ID = 53;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Falta de legitimidad' WHERE PN_ID = 54;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Medios preparatorios a juicio' WHERE PN_ID = 55;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Proyecto de participación' WHERE PN_ID = 56;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Venta de menores' WHERE PN_ID = 57;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Deducción de pensión alimenticia' WHERE PN_ID = 58;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Aumento de pensión alimenticia' WHERE PN_ID = 59;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Sustitución de garantías' WHERE PN_ID = 60;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Excepción y pruebas S.' WHERE PN_ID = 61;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Tomo' WHERE PN_ID = 62;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'R. Revocación' WHERE PN_ID = 63;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Cancelación pensión alimenticia' WHERE PN_ID = 64;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Inventarios y avalúos' WHERE PN_ID = 65;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Cancelación de hipoteca por prescripción' WHERE PN_ID = 66;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. Cancelación de embargo por prescripción' WHERE PN_ID = 67;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Documentos' WHERE PN_ID = 68;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Legajo de acuerdos' WHERE PN_ID = 69;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Legajo de sentencias' WHERE PN_ID = 70;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Incidente de falsedad' WHERE PN_ID = 71;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Incidente de inejecución de sentencia por prescipción' WHERE PN_ID = 72;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Expedientillo de actuación' WHERE PN_ID = 73;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'I. de Homonimia' WHERE PN_ID = 74;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Exp. Principal' WHERE PN_ID = 75;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Incidente de liquidación de sociedad conyugal' WHERE PN_ID = 76;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Incidente de suspensión' WHERE PN_ID = 77;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Reposición de autos' WHERE PN_ID = 78;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Recurso de reconsideración' WHERE PN_ID = 79;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Duplicado del expediente principal' WHERE PN_ID = 80;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Copias certificadas de expediente' WHERE PN_ID = 81;

UPDATE TRIALS.TBL_TIPO_PIEZAS SET S_TIPO = 'Incidente de recusación' WHERE PN_ID = 82;