DROP SEQUENCE IF EXISTS TRIALS.SEQ_NOTIFICACIONES_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_NOTIFICACIONES_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_NOTIFICACIONES_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_NOTIFICACIONES;

CREATE TABLE TRIALS.TBL_NOTIFICACIONES
(
   PN_ID                 INT            NOT NULL PRIMARY KEY,
   S_CONCEPTO            VARCHAR(80)    NOT NULL,
   S_NOTAS               VARCHAR(500),
   N_TIPO                INT,
   T_FECHA_PUBLICACION   DATE,
   T_FECHA_RESOLUCION    DATE,
   N_ESTADO              INT,
   FN_CARPETA            INT           NOT NULL REFERENCES TRIALS.TBL_CARPETAS (PN_ID)
);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICACIONES ON TRIALS.TBL_NOTIFICACIONES (FN_CARPETA);