-- PERMISOS MENU
/*
*  BANDEJA - ID (4)
*  BANDEJA RECEPCION - ID (20)
*  BANDEJA ASIGNADO  - ID (21)
*  AUDIENCIAS        - ID (23)
*  OFICIOS GRID GENERAL  - ID (18)
*  OFICIOS CREACIÓN     -  ID (22)
*  LIBRO DE GOBIERNO   - ID (26)
*/ 
UPDATE TRIALS.TBL_MENUS
SET S_ROL = S_ROL || ',PROYECTISTA'
WHERE PN_ID IN (4, 20, 21, 23, 18, 22, 26);
