UPDATE TRIALS.TBL_MENUS SET S_ROL = S_ROL || ',TECNICO_JUZGADO,SECRETARIO,AUXILIAR_OFICIAL_MAYOR_JUZGADO' WHERE S_NOMBRE = 'Registro';

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'OFICIAL_MAYOR_OFICIALIA,CAPTURISTA,OFICIAL_MAYOR_JUZGADO,TECNICO_JUZGADO,SECRETARIO,AUXILIAR_OFICIAL_MAYOR_JUZGADO' WHERE S_NOMBRE = 'Oficios';