ALTER TABLE TRIALS.TBL_NOTIFICACIONES
ADD COLUMN FN_LISTA INT,
ADD CONSTRAINT FK_LISTA FOREIGN KEY (FN_LISTA) REFERENCES TRIALS.TBL_LISTA_ESTRADOS(PN_ID);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICACIONES_FN_LISTA ON TRIALS.TBL_NOTIFICACIONES (FN_LISTA);

