# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
- develop

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '61927f2e-b580-4647-9b3a-6b59e0eb9f32'
  imageRepository: 'trialsservice'
  containerRegistry: 'pjpuebla.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildNumber)'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Cache@2
      inputs:
        key: 'maven | "$(Agent.OS)" | **/pom.xml'
        restoreKeys: |
          maven | "$(Agent.OS)"
          maven
        path: $(MAVEN_CACHE_FOLDER)
      displayName: Cache Maven local repo

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
        publishJUnitResults: true
        testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
        testRunTitle: 'JUnitRun'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'

    - task: Cache@2
      displayName: Qodana Cache
      inputs:
        key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
        path: '$(Agent.TempDirectory)/qodana/cache'
        restoreKeys: |
          "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
          "$(Build.Repository.Name)"

    - task: QodanaScan@2024
      inputs:
        args: "--baseline,qodana.sarif.json"
      env:
        QODANA_TOKEN: $(QODANA_TOKEN)
        QODANA_ENDPOINT: 'https://qodana.cloud'

    - task: Docker@2
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs:
    - deployment: Deploy_Alpha
      pool:
        vmImage: $(vmImageName)
      environment: alpha-latest
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - script: |
                  echo $(Build.SourcesDirectory)
                  ls -al $(Build.SourcesDirectory)
                displayName: 'List directory contents'

              - task: KubernetesManifest@1
                name: bake
                displayName: Kustomize
                inputs:
                  action: bake
                  renderType: kustomize
                  containers: '$(containerRegistry)/$(imageRepository):$(tag)'
                  kustomizationPath: '$(Build.SourcesDirectory)/kustomize/base'
                  namespace: 'trials'

              - task: KubernetesManifest@1
                displayName: Deploy
                inputs:
                  action: deploy
                  kubernetesServiceConnection: 'alpha-latest-trials-1726267947420'
                  namespace: 'trials'
                  manifests: $(bake.manifestsBundle)