-- AÑADE COLUMNA PARA IDENTIFICAR SI ES UN EXPEDIENTE MIGRADO
-- AÑEDE COLUMNA PARA COLOCAR CU.

ALTER TABLE trials.tbl_carpetas
ADD COLUMN IF NOT EXISTS fn_migrado INT DEFAULT NULL,
ADD CONSTRAINT fk_carpetas_migraciones
    FOREIGN KEY (fn_migrado)
    REFERENCES trials.migraciones (pn_id);

ALTER TABLE TRIALS.TBL_CARPETAS
ADD COLUMN IF NOT EXISTS S_CU VARCHAR(50);