INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (19, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Carlos', 'Morales', '', '', 1, 'archivo@judicial.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, '37920a49-9a62-42a8-87a8-feefaa976f01', 19
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

UPDATE TRIALS.TBL_MENUS SET S_ROL = S_ROL || ',ARCHIVO_JUDICIAL' WHERE S_NOMBRE = 'Bandeja' and S_LINK = '';

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (52, 'Histórico', 'ARCHIVO_JUDICIAL', '/api/archivojudicial/bandeja/historico', 3, 4);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (53, 'Archivo Judicial', 'ARCHIVO_JUDICIAL', '', 7, null);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (54, 'Envío', 'ARCHIVO_JUDICIAL', '/api/archivojudicial/bandeja/envio', 1, 4);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (55, 'Solicitudes', 'ARCHIVO_JUDICIAL', '/api/archivojudicial/bandeja/solicitudes', 2, 4);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (56, 'Consulta', 'ARCHIVO_JUDICIAL', '/api/archivojudicial/bandeja/recibidos', 5, 53);

CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_PAQUETE_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_PAQUETE_ID INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TRIALS.TBL_PAQUETES
(
    PN_ID           INT             NOT NULL PRIMARY KEY,
    N_PAQUETE_ID    INT             NOT NULL,
    N_URGENTE       INT             NOT NULL,
    S_USUARIO_ALTA  VARCHAR(50)     DEFAULT CURRENT_USER,
    T_FECHA_ENVIO   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_TERMINO TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TRIALS.TBL_CARPETAS ADD COLUMN FN_PAQUETE INT;
ALTER TABLE TRIALS.TBL_DOCUMENTOS ADD COLUMN FN_PAQUETE INT;