CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_CONTADORES_JUZGADOS_ID START WITH 1;

CREATE TABLE IF NOT EXISTS TRIALS.TBL_CONTADORES_JUZGADOS (
    PN_ID INT NOT NULL PRIMARY KEY,
    N_VERSION INT,
    FN_JUZGADO INT NOT NULL,
    N_MAX_ASIGNACIONES INT NOT NULL,
    N_CONTADOR_ASIGNACIONES INT NOT NULL DEFAULT 0,
    FN_TIPO_JUICIO INT NOT NULL,
    N_ESTADO INT NOT NULL DEFAULT 0,
    T_FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,

    CONSTRAINT FK_CONTADORES_JUZGADOS_JUZGADO
        FOREIGN KEY (FN_JUZGADO) REFERENCES TRIALS.TBL_JUZGADOS (PN_ID),
    CONSTRAINT FK_CONTADORES_JUZGADOS_TIPO_JUICIO
        FOREIGN KEY (FN_TIPO_JUICIO) REFERENCES TRIALS.TBL_TIPO_JUICIO (PN_ID),
    CONSTRAINT UK_CONTADORES_JUZGADO_TIPO_JUICIO
        UNIQUE (FN_JUZGADO, FN_TIPO_JUICIO)
);

CREATE INDEX IDX_CONTADORES_JUZGADOS_JUZGADO ON TRIALS.TBL_CONTADORES_JUZGADOS (FN_JUZGADO);
CREATE INDEX IDX_CONTADORES_JUZGADOS_TIPO_JUICIO ON TRIALS.TBL_CONTADORES_JUZGADOS (FN_TIPO_JUICIO);
