-- Actualización de nombres de juzgados y de claves:

UPDATE TRIALS.TBL_JUZGADOS
SET S_NOMBRE = 'JUZGADO PRIMERO FAMILIAR', S_CLAVE_JUZGADO = '1201', S_TABLA_UBI='ubicaciones_pue_fa'
WHERE S_NOMBRE = 'Juzgado Primero Familiar';

UPDATE TRIALS.TBL_JUZGADOS
SET S_NOMBRE = 'JUZGADO PRIMERO PENAL', S_CLAVE_JUZGADO = '1301', S_TABLA_UBI=''
WHERE S_NOMBRE = 'Juzgado 1 penal TEST';

UPDATE TRIALS.TBL_JUZGADOS
SET S_NOMBRE = 'JUZGADO NOVENO ESPECIALIZADO EN MATERIA MERCANTIL', S_CLAVE_JUZGADO = '1109', S_TABLA_UBI='ubicaciones09'
WHERE S_NOMBRE = 'Juzgado Noveno Mercantil';
COMMIT;

