CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_CONFIGURACION_ID START WITH 1;
ALTER SEQUENCE TRIALS.SEQ_CONFIGURACION_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_CONFIGURACIONES;
CREATE TABLE TRIALS.TBL_CONFIGURACIONES
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_PROPIEDAD        VARCHAR(100) NOT NULL,
    S_VALOR         VARCHAR(100) NOT NULL,
    N_ESTADO        INT          NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);