CREATE TABLE TRIALS.TBL_MIGRACIONES(
    PN_ID INT NOT NULL PRIMARY KEY,
    N_VERSION INT,
    N_ESTATUS_MIGRACION INT,
    S_OBSERVACIONES VARCHAR(150),
    S_ASIGNACION_ANTERIOR VARCHAR(150),
    S_PUESTO_ASIGNACION_ANTERIOR VARCHAR(150),
    FN_JUZGADO INT,
    FN_CARPETA INT,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER,

    FOREIGN KEY (FN_JUZGADO) REFERENCES TRIALS.TBL_JUZGADOS(PN_ID),
    FOREIGN KEY (FN_CARPETA) REFERENCES TRIALS.TBL_CARPETAS(PN_ID)
);

CREATE SEQUENCE seq_migracion_id
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;