UPDATE TRIALS.TBL_MENU
SET S_ROL = 'ADMINISTRADOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,ENCARGADO_SALA,JUEZ,OFICIAL_MAYOR_JUZGADO,SECRETARIO,TECNICO_JUZGADO,PROYECTISTA,JUEZ,COMISARIO'
WHERE PN_ID = 26;