UPDATE TRIALS.TBL_MENUS
SET S_ROL = 'OFICIAL_MAYOR_OFICIALIA'
WHERE S_NOMBRE = 'Reasignación de expediente';

UPDATE TRIALS.TBL_MENUS
SET S_ROL = 'OFICIAL_MAYOR_JUZGADO,OFICIAL_MAYOR_OFICIALIA,AUXILIAR'
WHERE S_NOMBRE = 'Envios';