-- AÑADE COLUMNA PARA IDENTIFICAR SI ES UN EXPEDIENTE MIGRADO
-- AÑEDE COLUMNA PARA COLOCAR CU.

ALTER TABLE trials.tbl_carpetas
ADD COLUMN IF NOT EXISTS n_migrado INT DEFAULT NULL;

ALTER TABLE TRIALS.TBL_CARPETAS
ADD COLUMN IF NOT EXISTS S_CU VARCHAR(50);