-- AÑADE COLUMNA PARA IDENTIFICAR SI ES UN EXPEDIENTE MIGRADO
-- AÑEDE COLUMNA PARA COLOCAR CU.

ALTER TABLE TRIALS.TBL_CARPETAS
ADD COLUMN IF NOT EXISTS N_MIGRADO INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE TRIALS.TBL_CARPETAS
ADD COLUMN IF NOT EXISTS S_CU VARCHAR(50);