INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (47, 'Estadística', 'ESTADISTICA', '', 1, null);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (48, 'Reportes', 'ESTADISTICA', '/api/reports/main', 1, 47);

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Alejandra', 'Estadistica', '', '', 1, 'estadistica@estadistica.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, 'cc64c866-f340-4a59-9fb7-cd6e9af63ad4', 13, null
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

