INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (47, 'Estadística', 'ESTADISTICA', '', 1, null);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (48, 'Reportes', 'ESTADISTICA', '/api/reportes/index', 1, 47);

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Alejandra', 'Estadistica', '', '', 1, 'estadistica@estadistica.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, 'cc64c866-f340-4a59-9fb7-cd6e9af63ad4', 13, null
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

CREATE TABLE TRIALS.TBL_REPORTES (
    PN_FILA         INTEGER NOT NULL,
    PN_COLUMNA      CHARACTER VARYING(5) NOT NULL,
    S_REPORTE       CHARACTER VARYING(100) NOT NULL,
    STYLE_DATA      JSONB NULL
    EXTRA_DATA      JSONB NULL
);

ALTER TABLE
  TRIALS.TBL_REPORTES
ADD
  CONSTRAINT TBL_REPORTES_PKEY PRIMARY KEY (PN_COLUMNA, PN_FILA);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (47, 'Estadística', 'ESTADISTICA', '', 1, null);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (48, 'Reportes', 'ESTADISTICA', '/api/reportes/index', 1, 47);

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Alejandra', 'Estadistica', '', '', 1, 'estadistica@estadistica.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, 'cc64c866-f340-4a59-9fb7-cd6e9af63ad4', 13, null
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

CREATE TABLE TRIALS.TBL_REPORTES (
    PN_FILA         INTEGER NOT NULL,
    PN_COLUMNA      INTEGER NOT NULL,
    S_REPORTE       CHARACTER VARYING(100) NOT NULL,
    STYLE_DATA      JSONB NULL,
    EXTRA_DATA      JSONB NULL
);

ALTER TABLE
  TRIALS.TBL_REPORTES
ADD
  CONSTRAINT TBL_REPORTES_PKEY PRIMARY KEY (PN_COLUMNA, PN_FILA);

INSERT INTO TRIALS.TBL_REPORTES (PN_FILA, PN_COLUMNA, S_REPORTE, STYLE_DATA, EXTRA_DATA)
VALUES
(0, 0, 'DIVORCIOS', null, null),
(5, 3, 'DIVORCIOS', null, null),
(6, 3, 'DIVORCIOS', null, null),
(7, 3, 'DIVORCIOS', null, null),
(2, 0, 'BANAVIM', null, null),
(3, 0, 'LABORAL', null, null),
(4, 0, 'PENAL', null, null),
(0, 1, 'ADOLESCENTES', null, null),
(0, 2, 'CFM', null, null);