CREATE TABLE TRIALS.TBL_CARPETAS_RUBROS (
    FN_CARPETA INT NOT NULL,
    FN_RUBRO INT NOT NULL,
    T_FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CARPETAS_RUBROS PRIMARY KEY (FN_CARPETA, FN_RUBRO),

    CONSTRAINT FK_CARPETA FOREIGN KEY (FN_CARPETA) REFERENCES TRIALS.TBL_CARPETAS (PN_ID),
    CONSTRAINT FK_RUBRO FOREIGN KEY (FN_RUBRO) REFERENCES TRIALS.TBL_RUBROS (PN_ID)
);

CREATE INDEX idx_carpetasrubros_carpeta ON TRIALS.TBL_CARPETAS_RUBROS USING btree (FN_CARPETA);
CREATE INDEX idx_carpetasrubros_rubro ON TRIALS.TBL_CARPETAS_RUBROS USING btree (FN_RUBRO);