DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOCUMENTO_CONTENIDO_ID;
CREATE SEQUENCE TRIALS.SEQ_DOCUMENTO_CONTENIDO_ID START WITH 50;



DROP TABLE IF EXISTS TRIALS.TBL_DOCUMENTO_CONTENIDO;
CREATE TABLE TRIALS.TBL_DOCUMENTO_CONTENIDO
(
    PN_ID                INT         NOT NULL PRIMARY KEY,
    S_TEXTO              VARCHAR     NOT NULL,
    S_TAMANIO_PAPEL      VARCHAR     NOT NULL,
    FN_DOCUMENTO         INT         NOT NULL,
    
   
    CONSTRAINT "fk_documentos" FOREIGN KEY (FN_DOCUMENTO) references TRIALS.TBL_DOCUMENTOS (PN_ID)
);