DROP SEQUENCE IF EXISTS TRIALS.SEQ_ETAPA_PROCESAL_ID;

CREATE SEQUENCE TRIALS.SEQ_ETAPA_PROCESAL_ID START WITH 100
INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_ETAPA_PROCESAL;

CREATE TABLE TRIALS.TBL_ETAPA_PROCESAL(
    PN_ID              INT          NOT NULL PRIMARY KEY,
    N_VERSION          INT          NULL,
    S_NOMBRE           VARCHAR(250) NOT NULL,
    FN_TIPO_SISTEMA    INT          NULL REFERENCES TRIALS.TBL_TIPO_SISTEMA (PN_ID),
    FN_MATERIA         INT          NOT NULL REFERENCES TRIALS.TBL_MATERIAS (PN_ID),
    FN_TIPO_JUICIO     INT          NULL REFERENCES TRIALS.TBL_TIPO_JUICIO (PN_ID),
    FN_PROCEDIMIENTO   INT          NULL REFERENCES TRIALS.TBL_PROCEDIMIENTOS (PN_ID),
    FN_RUBRO           INT          NULL REFERENCES TRIALS.TBL_RUBROS (PN_ID),
    T_FECHA_ALTA       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA     VARCHAR(50)  NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA    VARCHAR(50)  NOT NULL DEFAULT CURRENT_USER
);

CREATE INDEX IF NOT EXISTS IDX_TIPO_SISTEMA ON TRIALS.TBL_ETAPA_PROCESAL (FN_TIPO_SISTEMA);
CREATE INDEX IF NOT EXISTS IDX_MATERIA ON TRIALS.TBL_ETAPA_PROCESAL (FN_MATERIA);
CREATE INDEX IF NOT EXISTS IDX_TIPO_JUICIO ON TRIALS.TBL_ETAPA_PROCESAL (FN_TIPO_JUICIO);
CREATE INDEX IF NOT EXISTS IDX_PROCEDIMIENTO ON TRIALS.TBL_ETAPA_PROCESAL (FN_PROCEDIMIENTO);
CREATE INDEX IF NOT exists IDX_RUBRO ON TRIALS.TBL_ETAPA_PROCESAL (FN_RUBRO);

--Insert catalogo etapa procesal

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Recepción de documentos', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Presentación de demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Conciliación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contestación de demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Desahogo de pruebas', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Alegatos', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Sentencia', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Apelación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Recepción de documentos', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia inicial', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de conciliación / Audiencia de conciliación y emplazamiento', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de contestación de demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de juicio / Desahogo de pruebas', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Sentencia', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Apelación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Recepción de documentos', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Presentación de la demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contestación de la demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia oral preliminar', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia oral de juicio', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Recepción de demanda y anexos', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Admisión de la demanda auto de exequendo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Emplazamiento', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contestación de la demanda y vista al actor', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Admisión de pruebas', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Desahogo de pruebas', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Alegatos y sentencia', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Apelación / Amparo directo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Recepción de documentos', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Conciliación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contestación de demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Vista para ofrecer pruebas/objeción', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Vista para complementar pruebas', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Calificación de pruebas', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Desahogo de pruebas y alegatos', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Sentencia', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Apelación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Recepción de documentos', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Escrita', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Verbal', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia conciliación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Emplazamiento', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de contestación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de desahogo de pruebas, alegatos y citación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Sentencia (escrita)', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Apelación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo indirecto', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
(SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'), (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa de investigación - Fase inicial', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa de investigación - Fase de investigación complementaria', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa intermedia - Fase escrita', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa intermedia - Fase oral', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa de juicio - Fase de preparación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa de juicio - Fase de audiencia de juicio o audiencia de debate', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa de juicio - Fase de audiencia de individualización penal y la reparación del daño', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Fallo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Investigación y formulación de la remisión o de Control', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Terminación de JEJA J/O responsable de iniciar o terminar etapas.', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Turnado', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Instrucción', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa de control', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Ejecución Atención a Público', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'JUSTICIA PARA ADOLESCENTES'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa prejudicial (n/a)', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Presentación de la demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Emplazamiento', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contestación de demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Réplica', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contrarréplica', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia preliminar', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de juicio', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Sentencia', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Ejecución', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo directo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimiento ordinario'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Presentación de la demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Emplazamiento', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contestación de demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Réplica', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contrarréplica', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia preliminar', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de juicio', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Sentencia', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo directo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Ejecución', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo directo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Recepción de la demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), (SELECT PN_ID FROM TRIALS.TBL_RUBROS WHERE S_NOMBRE = 'Conflictos colectivos de naturaleza económica');

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Secretario instructor', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), (SELECT PN_ID FROM TRIALS.TBL_RUBROS WHERE S_NOMBRE = 'Conflictos colectivos de naturaleza económica');

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Emplazamiento', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), (SELECT PN_ID FROM TRIALS.TBL_RUBROS WHERE S_NOMBRE = 'Conflictos colectivos de naturaleza económica');

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contestación de demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), (SELECT PN_ID FROM TRIALS.TBL_RUBROS WHERE S_NOMBRE = 'Conflictos colectivos de naturaleza económica');

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Se da vista con contestación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), (SELECT PN_ID FROM TRIALS.TBL_RUBROS WHERE S_NOMBRE = 'Conflictos colectivos de naturaleza económica');

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de conciliación y/o admisión y desahogo de', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), (SELECT PN_ID FROM TRIALS.TBL_RUBROS WHERE S_NOMBRE = 'Conflictos colectivos de naturaleza económica');

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Pruebas y alegatos', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), (SELECT PN_ID FROM TRIALS.TBL_RUBROS WHERE S_NOMBRE = 'Conflictos colectivos de naturaleza económica');

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Sentencia', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), (SELECT PN_ID FROM TRIALS.TBL_RUBROS WHERE S_NOMBRE = 'Conflictos colectivos de naturaleza económica');

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Procedimientos especiales'), (SELECT PN_ID FROM TRIALS.TBL_RUBROS WHERE S_NOMBRE = 'Conflictos colectivos de naturaleza económica');

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Formulación de pliego de peticiones', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Huelga'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Emplazamiento', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Huelga'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contestación de demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Huelga'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de conciliación', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Huelga'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Declaración de la huelga', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, (SELECT PN_ID FROM TRIALS.TBL_PROCEDIMIENTOS WHERE S_NOMBRE = 'Huelga'), NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Etapa prejudicial (n/a)', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Presentación de la demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Emplazamiento', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contestación de demanda', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Réplica', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Contrarréplica', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia preliminar', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Audiencia de juicio', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Sentencia', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Ejecución', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

INSERT INTO TRIALS.TBL_ETAPA_PROCESAL (PN_ID, N_VERSION, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO, FN_PROCEDIMIENTO, FN_RUBRO)
SELECT nextval('TRIALS.SEQ_ETAPA_PROCESAL_ID'), 0, 'Amparo directo', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7',
NULL, (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL, NULL, NULL;

