DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOC_DETALLE_ID;
CREATE SEQUENCE TRIALS.SEQ_DOC_DETALLE_ID START WITH 100;

DROP TABLE IF EXISTS TRIALS.TBL_DOCUMENTO_DETALLE;
CREATE TABLE TRIALS.TBL_DOCUMENTO_DETALLE
(
    PN_ID                INT         NOT NULL PRIMARY KEY,
    S_RUTA               VARCHAR(50),
    FN_DOCUMENTO         INT         NOT NULL,
    CONSTRAINT "fk_documentos" FOREIGN KEY (FN_DOCUMENTO) references TRIALS.TBL_DOCUMENTOS (PN_ID)
);

CREATE INDEX IDX_DOCUMENTO_DETALLE1 ON TRIALS.TBL_DOCUMENTO_DETALLE (FN_DOCUMENTO);

DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOC_CONTENIDO_ID;
CREATE SEQUENCE TRIALS.SEQ_DOC_CONTENIDO_ID START WITH 100;

DROP TABLE IF EXISTS TRIALS.TBL_DOCUMENTO_CONTENIDO;
CREATE TABLE TRIALS.TBL_DOCUMENTO_CONTENIDO
(
    PN_ID                INT         NOT NULL PRIMARY KEY,
    S_TEXTO              TEXT,
    FN_DOCUMENTO         INT         NOT NULL,
    CONSTRAINT "fk_documentos" FOREIGN KEY (FN_DOCUMENTO) references TRIALS.TBL_DOCUMENTOS (PN_ID)
);

CREATE INDEX IDX_DOCUMENTO_CONTENIDO1 ON TRIALS.TBL_DOCUMENTO_CONTENIDO (FN_DOCUMENTO);
