INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_CODIGO_POSTAL, S_COLONIA, S_ESTADO_REPUBLICA, S_EXTERIOR, S_INTERIOR, S_LOCALIDAD, S_MUNICIPIO, S_REFERENCIA, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
VALUES (10, 'PERIFÉRICO ECOLÓGICO ARCO SUR', '', '', 'PUEBLA', '4000', '', 'PUEBLA', 'SAN ANDRÉS CHOLULA', '', '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7', '2024-10-03 17:11:34.371602', '2024-10-03 18:41:39.539895');

INSERT INTO TRIALS.TBL_SEDES (FN_DISTRITO, FN_DOMICILIO, N_ESTADO, N_VERSION, PN_ID, S_EXTENSION, S_NOMBRE, S_TELEFONO, S_TIPO, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
VALUES (105, 10, 0, 0, 1, '', 'CIUDAD JUDICIAL SIGLO XXI TEST', '2222238400', 'INTERNO', '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7', '2024-10-03 17:11:34.457937', '2024-10-03 18:41:39.540059');

INSERT INTO TRIALS.TBL_JUZGADOS (FN_MATERIA, FN_SEDE, N_CONTADOR_ASIGNACIONES, N_ESTADO, N_INSTANCIA, N_MAX_ASIGNACIONES, N_VERSION, PN_ID, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
SELECT M.PN_ID, 1, 0, 0, 0, 1, 0, 1, 'Juzgado 1 Mercantil TEST', '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7', '2024-10-03 17:11:34.371602', '2024-10-03 18:41:39.539895'
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_JUZGADOS (FN_MATERIA, FN_SEDE, N_CONTADOR_ASIGNACIONES, N_ESTADO, N_INSTANCIA, N_MAX_ASIGNACIONES, N_VERSION, PN_ID, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
SELECT M.PN_ID, 1, 0, 0, 0, 1, 0, 2, 'Juzgado 2 Mercantil TEST', '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7', '2024-10-03 17:11:34.371602', '2024-10-03 18:41:39.539895'
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_JUZGADOS (FN_MATERIA, FN_SEDE, N_CONTADOR_ASIGNACIONES, N_ESTADO, N_INSTANCIA, N_MAX_ASIGNACIONES, N_VERSION, PN_ID, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
SELECT M.PN_ID, 1, 0, 0, 0, 1, 0, 3, 'Juzgado 3 Mercantil TEST', '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7', '2024-10-03 17:11:34.371602', '2024-10-03 18:41:39.539895'
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_JUZGADOS (FN_MATERIA, FN_SEDE, N_CONTADOR_ASIGNACIONES, N_ESTADO, N_INSTANCIA, N_MAX_ASIGNACIONES, N_VERSION, PN_ID, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
SELECT M.PN_ID, 1, 0, 0, 0, 3, 0, 4, 'Juzgado 4 Mercantil TEST', '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7', '2024-10-03 17:11:34.371602', '2024-10-03 18:41:39.539895'
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_JUZGADOS (FN_MATERIA, FN_SEDE, N_CONTADOR_ASIGNACIONES, N_ESTADO, N_INSTANCIA, N_MAX_ASIGNACIONES, N_VERSION, PN_ID, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
SELECT M.PN_ID, 1, 0, 0, 0, 2, 0, 5, 'Juzgado 5 Mercantil TEST', '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7', '2024-10-03 17:11:34.371602', '2024-10-03 18:41:39.539895'
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_JUZGADOS (FN_MATERIA, FN_SEDE, N_CONTADOR_ASIGNACIONES, N_ESTADO, N_INSTANCIA, N_MAX_ASIGNACIONES, N_VERSION, PN_ID, S_NOMBRE, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
SELECT M.PN_ID, 1, 0, 0, 1, 1, 0, 6, 'Sala 1 Mercantil TEST', '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7', '2024-10-03 17:11:34.371602', '2024-10-03 18:41:39.539895'
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 1, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 2, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 3, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 4, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 5, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 6, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 1, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 2, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 3, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 4, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
SELECT 6, TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (1, 0, 1, 2024, 1);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (1, 1, 1, 2024, 2);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (1, 2, 1, 2024, 3);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (1, 4, 1, 2024, 4);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (2, 0, 1, 2024, 5);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (2, 1, 1, 2024, 6);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (2, 2, 1, 2024, 7);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (2, 4, 1, 2024, 8);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (3, 0, 1, 2024, 9);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (3, 1, 1, 2024, 10);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (3, 2, 1, 2024, 11);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (3, 4, 1, 2024, 12);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (4, 0, 1, 2024, 13);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (4, 1, 1, 2024, 14);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (4, 2, 1, 2024, 15);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (4, 4, 1, 2024, 16);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (5, 0, 1, 2024, 17);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (5, 1, 1, 2024, 18);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (5, 2, 1, 2024, 19);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (5, 4, 1, 2024, 20);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (6, 0, 1, 2024, 21);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (6, 1, 1, 2024, 22);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (6, 2, 1, 2024, 23);

INSERT INTO TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID, N_TIPO_CARPETA, N_VALUE, N_YEAR, PN_ID)
VALUES (6, 4, 1, 2024, 24);

INSERT INTO TRIALS.TBL_OFICIALIAS (FN_SEDE, FN_TIPO, N_ESTADO, N_VERSION, PN_ID, S_NOMBRE, S_RESPONSABLE, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
SELECT 1, TIPO.PN_ID, 0, 0, 1, 'OCPueblaM TEST', '', '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7', '2024-10-03 19:06:24.757648', '2024-10-19 16:06:14.396828'
FROM TRIALS.TBL_TIPO_OFICIALIAS AS TIPO WHERE TIPO.S_NOMBRE = 'Común';

INSERT INTO TRIALS.TBL_OFICIALIAS_MATERIAS (FN_OFICIALIA, FN_MATERIA)
SELECT 1, M.PN_ID
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_OFICIALIAS_JUZGADOS (FN_OFICIALIA, FN_JUZGADO)
VALUES (1, 1);

INSERT INTO TRIALS.TBL_OFICIALIAS_JUZGADOS (FN_OFICIALIA, FN_JUZGADO)
VALUES (1, 2);

INSERT INTO TRIALS.TBL_OFICIALIAS_JUZGADOS (FN_OFICIALIA, FN_JUZGADO)
VALUES (1, 3);

INSERT INTO TRIALS.TBL_OFICIALIAS_JUZGADOS (FN_OFICIALIA, FN_JUZGADO)
VALUES (1, 4);

INSERT INTO TRIALS.TBL_OFICIALIAS_JUZGADOS (FN_OFICIALIA, FN_JUZGADO)
VALUES (1, 5);

INSERT INTO TRIALS.TBL_OFICIALIAS_JUZGADOS (FN_OFICIALIA, FN_JUZGADO)
VALUES (1, 6);

UPDATE TRIALS.TBL_PERSONAS SET FN_JUZGADO = 1 WHERE S_NOMBRES = 'Admin';

INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (3, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_OFICIALIA)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Norma', 'Capturista', '', '', 1, 'capturista@capturista.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, 'cacf013c-6fde-441a-a896-2249e6d6a73e', 3, 1
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (4, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_OFICIALIA)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Ernesto', 'Digitalizador', '', '', 1, 'capturista@capturista.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, '9f2cc20e-20f8-4384-b793-6c972b88ea47', 4, 1
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (5, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_OFICIALIA)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Santiago', 'Oficial Mayor', '', '', 1, 'oficial@oficial.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, 'be3f9af7-b332-4002-8ff8-4555aa767981', 5, 1
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (6, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Martín', 'Secretario', '', '', 1, 'secretario@secretario.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, '6f527032-cec2-48b4-a44c-68d67039e2cc', 6, 1
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (7, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Fernando', 'Oficial Mayor Juzgado', '', '', 1, 'oficialmayorjuzgado@oficialmayorjuzgado.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, '4b7c43cb-bc04-456b-b880-6cbeb5404c3a', 7, 1
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (8, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Iván', 'Tecnico Juzgado', '', '', 1, 'tecnico@tecnico.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, 'd7bc71c5-6c8a-44f7-b081-226865959022', 8, 1
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';
