ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE
ADD COLUMN S_ASUNTO VARCHAR(150),
ADD COLUMN T_FECHA_EMISION TIMESTAMP,
ADD COLUMN T_FECHA_ENTREGA TIMESTAMP,
ADD COLUMN N_ESTADO INT,
ADD COLUMN S_COMENTARIO VARCHAR(150);
