DROP SEQUENCE IF EXISTS TRIALS.SEQ_PROCEDIMIENTOS_ID;

CREATE SEQUENCE TRIALS.SEQ_PROCEDIMIENTOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_PROCEDIMIENTOS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_PROCEDIMIENTOS;

CREATE TABLE TRIALS.TBL_PROCEDIMIENTOS
(
    PN_ID              INT         NOT NULL PRIMARY KEY,
    N_VERSION          INT         NULL,
    S_NOMBRE           VARCHAR(250) NOT NULL,
    N_ESTADO           INT         NOT NULL,
    FN_TIPO_JUICIO     INT         NULL,
    T_FECHA_ALTA       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA    VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA    VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,

    CONSTRAINT "fk_tipo_juicio" FOREIGN KEY (FN_TIPO_JUICIO) REFERENCES TRIALS.TBL_TIPO_JUICIO (PN_ID)
);

CREATE INDEX IDX_TIPO_JUICIO ON TRIALS.TBL_PROCEDIMIENTOS (FN_TIPO_JUICIO);

-- Procedimientos asociados a 'CONFLICTIVIDAD LABORAL EN MATERIA INDIVIDUAL'
INSERT INTO TRIALS.TBL_PROCEDIMIENTOS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, FN_TIPO_JUICIO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_PROCEDIMIENTOS_ID'), 0, 'Procedimiento ordinario', 0, T.PN_ID, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7'
FROM TRIALS.TBL_TIPO_JUICIO T WHERE T.S_NOMBRE = 'CONFLICTIVIDAD LABORAL EN MATERIA INDIVIDUAL';

INSERT INTO TRIALS.TBL_PROCEDIMIENTOS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, FN_TIPO_JUICIO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_PROCEDIMIENTOS_ID'), 0, 'Procedimientos especiales', 0, T.PN_ID, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7'
FROM TRIALS.TBL_TIPO_JUICIO T WHERE T.S_NOMBRE = 'CONFLICTIVIDAD LABORAL EN MATERIA INDIVIDUAL';

INSERT INTO TRIALS.TBL_PROCEDIMIENTOS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, FN_TIPO_JUICIO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_PROCEDIMIENTOS_ID'), 0, 'Paraprocesales', 0, T.PN_ID, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7'
FROM TRIALS.TBL_TIPO_JUICIO T WHERE T.S_NOMBRE = 'CONFLICTIVIDAD LABORAL EN MATERIA INDIVIDUAL';

INSERT INTO TRIALS.TBL_PROCEDIMIENTOS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, FN_TIPO_JUICIO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_PROCEDIMIENTOS_ID'), 0, 'Procedimiento de ejecución por incumplimiento', 0, T.PN_ID, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7'
FROM TRIALS.TBL_TIPO_JUICIO T WHERE T.S_NOMBRE = 'CONFLICTIVIDAD LABORAL EN MATERIA INDIVIDUAL';

INSERT INTO TRIALS.TBL_PROCEDIMIENTOS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, FN_TIPO_JUICIO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_PROCEDIMIENTOS_ID'), 0, 'Tercerías', 0, T.PN_ID, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7'
FROM TRIALS.TBL_TIPO_JUICIO T WHERE T.S_NOMBRE = 'CONFLICTIVIDAD LABORAL EN MATERIA INDIVIDUAL';

INSERT INTO TRIALS.TBL_PROCEDIMIENTOS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, FN_TIPO_JUICIO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_PROCEDIMIENTOS_ID'), 0, 'Seguridad social', 0, T.PN_ID, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7'
FROM TRIALS.TBL_TIPO_JUICIO T WHERE T.S_NOMBRE = 'CONFLICTIVIDAD LABORAL EN MATERIA INDIVIDUAL';

-- Procedimientos asociados a 'CONFLICTIVIDAD LABORAL EN MATERIA COLECTIVA'
INSERT INTO TRIALS.TBL_PROCEDIMIENTOS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, FN_TIPO_JUICIO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_PROCEDIMIENTOS_ID'), 0, 'Huelga', 0, T.PN_ID, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7'
FROM TRIALS.TBL_TIPO_JUICIO T WHERE T.S_NOMBRE = 'CONFLICTIVIDAD LABORAL EN MATERIA COLECTIVA';

INSERT INTO TRIALS.TBL_PROCEDIMIENTOS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, FN_TIPO_JUICIO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_PROCEDIMIENTOS_ID'), 0, 'Especiales', 0, T.PN_ID, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7'
FROM TRIALS.TBL_TIPO_JUICIO T WHERE T.S_NOMBRE = 'CONFLICTIVIDAD LABORAL EN MATERIA COLECTIVA';