ALTER TABLE TRIALS.TBL_TIPO_PARTES
ADD CONSTRAINT FK_TBL_TIPO_PARTES_FN_MATERIA FOREIGN KEY (FN_MATERIA)
REFERENCES TRIALS.TBL_MATERIAS(PN_ID);

ALTER TABLE TRIALS.TBL_TIPO_PARTES
    ALTER COLUMN S_ESTADO TYPE INT USING S_ESTADO::INT;

ALTER TABLE TRIALS.TBL_TIPO_PARTES
    RENAME COLUMN S_ESTADO TO N_ESTADO;