CREATE SEQUENCE TRIALS.SEQ_TIPO_PARTES_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_TIPO_PARTES_ID INCREMENT BY 1;
CREATE TABLE TRIALS.TBL_TIPO_PARTES
(
	PN_ID		INT		NOT NULL PRIMARY KEY,
	N_VERSION	INT,
	S_NOMBRE	VARCHAR(100)	NOT NULL,
	FN_MATERIA	BIGINT		NOT NULL,
	T_FECHA_ALTA	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP,
	T_FECHA_EDITA	TIMESTAMP	DEFAULT	CURRENT_TIMESTAMP,
	S_USUARIO_ALTA	VARCHAR(50)	DEFAULT CURRENT_USER,
	S_USUARIO_EDITA	VARCHAR(50)	DEFAULT CURRENT_USER,
	S_ESTADO	CHAR(1)		NOT NULL
);

ALTER TABLE TRIALS.TBL_TIPO_PARTES
ADD CONSTRAINT FK_TBL_TIPO_PARTES_FN_MATERIA FOREIGN KEY (FN_MATERIA)
REFERENCES TRIALS.TBL_MATERIAS(PN_ID);