CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_REL_JUZGADO_ESPECIALIDAD_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_REL_JUZGADO_ESPECIALIDAD_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_REL_JUZGADO_ESPECIALIDAD;
CREATE TABLE TRIALS.TBL_REL_JUZGADO_ESPECIALIDAD
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    FN_JUZGADO      INT          NOT NULL,
    FN_ESPECIALIDAD INT          NOT NULL,
    FOREIGN KEY (FN_JUZGADO) REFERENCES TRIALS.TBL_JUZGADOS(PN_ID),
    FOREIGN KEY (FN_ESPECIALIDAD) REFERENCES TRIALS.TBL_ESPECIALIDADES(PN_ID)
);