
CREATE SEQUENCE TRIALS.SEQ_TIPO_OFICIALIAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_TIPO_OFICIALIAS_ID INCREMENT BY 1;
CREATE TABLE TRIALS.TBL_TIPO_OFICIALIAS
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(100) NOT NULL,
    S_ESTADO        CHAR(1)      NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);

INSERT INTO TRIALS.TBL_TIPO_OFICIALIAS (PN_ID, N_VERSION, S_NOMBRE, S_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_TIPO_OFICIALIAS_ID'), 0, 'Común', 'A', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');

INSERT INTO TRIALS.TBL_TIPO_OFICIALIAS (PN_ID, N_VERSION, S_NOMBRE, S_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_TIPO_OFICIALIAS_ID'), 0, 'Mayor', 'A', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');

-- si los datos actuales no son convertibles hacer esto antes del paso 1
-- se perderan los datos actuales.
TRUNCATE TABLE TRIALS.TBL_TIPO_OFICIALIAS;

-- Paso 1: Cambiar el tipo de dato de CHAR(1) a INT, asegurándote de que los datos actuales sean convertibles
ALTER TABLE TRIALS.TBL_TIPO_OFICIALIAS
    ALTER COLUMN S_ESTADO TYPE INT USING S_ESTADO::INT;

-- Paso 2: Renombrar la columna
ALTER TABLE TRIALS.TBL_TIPO_OFICIALIAS
    RENAME COLUMN S_ESTADO TO N_ESTADO;

-- Insert Nuevos

INSERT INTO TRIALS.TBL_TIPO_OFICIALIAS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_TIPO_OFICIALIAS_ID'), 0, 'Común', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');

INSERT INTO TRIALS.TBL_TIPO_OFICIALIAS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_TIPO_OFICIALIAS_ID'), 0, 'Mayor', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');
