ALTER TABLE TRIALS.TBL_PERSONA ADD COLUMN
    S_PSEUDONIMO VARCHAR(50);

ALTER TABLE TRIALS.TBL_PERSONA ADD COLUMN
    B_PERSONAL_JUZGADO BOOLEAN NOT NULL;

ALTER TABLE TRIALS.TBL_PERSONA ALTER COLUMN
    S_ESTADO TYPE INT USING S_ESTADO::INT;

ALTER TABLE TRIALS.TBL_PERSONA RENAME COLUMN
    S_ESTADO TO N_ESTADO;