CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_SALA_ID START WITH 1;
ALTER SEQUENCE TRIALS.SEQ_SALA_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_SALA;
CREATE TABLE TRIALS.TBL_SALA
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(100) NOT NULL,
    N_ESTADO        CHAR(5)      NOT NULL,
    FN_JUEZ_ID      INT          NOT NULL,
    FN_BLOQUE_ID    INT          NOT NULL,
    FN_JUZGADO_ID   INT          NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);