CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_OFICIALIAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_OFICIALIAS_ID INCREMENT BY 50;

DROP TABLE IF EXISTS TRIALS.TBL_OFICIALIAS;
CREATE TABLE TRIALS.TBL_OFICIALIAS
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_TIPO          VARCHAR(250) NOT NULL,
    S_NOMBRE        VARCHAR(20)  NOT NULL,
    FN_DOMICILIO    BIGINT       NOT NULL,
    S_RESPONSABLE   VARCHAR(50)  NOT NULL,
    S_ESTADO        CHAR(1)      NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);