ALTER TABLE TRIALS.TBL_PERSONAS ADD COLUMN
    S_PSEUDONIMO VARCHAR(50);

ALTER TABLE TRIALS.TBL_PERSONAS ALTER COLUMN
    S_ESTADO TYPE INT USING S_ESTADO::INT;

ALTER TABLE TRIALS.TBL_PERSONAS RENAME COLUMN
    S_ESTADO TO N_ESTADO;