CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_JUICIO_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_TIPO_JUICIO_ID INCREMENT BY 1 ;

DROP TABLE IF EXISTS TRIALS.TBL_TIPO_JUICIO;

CREATE TABLE TRIALS.TBL_TIPO_JUICIO
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(250) NOT NULL,
    N_ESTADO        INT          NOT NULL,
    FN_TIPO_SISTEMA INT          NOT NULL,
    FN_MATERIA      INT          NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  NOT NULL DEFAULT CURRENT_USER,

    FOREIGN KEY (FN_TIPO_SISTEMA) REFERENCES TRIALS.TBL_TIPO_SISTEMA(PN_ID),
    FOREIGN KEY (FN_MATERIA)      REFERENCES TRIALS.TBL_MATERIAS(PN_ID)
);