CREATE SEQUENCE TRIALS.SEQ_JUZGADOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_JUZGADOS_ID INCREMENT BY 50;
CREATE TABLE TRIALS.TBL_JUZGADOS
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(250) NOT NULL,
    FN_MATERIA      INT          NOT NULL,
    FN_DOMICILIO    BIGINT       NOT NULL,
    FN_DISTRITO     INT          NOT NULL,
    S_ESTADO        CHAR(1)      NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);
COMMENT
ON TABLE TRIALS.TBL_JUZGADOS IS 'Catalogo de juzgados';

CREATE SEQUENCE TRIALS.SEQ_DOMICILIOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_DOMICILIOS_ID INCREMENT BY 50;
CREATE TABLE TRIALS.TBL_DOMICILIOS
(
    PN_ID              BIGINT       NOT NULL PRIMARY KEY,
    N_VERSION          INT,
    S_CALLE            VARCHAR(250) NOT NULL,
    S_INTERIOR         VARCHAR(20),
    S_EXTERIOR         VARCHAR(20),
    S_COLONIA          VARCHAR(250),
    S_CODIGO_POSTAL    CHAR(5)      NOT NULL,
    S_MUNICIPIO        VARCHAR(250) NOT NULL,
    S_ESTADO_REPUBLICA VARCHAR(250) NOT NULL,
    S_ESTADO           CHAR(1)      NOT NULL,
    T_FECHA_ALTA       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA     VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA    VARCHAR(50)  DEFAULT CURRENT_USER
);

CREATE SEQUENCE TRIALS.SEQ_PERSONAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_PERSONAS_ID INCREMENT BY 50;
CREATE TABLE TRIALS.TBL_PERSONAS
(
    PN_ID                  BIGINT       NOT NULL PRIMARY KEY,
    N_VERSION              INT,
    S_NOMBRES              VARCHAR(50)  NOT NULL,
    S_APELLIDO_PATERNO     VARCHAR(40)  NOT NULL,
    S_APELLIDO_MATERNO     VARCHAR(40),
    S_CURP                 CHAR(18)     NOT NULL,
    S_RFC                  VARCHAR(13),
    S_SEXO                 CHAR(1)      NOT NULL,
    S_CORREO_ELECTRONICO   VARCHAR(250) NOT NULL,
    S_TELEFONO             VARCHAR(10),
    S_CELULAR              VARCHAR(10),
    T_FECHA_NACIMIENTO     DATE         NOT NULL,
    FS_ESTADO_CIVIL        VARCHAR(250),
    S_OCUPACION            VARCHAR(150),
    FS_ESCOLARIDAD         VARCHAR(100),
    S_MUNICIPIO_NACIMIENTO VARCHAR(250),
    S_ESTADO_NACIMIENTO    VARCHAR(250),
    FN_DOMICILIO           BIGINT       NOT NULL,
    S_ESTADO               CHAR(1)      NOT NULL,
    T_FECHA_ALTA           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA         VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA        VARCHAR(50)  DEFAULT CURRENT_USER
);

CREATE SEQUENCE TRIALS.SEQ_MATERIAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_MATERIAS_ID INCREMENT BY 50;
CREATE TABLE TRIALS.TBL_MATERIAS
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(100) NOT NULL,
    S_ESTADO        CHAR(1)      NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);

CREATE SEQUENCE TRIALS.SEQ_TIPO_PARTES_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_TIPO_PARTES_ID INCREMENT BY 50;
CREATE TABLE TRIALS.TBL_TIPO_PARTES
(
    PN_ID           INT         NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(50) NOT NULL,
    FN_MATERIA      INT         NOT NULL,
    S_ESTADO        CHAR(1)     NOT NULL,
    T_FECHA_ALTA    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
);

CREATE SEQUENCE TRIALS.SEQ_OFICIALIAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_OFICIALIAS_ID INCREMENT BY 50;
CREATE TABLE TRIALS.TBL_OFICIALIAS
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_TIPO          VARCHAR(250) NOT NULL,
    S_NOMBRE        VARCHAR(20)  NOT NULL,
    FN_DOMICILIO    BIGINT       NOT NULL,
    S_RESPONSABLE   VARCHAR(50)         NOT NULL,
    S_ESTADO        CHAR(1)      NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);
