CREATE SEQUENCE TRIALS.SEQ_LISTA_VALOR_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_LISTA_VALOR_ID INCREMENT BY 50;
CREATE TABLE TRIALS.TBL_LISTA_VALOR
(
    PN_ID           INT         NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(50) NOT NULL,
    S_ESTADO        CHAR(1)     NOT NULL,
    T_FECHA_ALTA    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
);