CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_JUICIO_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_TIPO_JUICIO_ID INCREMENT BY 1 ;

DROP TABLE IF EXISTS TRIALS.TBL_TIPO_JUICIO;

CREATE TABLE TRIALS.TBL_TIPO_JUICIO
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(250) NOT NULL,
    N_ESTADO        INT          NOT NULL,
    FN_TIPO_SISTEMA INT          NOT NULL,
    FN_MATERIA      INT          NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  NOT NULL DEFAULT CURRENT_USER,

    FOREIGN KEY (FN_TIPO_SISTEMA) REFERENCES TRIALS.TBL_TIPO_SISTEMA(PN_ID),
    FOREIGN KEY (FN_MATERIA)      REFERENCES TRIALS.TBL_MATERIAS(PN_ID)
);

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Laboral (Tradicional)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Tradicional' AND M.S_NOMBRE = 'LABORAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Mercantil (Tradicional)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Tradicional' AND M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Oralidad Mercantil (Oral)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Oralidad Mercantil (Oral Ejecutivo)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Oralidad Mercantil (Providencia precautoria)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Oralidad Mercantil (Medios preparatorios)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'MERCANTIL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Civil (Tradicional)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Tradicional' AND M.S_NOMBRE = 'CIVIL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Civil (Oral)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'CIVIL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Civil (Juicio de extincion de dominio)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'CIVIL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Familiar (Tradicional)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Tradicional' AND M.S_NOMBRE = 'FAMILIAR';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Familiar Oralidad', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'FAMILIAR';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Familiar Oralidad (Alimentos)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'FAMILIAR';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Familiar Oralidad (Divorcio Incausado Unilateral)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'FAMILIAR';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Familiar Oralidad  (Divoricio Incausado Bilateral)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'FAMILIAR';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Familiar Oralidad (Guardia y Custodia)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'FAMILIAR';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Familiar Oralidad (Visita y Convivencia)', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID 
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Oral' AND M.S_NOMBRE = 'FAMILIAR';
