CREATE SEQUENCE TRIALS.SEQ_ORGANISMOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_ORGANISMOS_ID INCREMENT BY 1;
CREATE TABLE TRIALS.TBL_ORGANISMOS
(
	PN_ID		INT		NOT NULL PRIMARY KEY,
	N_VERSION	INT,
	S_NOMBRE	VARCHAR(250)	NOT NULL,
	T_FECHA_ALTA	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP,
	T_FECHA_EDITA	TIMESTAMP	DEFAULT	CURRENT_TIMESTAMP,
	S_USUARIO_ALTA	VARCHAR(50)	DEFAULT CURRENT_USER,
	S_USUARIO_EDITA	VARCHAR(50)	DEFAULT CURRENT_USER,
	S_ESTADO	CHAR(1)		NOT NULL
);

INSERT INTO TRIALS.TBL_ORGANISMOS (PN_ID, N_VERSION, S_NOMBRE, T_FECHA_ALTA, T_FECHA_EDITA, S_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (nextval('TRIALS.SEQ_ORGANISMOS_ID'), 0, 'CONSEJO DE LA JUDICATURA DEL PODER JUDICIAL DEL ESTADO DE PUEBLA', current_timestamp, current_timestamp,'A', '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');

