ALTER TABLE TRIALS.TBL_JUZGADOS
    ALTER COLUMN S_ESTADO TYPE INT USING S_ESTADO::INT;

ALTER TABLE TRIALS.TBL_JUZGADOS
    RENAME COLUMN S_ESTADO TO N_ESTADO;

ALTER TABLE TRIALS.TBL_JUZGADOS DROP COLUMN FN_DOMICILIO;

ALTER TABLE TRIALS.TBL_JUZGADOS DROP COLUMN FN_DISTRITO;

ALTER TABLE TRIALS.TBL_JUZGADOS ADD COLUMN FN_SEDE INT NOT NULL;

ALTER TABLE TRIALS.TBL_JUZGADOS
ADD CONSTRAINT FK_TBL_TBL_JUZGADOS_FN_MATERIA FOREIGN KEY (FN_MATERIA)
REFERENCES TRIALS.TBL_MATERIAS(PN_ID);

ALTER TABLE TRIALS.TBL_JUZGADOS
ADD CONSTRAINT FK_TBL_TBL_JUZGADOS_FN_SEDE FOREIGN KEY (FN_SEDE)
REFERENCES TRIALS.TBL_SEDES(PN_ID);