CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_PERSONAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_PERSONAS_ID INCREMENT BY 50;

DROP TABLE IF EXISTS TRIALS.TBL_PERSONAS;
CREATE TABLE TRIALS.TBL_PERSONAS
(
    PN_ID                  BIGINT       NOT NULL PRIMARY KEY,
    N_VERSION              INT,
    S_NOMBRES              VARCHAR(50)  NOT NULL,
    S_APELLIDO_PATERNO     VARCHAR(40)  NOT NULL,
    S_APELLIDO_MATERNO     VARCHAR(40),
    S_CURP                 CHAR(18)     NOT NULL,
    S_RFC                  VARCHAR(13),
    S_SEXO                 CHAR(1)      NOT NULL,
    S_CORREO_ELECTRONICO   VARCHAR(250) NOT NULL,
    S_TELEFONO             VARCHAR(10),
    S_CELULAR              VARCHAR(10),
    T_FECHA_NACIMIENTO     DATE         NOT NULL,
    FS_ESTADO_CIVIL        VARCHAR(250),
    S_OCUPACION            VARCHAR(150),
    FS_ESCOLARIDAD         VARCHAR(100),
    S_MUNICIPIO_NACIMIENTO VARCHAR(250),
    S_ESTADO_NACIMIENTO    VARCHAR(250),
    FN_DOMICILIO           BIGINT       NOT NULL,
    S_PERSONA_FISCAL       CHAR(1),
    S_PSEUDONIMO           VARCHAR(50),
    N_ESTADO               INT          NOT NULL,
    T_FECHA_ALTA           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA         VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA        VARCHAR(50)  DEFAULT CURRENT_USER
    
);