CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_PARTES_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_TIPO_PARTES_ID INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS TRIALS.TBL_TIPO_PARTES
(
    PN_ID           INT         NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(50) NOT NULL,
    FN_TIPO_JUICIO  INT         NOT NULL,
    N_ESTADO        CHAR(1)     NOT NULL,
    T_FECHA_ALTA    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
);

ALTER TABLE TRIALS.TBL_TIPO_PARTES
ADD CONSTRAINT FK_TBL_TIPO_PARTES_FN_TIPO_JUICIO FOREIGN KEY (FN_TIPO_JUICIO)
REFERENCES TRIALS.TBL_TIPO_JUICIO(PN_ID);

