-- si los datos actuales no son convertibles hacer esto antes del paso 1
-- se perderan los datos actuales.
TRUNCATE TABLE TRIALS.TBL_TIPO_OFICIALIAS;

-- Paso 1: Cambiar el tipo de dato de CHAR(1) a INT, asegurándote de que los datos actuales sean convertibles
ALTER TABLE TRIALS.TBL_TIPO_OFICIALIAS
    ALTER COLUMN S_ESTADO TYPE INT USING S_ESTADO::INT;

-- Paso 2: Renombrar la columna
ALTER TABLE TRIALS.TBL_TIPO_OFICIALIAS
    RENAME COLUMN S_ESTADO TO N_ESTADO;

-- Insert Nuevos

INSERT INTO TRIALS.TBL_TIPO_OFICIALIAS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_TIPO_OFICIALIAS_ID'), 0, 'Común', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');

INSERT INTO TRIALS.TBL_TIPO_OFICIALIAS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_TIPO_OFICIALIAS_ID'), 0, 'Mayor', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');
