DROP SEQUENCE IF EXISTS TRIALS.SEQ_SEDES_ID;
CREATE SEQUENCE TRIALS.SEQ_SEDES_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_SEDES_ID INCREMENT BY 50;
DROP TABLE IF EXISTS TRIALS.TBL_SEDES;
CREATE TABLE TRIALS.TBL_SEDES
(
    PN_ID           INT         NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(50) NOT NULL,
    FN_DISTRITO     INT         NOT NULL,
    FN_DOMICILIO    INT         NOT NULL,
    S_TIPO          VARCHAR(10) NOT NULL,
    N_ESTADO        INT         NOT NULL,
    S_TELEFONO      VARCHAR(20),
    S_EXTENSION     VARCHAR(6),
    T_FECHA_ALTA    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    CONSTRAINT "fk_sedes_distritos" FOREIGN KEY (FN_DISTRITO) references TRIALS.TBL_DISTRITOS (PN_ID),
    CONSTRAINT "fk_sedes_domicilios" FOREIGN KEY (FN_DOMICILIO) references TRIALS.TBL_DOMICILIOS (PN_ID)
);