CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_ESPECIALIDADES_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_ESPECIALIDADES_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_ESPECIALIDADES;
CREATE TABLE TRIALS.TBL_ESPECIALIDADES
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(250) NOT NULL,
    N_ESTADO        INT          NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);

INSERT INTO TRIALS.TBL_ESPECIALIDADES (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_ESPECIALIDADES_ID'), 0, 'Juzgado Especializado en Juicios de Extinción de Dominio', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');

INSERT INTO TRIALS.TBL_ESPECIALIDADES (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_ESPECIALIDADES_ID'), 0, 'Juzgado Especializado en Oralidad Familiar', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');



CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_REL_JUZGADO_ESPECIALIDAD_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_REL_JUZGADO_ESPECIALIDAD_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_REL_JUZGADO_ESPECIALIDAD
CREATE TABLE TRIALS.TBL_REL_JUZGADO_ESPECIALIDAD
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    FN_JUZGADO      INT          NOT NULL,
    FN_ESPECIALIDAD INT          NOT NULL,
    FOREIGN KEY (FN_JUZGADO) REFERENCES TRIALS.TBL_JUZGADOS(PN_ID),
    FOREIGN KEY (FN_ESPECIALIDAD) REFERENCES TRIALS.TBL_ESPECIALIDADES(PN_ID)
);