CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_OFICIALIAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_TIPO_OFICIALIAS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_TIPO_OFICIALIAS;
CREATE TABLE TRIALS.TBL_TIPO_OFICIALIAS
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(100) NOT NULL,
    N_ESTADO        INT          NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);

INSERT INTO TRIALS.TBL_TIPO_OFICIALIAS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_TIPO_OFICIALIAS_ID'), 0, 'Común', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');

INSERT INTO TRIALS.TBL_TIPO_OFICIALIAS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (nextval('TRIALS.SEQ_TIPO_OFICIALIAS_ID'), 0, 'Mayor', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');
