CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DOMICILIOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_DOMICILIOS_ID INCREMENT BY 50;

DROP TABLE IF EXISTS TRIALS.TBL_DOMICILIOS;
CREATE TABLE TRIALS.TBL_DOMICILIOS
(
    PN_ID              BIGINT       NOT NULL PRIMARY KEY,
    
    S_CALLE            VARCHAR(250) NOT NULL,
    S_INTERIOR         VARCHAR(20),
    S_EXTERIOR         VARCHAR(20),
    S_COLONIA          VARCHAR(250),
    S_CODIGO_POSTAL    CHAR(5)      NOT NULL,
    S_MUNICIPIO        VARCHAR(250) NOT NULL,
    S_ESTADO_REPUBLICA VARCHAR(250) NOT NULL,
    S_REFERENCIA       VARCHAR(250) DEFAULT NULL,
    S_LOCALIDAD        VARCHAR(250) DEFAULT NULL,
    T_FECHA_ALTA       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA     VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA    VARCHAR(50)  DEFAULT CURRENT_USER
);