CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_JUZGADOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_JUZGADOS_ID INCREMENT BY 50;

DROP TABLE IF EXISTS TRIALS.TBL_JUZGADOS;
CREATE TABLE IF NOT EXISTS TRIALS.TBL_JUZGADOS
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    N_VERSION       INT,
    S_NOMBRE        VARCHAR(250) NOT NULL,
    FN_MATERIA      INT          NOT NULL,
    FN_SEDE         INT          NOT NULL,
    N_ESTADO        INT          NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);

ALTER TABLE TRIALS.TBL_JUZGADOS
ADD CONSTRAINT FK_TBL_TBL_JUZGADOS_FN_MATERIA FOREIGN KEY (FN_MATERIA)
REFERENCES TRIALS.TBL_MATERIAS(PN_ID);

ALTER TABLE TRIALS.TBL_JUZGADOS
ADD CONSTRAINT FK_TBL_TBL_JUZGADOS_FN_SEDE FOREIGN KEY (FN_SEDE)
REFERENCES TRIALS.TBL_SEDES(PN_ID);