ALTER TABLE TRIALS.TBL_TIPO_PARTES
    ALTER COLUMN S_ESTADO TYPE INT USING S_ESTADO::INT;

ALTER TABLE TRIALS.TBL_TIPO_PARTES
    RENAME COLUMN S_ESTADO TO N_ESTADO;

ALTER TABLE TRIALS.TBL_TIPO_PARTES
    RENAME COLUMN FN_MATERIA TO FN_TIPO_JUICIO;

ALTER TABLE TRIALS.TBL_TIPO_PARTES
ADD CONSTRAINT FK_TBL_TIPO_PARTES_FN_TIPO_JUICIO FOREIGN KEY (FN_TIPO_JUICIO)
REFERENCES TRIALS.TBL_TIPO_JUICIO(PN_ID);

ALTER TABLE TRIALS.TBL_TIPO_PARTES DROP CONSTRAINT FK_TBL_TIPO_PARTES_FN_MATERIA;