SPRING_FLYWAY_ENABLED=true
SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=https://test.pjptrials.link/kc/realms/trials-realm
KEYCLOAK_SERVERURL=https://test.pjptrials.link/kc
SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgresql-sfo3-86189-beta-do-user-17640077-0.e.db.ondigitalocean.com:25060/defaultdb?currentSchema=trials