--ALTER TABLE al campo S_ESTADO
ALTER TABLE TRIALS.TBL_OFICIALIAS
ALTER COLUMN S_ESTADO TYPE INT
USING S_ESTADO::INTEGER;

ALTER TABLE TRIALS.TBL_OFICIALIAS
ALTER COLUMN S_ESTADO SET NOT NULL;

ALTER TABLE TRIALS.TBL_OFICIALIAS
RENAME COLUMN S_ESTADO TO N_ESTADO;

--ALTER TABLE al campo S_TIPO
ALTER TABLE TRIALS.TBL_OFICIALIAS
ALTER COLUMN S_TIPO TYPE INT
USING S_TIPO::INTEGER;

ALTER TABLE TRIALS.TBL_OFICIALIAS
ALTER COLUMN S_TIPO SET NOT NULL;

ALTER TABLE TRIALS.TBL_OFICIALIAS
RENAME COLUMN S_TIPO TO FN_TIPO;

--Agregar FK_TIPO_OFICIALIA
ALTER TABLE TRIALS.TBL_OFICIALIAS
ADD CONSTRAINT FK_TBL_TBL_OFICIALIAS_FN_TIPO FOREIGN KEY (FN_TIPO)
REFERENCES TRIALS.TBL_TIPO_OFICIALIAS(PN_ID);

--Agregar columna SEDES
ALTER TABLE TRIALS.TBL_OFICIALIAS
ADD COLUMN FN_SEDE INT NOT NULL;

--Agregar FK_TIPO_OFICIALIA
ALTER TABLE TRIALS.TBL_OFICIALIAS
ADD CONSTRAINT FK_TBL_TBL_SEDES_FN_SEDE FOREIGN KEY (FN_SEDE)
REFERENCES TRIALS.TBL_SEDES(PN_ID);

ALTER TABLE TRIALS.TBL_OFICIALIAS
DROP COLUMN FN_DOMICILIO;