DROP SEQUENCE IF EXISTS TRIALS.SEQ_ANEXOS_ID;
CREATE SEQUENCE TRIALS.SEQ_ANEXOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_ANEXOS_ID INCREMENT BY 50;


DROP TABLE IF EXISTS TRIALS.TBL_ANEXOS;
CREATE TABLE TRIALS.TBL_ANEXOS
(
    PN_ID           INT         NOT NULL PRIMARY KEY,
    S_NOMBRE        VARCHAR(50) NOT NULL,
    FN_DOCUMENTO    INT         NOT NULL,
    T_FECHA_ALTA       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA     VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA    VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    CONSTRAINT "fk_documentos" FOREIGN KEY (FN_DOCUMENTO) references TRIALS.TBL_DOCUMENTOS (PN_ID)
);