CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_BLOQUE_ID START WITH 1;
ALTER SEQUENCE TRIALS.SEQ_BLOQUE_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_BLOQUE;
CREATE TABLE TRIALS.TBL_BLOQUE
(
    PN_ID           INT          NOT NULL PRIMARY KEY,
    T_HORA_INICIAL  TIME         NOT NULL,
    T_HORA_FINAL    TIME         NOT NULL,
    N_ESTADO        CHAR(5)      NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);


INSERT INTO TRIALS.TBL_BLOQUE(PN_ID, T_HORA_INICIAL, T_HORA_FINAL, N_ESTADO, T_FECHA_ALTA) 
VALUES (nextval('TRIALS.SEQ_BLOQUE_ID'), '08:30:00', '09:30:00', 'A', CURRENT_TIMESTAMP);


INSERT INTO TRIALS.TBL_BLOQUE(PN_ID, N_VERSION, T_HORA_INICIAL, T_HORA_FINAL, N_ESTADO, T_FECHA_ALTA) 
VALUES (nextval('TRIALS.SEQ_BLOQUE_ID'), '11:00:00', '12:00:00', 'A', CURRENT_TIMESTAMP);


INSERT INTO TRIALS.TBL_BLOQUE(PN_ID, N_VERSION, T_HORA_INICIAL, T_HORA_FINAL, N_ESTADO, T_FECHA_ALTA) 
VALUES (nextval('TRIALS.SEQ_BLOQUE_ID'), '08:30:00', '12:30:00', 'A', CURRENT_TIMESTAMP);