DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOCUMENTOS_ID;
CREATE SEQUENCE TRIALS.SEQ_DOCUMENTOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_DOCUMENTOS_ID INCREMENT BY 50;

DROP TABLE IF EXISTS TRIALS.TBL_DOCUMENTOS;
CREATE TABLE TRIALS.TBL_DOCUMENTOS
(
    PN_ID              INT         NOT NULL PRIMARY KEY,
    S_FOLIO            VARCHAR(15) NOT NULL,
--  ES FK
--    N_CONCEPTO         INT         NOT NULL,
    S_RUTA             VARCHAR(50) NOT NULL,
    S_ESTATUS_PROCESAL VARCHAR(50) NOT NULL,
    N_TIPO_DOCUMENTO   INT         NOT NULL,
    T_FECHA_ALTA       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA     VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA    VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    FN_JUZGADO         INT         NOT NULL,
    FN_TIPO_JUICIO     INT         NOT NULL,
    CONSTRAINT "fk_juzgados" FOREIGN KEY (FN_JUZGADO) references TRIALS.TBL_JUZGADOS (PN_ID),
    CONSTRAINT  "fk_tipo_juicio" FOREIGN KEY (FN_TIPO_JUICIO)  references TRIALS.TBL_TIPO_JUICIO(PN_ID)
);
