--ALTER TABLE al campo S_ESTADO
ALTER TABLE TRIALS.TBL_OFICIALIAS
ALTER COLUMN S_ESTADO TYPE INT
USING S_ESTADO::INTEGER;

ALTER TABLE TRIALS.TBL_OFICIALIAS
ALTER COLUMN S_ESTADO SET NOT NULL;

ALTER TABLE TRIALS.TBL_OFICIALIAS
RENAME COLUMN S_ESTADO TO N_ESTADO;

--ALTER TABLE al campo S_TIPO
ALTER TABLE TRIALS.TBL_OFICIALIAS
ALTER COLUMN S_TIPO TYPE INT
USING S_TIPO::INTEGER;

ALTER TABLE TRIALS.TBL_OFICIALIAS
ALTER COLUMN S_TIPO SET NOT NULL;

ALTER TABLE TRIALS.TBL_OFICIALIAS
RENAME COLUMN S_TIPO TO FN_TIPO;

--Agregar FK_TIPO_OFICIALIA
ALTER TABLE TRIALS.TBL_OFICIALIAS
ADD CONSTRAINT FK_TBL_TBL_OFICIALIAS_FN_TIPO FOREIGN KEY (FN_TIPO)
REFERENCES TRIALS.TBL_TIPO_OFICIALIAS(PN_ID);

--Agregar columna SEDES
ALTER TABLE TRIALS.TBL_OFICIALIAS
ADD COLUMN FN_SEDE INT NOT NULL;

--Agregar FK_TIPO_OFICIALIA
ALTER TABLE TRIALS.TBL_OFICIALIAS
ADD CONSTRAINT FK_TBL_TBL_SEDES_FN_SEDE FOREIGN KEY (FN_SEDE)
REFERENCES TRIALS.TBL_SEDES(PN_ID);

--ADD registro
INSERT INTO TRIALS.TBL_OFICIALIAS (PN_ID, N_VERSION, FN_TIPO, S_NOMBRE, FN_DOMICILIO, S_RESPONSABLE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_SEDE)
VALUES (nextval('TRIALS.SEQ_OFICIALIAS_ID'), 0, 100, 'Común en partes', 1, 'Responsable', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', 51);