
DELETE FROM TRIALS.TBL_PERSONAS;
ALTER TABLE TRIALS.TBL_PERSONAS DROP COLUMN S_PSEUDONIMO;
ALTER TABLE TRIALS.TBL_PERSONAS DROP COLUMN S_MUNICIPIO_NACIMIENTO;
ALTER TABLE TRIALS.TBL_PERSONAS DROP COLUMN S_ESTADO_NACIMIENTO;
ALTER TABLE TRIALS.TBL_PERSONAS DROP COLUMN S_PERSONA_FISCAL;

ALTER TABLE TRIALS.TBL_PERSONAS ALTER COLUMN S_SEXO TYPE INT USING S_SEXO::INT;
ALTER TABLE TRIALS.TBL_PERSONAS RENAME COLUMN S_SEXO TO N_SEXO;

ALTER TABLE TRIALS.TBL_PERSONAS ALTER COLUMN FS_ESTADO_CIVIL TYPE INT USING FS_ESTADO_CIVIL::INT;
ALTER TABLE TRIALS.TBL_PERSONAS RENAME COLUMN FS_ESTADO_CIVIL TO FN_ESTADO_CIVIL;

ALTER TABLE TRIALS.TBL_PERSONAS ALTER COLUMN FS_ESCOLARIDAD TYPE INT USING FS_ESCOLARIDAD::INT;
ALTER TABLE TRIALS.TBL_PERSONAS RENAME COLUMN FS_ESCOLARIDAD TO FN_ESCOLARIDAD;

ALTER TABLE TRIALS.TBL_PERSONAS ADD COLUMN FN_JUZGADO INT;
ALTER TABLE TRIALS.TBL_PERSONAS ADD COLUMN S_USUARIO VARCHAR(50);
