DROP SEQUENCE IF EXISTS TRIALS.SEQ_ANEXOS_ID;
CREATE SEQUENCE TRIALS.SEQ_ANEXOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_ANEXOS_ID INCREMENT BY 50;


DROP TABLE IF EXISTS TRIALS.TBL_ANEXOS;
CREATE TABLE TRIALS.TBL_ANEXOS
(
    PN_ID           INT         NOT NULL PRIMARY KEY,
    S_NOMBRE        VARCHAR(50) NOT NULL,
--  FK DE DOCUMENTOS
    FN_DOCUMENTO    INT         NOT NULL,
    CONSTRAINT "fk_documentos" FOREIGN KEY (FN_DOCUMENTO) references TRIALS.TBL_DOCUMENTOS (PN_ID)
);