

DROP TABLE IF EXISTS TRIALS.TBL_JUZGADO_TIPOJUICIO;
CREATE TABLE TRIALS.TBL_JUZGADO_TIPOJUICIO
(
    PN_ID               SERIAL       PRIMARY KEY,
    FN_JUZGADO          INT          NOT NULL,
    FN_TIPOJUICIO       INT          NOT NULL,

    FOREIGN KEY (FN_JUZGADO) REFERENCES TRIALS.TBL_JUZGADOS(PN_ID),
    FOREIGN KEY (FN_TIPOJUICIO) REFERENCES TRIALS.TBL_TIPO_JUICIO(PN_ID)
);
