DROP SEQUENCE IF EXISTS TRIALS.SEQ_PERSONAS_DOCUMENTOS_ID;
CREATE SEQUENCE TRIALS.SEQ_PERSONAS_DOCUMENTOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_PERSONAS_DOCUMENTOS_ID INCREMENT BY 50;

DROP TABLE IF EXISTS TRIALS.TBL_PERSONAS_DOCUMENTOS CASCADE;
CREATE TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
(
    PN_ID               INT         NOT NULL PRIMARY KEY,
    S_NOMBRES           VARCHAR(50) NOT NULL,
    S_APELLIDO_PATERNO  VARCHAR(40) ,
    S_APELLIDO_MATERNO  VARCHAR(40),
    S_PSEUDONIMO        VARCHAR(40),
    S_TIPO_PERSONA      VARCHAR(40),
    FN_DOCUMENTO        INT         NOT NULL,
    FN_TIPO_PARTE       INT         NOT NULL,
    T_FECHA_ALTA        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA      VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA     VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    CONSTRAINT "fk_documentos" FOREIGN KEY (FN_DOCUMENTO) references TRIALS.TBL_DOCUMENTOS (PN_ID),
    CONSTRAINT "fk_tipo_partes" FOREIGN KEY (FN_TIPO_PARTE) references TRIALS.TBL_TIPO_PARTES (PN_ID)
);