-- Secuencia para Demanda
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DEMANDA_FOLIO
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 1;


-- Secuencia para Exhorto
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_EXHORTO_FOLIO
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 1;


-- Secuencia para Promoción
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_PROMOCION_FOLIO
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 1;