CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_NOTIFICACIONES_SALAS_ID START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS TRIALS.TBL_NOTIFICACIONES_SALAS (
    PN_ID INT NOT NULL PRIMARY KEY,
    S_TOCA VARCHAR(50) NOT NULL,
    T_FECHA_TERMINO TIMESTAMP,
    S_RUTA_ARCHIVO VARCHAR(100),
    N_ESTADO INTEGER NOT NULL DEFAULT 0,
    S_CONTENIDO_CORREO TEXT NOT NULL,
    T_FECHA_ENVIO TIMESTAMP,
    FN_SALA INT NOT NULL,
    T_FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    CONSTRAINT fk_notificaciones_salas_juzgado
        FOREIGN KEY (FN_SALA) REFERENCES TRIALS.TBL_JUZGADOS (PN_ID)

);
