CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_ANEXOS_OFICIOS_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TRIALS.TBL_ANEXOS_OFICIOS (
    PN_ID INT NOT NULL PRIMARY KEY,
    S_NOMBRE_ARCHIVO VARCHAR(250) NOT NULL,
    FN_DOCUMENTO INT NOT NULL,
    N_ESTADO INT NOT NULL DEFAULT 0,
    T_FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    CONSTRAINT FK_ANEXOS_OFICIOS_DOCUMENTO
        FOREIGN KEY (FN_DOCUMENTO) REFERENCES TRIALS.TBL_DOCUMENTOS (PN_ID)
);

CREATE INDEX IF NOT EXISTS IDX_ANEXOS_OFICIOS_DOCUMENTO ON TRIALS.TBL_ANEXOS_OFICIOS (FN_DOCUMENTO);
CREATE INDEX IF NOT EXISTS IDX_ANEXOS_OFICIOS_ESTADO ON TRIALS.TBL_ANEXOS_OFICIOS (N_ESTADO);
