CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_EMAIL_LOG_ID START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS TRIALS.TBL_EMAIL_LOG (
    PN_ID INT NOT NULL PRIMARY KEY,

    -- Proveedor
    S_PROVIDER VARCHAR(30) NOT NULL,                 -- ejemplo: 'SENDPULSE'
    S_PROVIDER_MESSAGE_ID VARCHAR(80) NOT NULL,      -- id real de SendPulse (string)

    -- Contenido básico (útil para auditoría / reintentos / debug)
    S_TO_EMAIL VARCHAR(80) NOT NULL,
    S_TO_NAME VARCHAR(80),
    S_SUBJECT VARCHAR(200) NOT NULL,

    -- Estado interno (enum controlado por tu sistema)
    N_ESTADO INTEGER NOT NULL DEFAULT 0,             -- 0=PENDIENTE_ENVIO, 1=ENVIADO, 2=LEIDO, 3=NO_ENTREGADO, 4=ERROR_ENVIO(opcional)

    -- Respuesta SMTP / diagnóstico
    N_SMTP_ANSWER_CODE INTEGER,
    S_SMTP_ANSWER_SUBCODE VARCHAR(50),
    S_SMTP_ANSWER_DATA VARCHAR(2000),

    -- Fechas de eventos (si se pueden inferir/obtener)
    T_FECHA_ENVIO TIMESTAMP,
    T_FECHA_ENTREGA TIMESTAMP,
    T_FECHA_LECTURA TIMESTAMP,
    T_ULTIMA_VERIFICACION TIMESTAMP,

    -- Auditoría
    T_FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
);