CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_NOTIFICACIONES_SALAS_DESTINATARIOS_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS (
    PN_ID INT NOT NULL PRIMARY KEY,
    FN_NOTIFICACION_SALA INT NOT NULL REFERENCES TRIALS.TBL_NOTIFICACIONES_SALAS (PN_ID),
    S_NOMBRE_DESTINATARIO VARCHAR(120) NOT NULL,
    S_CORREO_ELECTRONICO VARCHAR(120) NOT NULL,
    S_TIPO_PARTE VARCHAR(100) NOT NULL,
    FN_EMAIL_LOG_ID INT REFERENCES TRIALS.TBL_EMAIL_LOG (PN_ID),
    N_ESTADO INTEGER NOT NULL DEFAULT 0,
    T_FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
);

CREATE INDEX IF NOT EXISTS IDX_NOTIF_SALA_DEST_NOTIF
    ON TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS (FN_NOTIFICACION_SALA);

CREATE INDEX IF NOT EXISTS IDX_NOTIF_SALA_DEST_CORREO
    ON TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS (LOWER(S_CORREO_ELECTRONICO));

CREATE INDEX IF NOT EXISTS IDX_NOTIF_SALA_DEST_NOMBRE
    ON TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS (LOWER(S_NOMBRE_DESTINATARIO));