CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_OFICIOS_CENTRAL_COMISARIO_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TRIALS.TBL_OFICIOS_CENTRAL_COMISARIO (
    PN_ID INT NOT NULL,
    N_VERSION INT,
    FN_DOCUMENTO INT NOT NULL,
    FN_PERSONA_ENVIA INT NOT NULL,
    FN_PERSONA_RECIBE INT,
    FN_COMISARIO INT,
    FN_PERSONA_DEVUELVE INT,
    N_ESTADO INT NOT NULL DEFAULT 0,
    T_FECHA_ENVIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_RECEPCION TIMESTAMP,
    T_FECHA_NOTIFICACION TIMESTAMP,
    T_FECHA_DEVOLUCION TIMESTAMP,
    FN_CENTRAL_COMISARIOS INT,
    T_FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    PRIMARY KEY (PN_ID),
    CONSTRAINT FK_OFICIOS_CENTRAL_COMISARIO_DOCUMENTO
        FOREIGN KEY (FN_DOCUMENTO) REFERENCES TRIALS.TBL_DOCUMENTOS (PN_ID),
    CONSTRAINT FK_OFICIOS_CENTRAL_COMISARIO_PERSONA_ENVIA
        FOREIGN KEY (FN_PERSONA_ENVIA) REFERENCES TRIALS.TBL_PERSONAS (PN_ID),
    CONSTRAINT FK_OFICIOS_CENTRAL_COMISARIO_PERSONA_RECIBE
        FOREIGN KEY (FN_PERSONA_RECIBE) REFERENCES TRIALS.TBL_PERSONAS (PN_ID),
    CONSTRAINT FK_OFICIOS_CENTRAL_COMISARIO_COMISARIO
        FOREIGN KEY (FN_COMISARIO) REFERENCES TRIALS.TBL_PERSONAS (PN_ID),
    CONSTRAINT FK_OFICIOS_CENTRAL_COMISARIO_PERSONA_DEVUELVE
        FOREIGN KEY (FN_PERSONA_DEVUELVE) REFERENCES TRIALS.TBL_PERSONAS (PN_ID),
    CONSTRAINT FK_OFICIOS_CENTRAL_COMISARIO_CENTRAL_COMISARIOS
        FOREIGN KEY (FN_CENTRAL_COMISARIOS) REFERENCES TRIALS.TBL_JUZGADOS (PN_ID)
);

CREATE INDEX IF NOT EXISTS IDX_OFICIOS_CENTRAL_COMISARIO_DOCUMENTO
    ON TRIALS.TBL_OFICIOS_CENTRAL_COMISARIO (FN_DOCUMENTO);

CREATE INDEX IF NOT EXISTS IDX_OFICIOS_CENTRAL_COMISARIO_ESTADO
    ON TRIALS.TBL_OFICIOS_CENTRAL_COMISARIO (N_ESTADO);

CREATE INDEX IF NOT EXISTS IDX_OFICIOS_CENTRAL_COMISARIO_COMISARIO
    ON TRIALS.TBL_OFICIOS_CENTRAL_COMISARIO (FN_COMISARIO);