-- AJUSTE PERMISO DE ADMINISTRADOR DE JUZGADO:  SE ELIMINA MENÚ DE REGISTRO DE OFICIOS Y LIBRO DE GOBIERNO.

UPDATE trials.tbl_menus
SET S_ROL = 'OFICIAL_MAYOR_OFICIALIA,CAPTURISTA,OFICIAL_MAYOR_JUZGADO,SECRETARIO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,ENCARGADO_SALA,JUEZ'
WHERE s_nombre = 'Registro';

UPDATE trials.tbl_menus
SET S_ROL = 'OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,SECRETARIO,PROYECTISTA,ENCARGADO_SALA,OFICIAL_MAYOR_OFICIALIA,JUEZ,COMISARIO'
WHERE PN_ID = 18;

-- AJUSTE PERMISO AUXILIAR DEL OFICIAL MAYOR DE JUZGADO:
-- SE ajusta nombre de rol ya que estaba registrado como auxiliar y no cmo auxiliar_oficial_mayor_juzgado.
-- Se agrega permiso para modulo de bandeja ya que tenia permisos para los submodulos de bandeja pero no para el modulo principal.
-- Se elimina permiso de calendario.
UPDATE trials.tbl_menus 
SET S_ROL = 'OFICIAL_MAYOR_JUZGADO,OFICIAL_MAYOR_OFICIALIA,AUXILIAR_OFICIAL_MAYOR_JUZGADO'
WHERE PN_ID = 35;

UPDATE trials.tbl_menus
SET S_ROL = 'OFICIAL_MAYOR_OFICIALIA,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO,OFICIAL_MAYOR_JUZGADO,SECRETARIO,TECNICO_JUZGADO,DILIGENCIARIO,PROYECTISTA,ENCARGADO_SALA,ADMINISTRADOR_JUZGADO,JUEZ,COMISARIO,ARCHIVO_JUDICIAL,NOTIFICADOR_SALA,AUXILIAR_OFICIAL_MAYOR_JUZGADO'
WHERE PN_ID = 4;

UPDATE trials.tbl_menus 
SET S_ROL = 'ADMINISTRADOR_JUZGADO,ADMINISTRADOR_SISTEMA'
WHERE PN_ID = 32 AND s_nombre = 'Calendarios';

