CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_NOTIFICACIONES_SALAS_DESTINATARIOS_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS (
    PN_ID INT NOT NULL PRIMARY KEY,
    FN_NOTIFICACION_SALA INT NOT NULL REFERENCES TRIALS.TBL_NOTIFICACIONES_SALAS (PN_ID),
    S_NOMBRE_DESTINATARIO VARCHAR(120) NOT NULL,
    S_CORREO_ELECTRONICO VARCHAR(120) NOT NULL,
    S_TIPO_PARTE VARCHAR(100) NOT NULL,
    FN_EMAIL_LOG_ID INT REFERENCES TRIALS.TBL_EMAIL_LOG (PN_ID),
    N_ESTADO INTEGER NOT NULL DEFAULT 0,
    T_FECHA_ALTA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
);

CREATE INDEX IF NOT EXISTS IDX_NOTIF_SALA_DEST_NOTIF
    ON TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS (FN_NOTIFICACION_SALA);

CREATE INDEX IF NOT EXISTS IDX_NOTIF_SALA_DEST_CORREO
    ON TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS (LOWER(S_CORREO_ELECTRONICO));

CREATE INDEX IF NOT EXISTS IDX_NOTIF_SALA_DEST_NOMBRE
    ON TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS (LOWER(S_NOMBRE_DESTINATARIO));

ALTER TABLE TRIALS.TBL_NOTIFICACIONES_SALAS
    ADD COLUMN IF NOT EXISTS S_NOMBRE_SALA VARCHAR(120);

INSERT INTO TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS (
    PN_ID,
    FN_NOTIFICACION_SALA,
    S_NOMBRE_DESTINATARIO,
    S_CORREO_ELECTRONICO,
    S_TIPO_PARTE,
    FN_EMAIL_LOG_ID,
    N_ESTADO,
    T_FECHA_ALTA,
    T_FECHA_EDITA,
    S_USUARIO_ALTA,
    S_USUARIO_EDITA
)
SELECT
    nextval('TRIALS.SEQ_NOTIFICACIONES_SALAS_DESTINATARIOS_ID'),
    ns.PN_ID,
    COALESCE(ns.S_NOMBRE_DESTINATARIO, 'DESTINATARIO'),
    COALESCE(ns.S_CORREO_DESTINATARIO, 'sin-correo@invalid.local'),
    'NO_ESPECIFICADO',
    ns.FN_EMAIL_LOG_ID,
    ns.N_ESTADO,
    COALESCE(ns.T_FECHA_ALTA, CURRENT_TIMESTAMP),
    COALESCE(ns.T_FECHA_EDITA, CURRENT_TIMESTAMP),
    COALESCE(ns.S_USUARIO_ALTA, CURRENT_USER),
    COALESCE(ns.S_USUARIO_EDITA, CURRENT_USER)
FROM TRIALS.TBL_NOTIFICACIONES_SALAS ns
WHERE ns.S_NOMBRE_DESTINATARIO IS NOT NULL
  AND ns.S_CORREO_DESTINATARIO IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM TRIALS.TBL_NOTIFICACIONES_SALAS_DESTINATARIOS d
      WHERE d.FN_NOTIFICACION_SALA = ns.PN_ID
  );

DO $$
DECLARE
    constraint_name TEXT;
BEGIN
    FOR constraint_name IN
        SELECT c.conname
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY (c.conkey)
        WHERE n.nspname = 'trials'
          AND t.relname = 'tbl_notificaciones_salas'
          AND a.attname = 'fn_email_log_id'
    LOOP
        EXECUTE format('ALTER TABLE TRIALS.TBL_NOTIFICACIONES_SALAS DROP CONSTRAINT IF EXISTS %I', constraint_name);
    END LOOP;
END $$;

ALTER TABLE TRIALS.TBL_NOTIFICACIONES_SALAS DROP COLUMN IF EXISTS S_NOMBRE_DESTINATARIO;
ALTER TABLE TRIALS.TBL_NOTIFICACIONES_SALAS DROP COLUMN IF EXISTS S_CORREO_DESTINATARIO;
ALTER TABLE TRIALS.TBL_NOTIFICACIONES_SALAS DROP COLUMN IF EXISTS FN_EMAIL_LOG_ID;
