ALTER SEQUENCE TRIALS.SEQ_JUZGADOS_ID INCREMENT BY 1;

-- insertamos distrito si no existe:
INSERT INTO TRIALS.TBL_DISTRITOS (PN_ID, N_VERSION, S_NOMBRE, S_REGION, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_DISTRITOS_ID'), 0, 'PUEBLA', 'Centro', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7'
WHERE NOT EXISTS (SELECT 1 FROM TRIALS.TBL_DISTRITOS WHERE S_NOMBRE = 'PUEBLA');

-- insertamos domicilio si no existe:
INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_ESTADO_REPUBLICA, S_EXTERIOR, S_LOCALIDAD, S_MUNICIPIO, S_USUARIO_ALTA, S_USUARIO_EDITA, T_FECHA_ALTA, T_FECHA_EDITA)
SELECT nextval('TRIALS.SEQ_DOMICILIOS_ID'), '11 sur', 'PUEBLA', '11921', 'PUEBLA', 'PUEBLA',
       '6B13785F-D213-4585-A76B-437FFE57C9C7', '6B13785F-D213-4585-A76B-437FFE57C9C7',
       '2024-10-03 17:11:34.371602', '2024-10-03 18:41:39.539895'
WHERE NOT EXISTS (
    SELECT 1
    FROM TRIALS.TBL_DOMICILIOS
    WHERE S_CALLE = '11 sur'
      AND S_ESTADO_REPUBLICA = 'PUEBLA'
      AND S_EXTERIOR = '11921'
      AND S_LOCALIDAD = 'PUEBLA'
      AND S_MUNICIPIO = 'PUEBLA'
);

-- insertamos sede si no existe:
INSERT INTO TRIALS.TBL_SEDES (
    PN_ID, FN_DISTRITO, FN_DOMICILIO, N_ESTADO, N_VERSION,
    S_NOMBRE, S_TELEFONO, S_TIPO, S_USUARIO_ALTA, S_USUARIO_EDITA,
    T_FECHA_ALTA, T_FECHA_EDITA
)
SELECT
    nextval('TRIALS.SEQ_SEDES_ID'),
    (SELECT PN_ID FROM TRIALS.TBL_DISTRITOS WHERE S_NOMBRE = 'PUEBLA'),
    (SELECT PN_ID FROM TRIALS.TBL_DOMICILIOS
        WHERE S_CALLE = '11 sur'
        AND S_ESTADO_REPUBLICA = 'PUEBLA'
        AND S_EXTERIOR = '11921'
        AND S_LOCALIDAD = 'PUEBLA'
        AND S_MUNICIPIO = 'PUEBLA'),
    0,0,
    'Centro de Justicia Penal de Puebla',
    '2222238400',
    'INTERNO',
    '6B13785F-D213-4585-A76B-437FFE57C9C7',
    '6B13785F-D213-4585-A76B-437FFE57C9C7',
    '2024-10-03 17:11:34.457937',
    '2024-10-03 18:41:39.540059'
WHERE NOT EXISTS (
    SELECT 1
    FROM TRIALS.TBL_SEDES
    WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'
);

-- insertamos materia si no existe:
INSERT INTO TRIALS.TBL_MATERIAS (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
SELECT nextval('TRIALS.SEQ_MATERIAS_ID'), 0, 'PENAL', 0,
       '6b13785f-d213-4585-a76b-437ffe57c9c7',
       '6b13785f-d213-4585-a76b-437ffe57c9c7'
WHERE NOT EXISTS (
    SELECT 1 FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'
);


-- INSERT JUZGADOS IDEMPOTENTES


INSERT INTO TRIALS.TBL_JUZGADOS(
    PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE,
    N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES,
    N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME
)
SELECT
    nextval('TRIALS.SEQ_JUZGADOS_ID'),
    0,
    'Cuarta Sala Colegiada en Materia Penal',
    (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'),
    (SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
    0,0,0,1,
    NULL,
    'Cuarta sala'
WHERE NOT EXISTS (
    SELECT 1 FROM TRIALS.TBL_JUZGADOS
    WHERE S_NOMBRE = 'Cuarta Sala Colegiada en Materia Penal'
);


INSERT INTO TRIALS.TBL_JUZGADOS(
    PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE,
    N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES,
    N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME
)
SELECT
    nextval('TRIALS.SEQ_JUZGADOS_ID'),
    0,
    'Cuarto Tribunal de Alzada Colegiado de lo Penal',
    (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'),
    (SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
    0,0,0,1,
    (SELECT PN_ID FROM TRIALS.TBL_JUZGADOS WHERE S_NOMBRE = 'Cuarta Sala Colegiada en Materia Penal'),
    'Cuarto Tribunal de Alzada'
WHERE NOT EXISTS (
    SELECT 1 FROM TRIALS.TBL_JUZGADOS
    WHERE S_NOMBRE = 'Cuarto Tribunal de Alzada Colegiado de lo Penal'
);


INSERT INTO TRIALS.TBL_JUZGADOS(
    PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE,
    N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES,
    N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME
)
SELECT
    nextval('TRIALS.SEQ_JUZGADOS_ID'),
    0,
    'Decima Primera Sala Unitaria de lo Penal',
    (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'),
    (SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
    0,0,0,1,
    (SELECT PN_ID FROM TRIALS.TBL_JUZGADOS WHERE S_NOMBRE = 'Cuarta Sala Colegiada en Materia Penal'),
    'Decima Primera Sala'
WHERE NOT EXISTS (
    SELECT 1 FROM TRIALS.TBL_JUZGADOS
    WHERE S_NOMBRE = 'Decima Primera Sala Unitaria de lo Penal'
);


INSERT INTO TRIALS.TBL_JUZGADOS(
    PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE,
    N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES,
    N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME
)
SELECT
    nextval('TRIALS.SEQ_JUZGADOS_ID'),
    0,
    'Decima Segunda Sala Unitaria de lo Penal',
    (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'),
    (SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
    0,0,0,1,
    (SELECT PN_ID FROM TRIALS.TBL_JUZGADOS WHERE S_NOMBRE = 'Cuarta Sala Colegiada en Materia Penal'),
    'Decima Segunda Sala'
WHERE NOT EXISTS (
    SELECT 1 FROM TRIALS.TBL_JUZGADOS
    WHERE S_NOMBRE = 'Decima Segunda Sala Unitaria de lo Penal'
);


INSERT INTO TRIALS.TBL_JUZGADOS(
    PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE,
    N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES,
    N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME
)
SELECT
    nextval('TRIALS.SEQ_JUZGADOS_ID'),
    0,
    'Decima Tercera Sala Unitaria de lo Penal',
    (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'),
    (SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
    0,0,0,1,
    (SELECT PN_ID FROM TRIALS.TBL_JUZGADOS WHERE S_NOMBRE = 'Cuarta Sala Colegiada en Materia Penal'),
    'Decima Tercera Sala'
WHERE NOT EXISTS (
    SELECT 1 FROM TRIALS.TBL_JUZGADOS
    WHERE S_NOMBRE = 'Decima Tercera Sala Unitaria de lo Penal'
);