INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Carpetas', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Penal';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Carpetas', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Causas Penales con Detenido';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Carpetas', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Causas Penales sin Detenido';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Carpetas', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Causas Penales por Orden De Aprehensión';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Carpetas', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Expedientillo de Control Judicial';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Carpetas', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Expedientillo de Control De Actos De Investigación';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Carpetas', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Expedientillo De Exhorto';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Carpetas', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Carpetas De Ejecución';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Carpetas', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Carpetas De Juicio';
