ALTER TABLE TRIALS.TBL_CARPETA_DETALLE
    ADD COLUMN IF NOT EXISTS S_ULTIMO_DOMICILIO_FAMILIAR VARCHAR(300),
    ADD COLUMN IF NOT EXISTS S_DOMICILIO_ACREEDOR VARCHAR(300),
    ADD COLUMN IF NOT EXISTS S_DOMICILIO_FAMILIAR VARCHAR(300),
    ADD COLUMN IF NOT EXISTS S_DOMICILIO_DEMANDADO VARCHAR(300),
    ADD COLUMN IF NOT EXISTS S_DOMICILIO_MENOR_EDAD VARCHAR(300);
