ALTER TABLE TRIALS.TBL_EMAIL_LOGS
    ADD COLUMN IF NOT EXISTS S_SMTP_ANSWER_CODE_EXPLAIN VARCHAR(200),
    ADD COLUMN IF NOT EXISTS S_ERROR_ENVIO_DETALLE VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS T_FECHA_DESCARGA_VINCULO TIMESTAMP,
    ADD COLUMN IF NOT EXISTS J_TRACKING_LINK_DETALLE JSONB;

CREATE INDEX IF NOT EXISTS IDX_EMAIL_LOG_ESTADO_PROXIMA_ID
    ON TRIALS.TBL_EMAIL_LOGS (S_ESTADO, T_PROXIMA_VERIFICACION, PN_ID);

CREATE INDEX IF NOT EXISTS IDX_EMAIL_LOG_PROVIDER_MSG_ID
    ON TRIALS.TBL_EMAIL_LOGS (S_PROVIDER_MESSAGE_ID);
