ALTER SEQUENCE TRIALS.SEQ_JUZGADOS_ID INCREMENT BY 1;

INSERT INTO TRIALS.TBL_JUZGADOS(PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE, N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES, N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME)
VALUES(nextval('TRIALS.SEQ_JUZGADOS_ID'),
0, 'Cuarta Sala Colegiada en Materia Penal', 
(SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), 
(SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
0, 0, 0, 1, null, 'Cuarta sala');

INSERT INTO TRIALS.TBL_JUZGADOS(PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE, N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES, N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME)
VALUES(nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'Cuarto Tribunal de Alzada Colegiado de lo Penal', 
(SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), 
(SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
0, 0, 0, 1,
(SELECT PN_ID FROM TRIALS.TBL_JUZGADOS WHERE S_NOMBRE = 'Cuarta Sala Colegiada en Materia Penal'),
'Cuarto Tribunal de Alzada');

INSERT INTO TRIALS.TBL_JUZGADOS(PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE, N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES, N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME)
VALUES(nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'Decima Primera Sala Unitaria de lo Penal', 
(SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), 
(SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
0, 0, 0, 1, 
(SELECT PN_ID FROM TRIALS.TBL_JUZGADOS WHERE S_NOMBRE = 'Cuarta Sala Colegiada en Materia Penal'),
'Decima Primera Sala');

INSERT INTO TRIALS.TBL_JUZGADOS(PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE, N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES, N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME)
VALUES(nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'Decima Segunda Sala Unitaria de lo Penal', 
(SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), 
(SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
0, 0, 0, 1, 
(SELECT PN_ID FROM TRIALS.TBL_JUZGADOS WHERE S_NOMBRE = 'Cuarta Sala Colegiada en Materia Penal'),
'Decima Segunda Sala');

INSERT INTO TRIALS.TBL_JUZGADOS(PN_ID, N_VERSION, S_NOMBRE, FN_MATERIA, FN_SEDE, N_ESTADO, N_CONTADOR_ASIGNACIONES, N_MAX_ASIGNACIONES, N_INSTANCIA, FN_JUZGADO_PADRE, S_SHORT_NAME)
VALUES(nextval('TRIALS.SEQ_JUZGADOS_ID'), 0, 'Decima Tercera Sala Unitaria de lo Penal', 
(SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), 
(SELECT PN_ID FROM TRIALS.TBL_SEDES WHERE TRIM(S_NOMBRE) = 'Centro de Justicia Penal de Puebla'),
0, 0, 0, 1, 
(SELECT PN_ID FROM TRIALS.TBL_JUZGADOS WHERE S_NOMBRE = 'Cuarta Sala Colegiada en Materia Penal'),
'Decima Tercera Sala');
