ALTER TABLE TRIALS.TBL_DOCUMENTOS ADD COLUMN N_ESTADO INT;

DROP TABLE IF EXISTS TRIALS.TBL_MOVIMIENTOS;
CREATE TABLE TRIALS.TBL_MOVIMIENTOS
(
    PN_ID                INT         NOT NULL PRIMARY KEY,
    FN_CARPETA           INT,
    FN_DOCUMENTO         INT,
    T_FECHA_ASIGNACION   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FN_PERSONA           INT         NOT  NULL,
    S_MOTIVO             VARCHAR(150),
    FN_OFICIALIA         INT,
    FN_JUZGADO           INT,
    N_TIPO               INT,
    S_UUID               uuid,
    FOREIGN KEY (FN_CARPETA) references TRIALS.TBL_CARPETAS (PN_ID),
    FOREIGN KEY (FN_DOCUMENTO) references TRIALS.TBL_DOCUMENTOS (PN_ID),
    FOREIGN KEY (FN_PERSONA) references TRIALS.TBL_PERSONAS (PN_ID),
    FOREIGN KEY (FN_OFICIALIA) references TRIALS.TBL_OFICIALIAS (PN_ID),
    FOREIGN KEY (FN_JUZGADO) references TRIALS.TBL_JUZGADOS (PN_ID)
);

CREATE INDEX IDX_MOVIMIENTO_CARPETA1 ON TRIALS.TBL_MOVIMIENTOS (FN_CARPETA);
CREATE INDEX IDX_MOVIMIENTO_DOCUMENTO2 ON TRIALS.TBL_MOVIMIENTOS (FN_DOCUMENTO);
CREATE INDEX IDX_MOVIMIENTO_PERSONA3 ON TRIALS.TBL_MOVIMIENTOS (FN_PERSONA);
CREATE INDEX IDX_MOVIMIENTO_OFICIALIA4 ON TRIALS.TBL_MOVIMIENTOS (FN_OFICIALIA);
CREATE INDEX IDX_MOVIMIENTO_JUZGADO5 ON TRIALS.TBL_MOVIMIENTOS (FN_JUZGADO);