ALTER TABLE TRIALS.TBL_DOCUMENTOS
ADD FN_INSTITUCION INT NULL,
ADD CONSTRAINT fk_fn_instituciones
FOREIGN KEY (FN_INSTITUCION) REFERENCES TRIALS.TBL_INSTITUCIONES (PN_ID);

ALTER TABLE TRIALS.TBL_DOCUMENTOS
ALTER COLUMN FN_CARPETA DROP NOT NULL;

ALTER TABLE TRIALS.TBL_DOCUMENTOS
ALTER COLUMN T_FECHA_ASIGNACION DROP NOT NULL;