ALTER TABLE TRIALS.TBL_DOCUMENTOS
ADD FN_CONCEPTO INT NULL;

ALTER TABLE TRIALS.TBL_DOCUMENTOS
ADD CONSTRAINT fk_concepto FOREIGN KEY (FN_CONCEPTO) REFERENCES TRIALS.TBL_CONCEPTOS (PN_ID);

CREATE INDEX IDX_FN_CONCEPTO ON TRIALS.TBL_DOCUMENTOS (FN_CONCEPTO);


