DROP SEQUENCE IF EXISTS TRIALS.SEQ_MOVIMIENTOS_ID;
CREATE SEQUENCE TRIALS.SEQ_MOVIMIENTOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_MOVIMIENTOS_ID INCREMENT BY 50;


DROP TABLE IF EXISTS TRIALS.TBL_MOVIMIENTOS;
CREATE TABLE TRIALS.TBL_MOVIMIENTOS
(
    PN_ID                INT         NOT NULL PRIMARY KEY,
    FN_CARPETA           INT         NOT NULL,
    FN_DOCUMENTO         INT         NOT NULL,
    T_FECHA_ASIGNACION   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FN_PERSONA           INT         NOT  NULL,
    S_MOTIVO             VARCHAR(150),
    FN_OFICIALIA         INT         NOT NULL,
    FN_JUZGADO           INT         NOT NULL,
    N_TIPO               INT         NOT NULL,
    S_UUID               uuid        NOT NULL,
    CONSTRAINT "fk_carpetas" FOREIGN KEY (FN_CARPETA) references TRIALS.TBL_CARPETAS (PN_ID),
    CONSTRAINT "fk_documentos" FOREIGN KEY (FN_DOCUMENTO) references TRIALS.TBL_DOCUMENTOS (PN_ID),
    CONSTRAINT "fk_personas" FOREIGN KEY (FN_PERSONA) references TRIALS.TBL_DOCUMENTOS (PN_ID),
    CONSTRAINT "fk_oficialias" FOREIGN KEY (FN_OFICIALIA) references TRIALS.TBL_OFICIALIAS (PN_ID),
    CONSTRAINT "fk_juzgados" FOREIGN KEY (FN_JUZGADO) references TRIALS.TBL_JUZGADOS (PN_ID)
);