-- Laboral (Tradicional)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Expediente', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Laboral (Tradicional)';

-- Familiar (Tradicional)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Expediente', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar (Tradicional)';

-- Mercantil (Tradicional)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Expediente', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

-- Oralidad Mercantil (Oral)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Carpeta Digital', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

-- Oralidad Mercantil (Oral Ejecutivo)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Carpeta Digital', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral Ejecutivo)';

-- Oralidad Mercantil (Providencia precautoria)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Carpeta Digital', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Providencia precautoria)';

-- Oralidad Mercantil (Medios preparatorios)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Carpeta Digital', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Medios preparatorios)';

-- Civil (Tradicional)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Expediente', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Tradicional)';

-- Civil (Juicio de extincion de dominio)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Expediente', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Juicio de extincion de dominio)';

-- Civil (Oral)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Carpeta Digital', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

-- Familiar Oralidad
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Carpeta Digital', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

-- Familiar Oralidad (Alimentos)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Carpeta Digital', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

-- Familiar Oralidad (Divorcio Incausado Unilateral)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Carpeta Digital', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

-- Familiar Oralidad  (Divoricio Incausado Bilateral)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nuevoNombre', 'Carpeta Digital', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

-- Familiar Oralidad (Guardia y Custodia)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioNino', 'Domicilio del niño, niña o adolescente', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

-- Familiar Oralidad (Visita y Convivencia)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioNino', 'Domicilio del niño, niña o adolescente', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

