ALTER TABLE TRIALS.TBL_CARPETAS
ADD COLUMN FN_PERSONA INT,
ADD COLUMN T_FECHA_ASIGNACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD FOREIGN KEY (FN_PERSONA) REFERENCES TRIALS.TBL_PERSONAS (PN_ID)
ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE TRIALS.TBL_DOCUMENTOS
ADD COLUMN FN_PERSONA INT,
ADD COLUMN T_FECHA_ASIGNACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD FOREIGN KEY (FN_PERSONA) REFERENCES TRIALS.TBL_PERSONAS (PN_ID)
ON UPDATE CASCADE ON DELETE CASCADE;