DROP SEQUENCE IF EXISTS TRIALS.SEQ_ACUERDO_RUBROS_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_ACUERDO_RUBROS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_ACUERDO_RUBROS_ID INCREMENT BY 1;


DROP TABLE IF EXISTS TRIALS.TBL_ACUERDO_RUBROS;
CREATE TABLE TRIALS.TBL_ACUERDO_RUBROS
(
   PN_ID                INT          NOT NULL PRIMARY KEY,
   S_NOMBRE             VARCHAR(80),
   FN_MATERIA           INT          NOT NULL REFERENCES TRIALS.TBL_MATERIAS (PN_ID),
   FN_TIPO_SISTEMA      INT          NULL REFERENCES TRIALS.TBL_TIPO_SISTEMA (PN_ID)
);
CREATE INDEX IF NOT EXISTS IDX_TIPO_SISTEMA_ACUERDO_RUBROS ON TRIALS.TBL_ACUERDO_RUBROS (FN_TIPO_SISTEMA);
CREATE INDEX IF NOT EXISTS IDX_MATERIA_ACUERDO_RUBROS ON TRIALS.TBL_ACUERDO_RUBROS (FN_MATERIA);


INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACEPTACION DE CARGO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACEPTACION AL CARGO DE PERITO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACLARACION DE SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACUERDO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACUERDO 1 DIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACUERDO EXTENSION SOLICITUD POR CORREO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AGREGAR', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AMPARO DIRECTO 15', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AMPARO DIRECTO 5', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'APELACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ARCHIVO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIECIA DE CONTINUACION DE JUICIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'COMPARECENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONCILIACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'COPIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CORRECCION DEL ACUERDO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DEVOLUCION DE DOCUMENTOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DILIGENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'INFORME PREVIO DE AMPARO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'INFORME JUSTIFICADO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'INFORMACIONES TESTIMONIALES', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'FIRMA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NOTIFICACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA RECLAMACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PROCEDIMIENTO NO CONTENSIOSO SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'OFRECIMIENTO DE PAGO SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'OFICIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'OFICIO APELACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RATIFICACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REVISAR', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'TOMA DE FOTOGRAFIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'LISTA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DOMICILIARIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'LIQUIDACION DE SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REVISION DE SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SALIDA REVISION SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA COLEGIADO 8 DIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA COLEGIADO 5 DIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA DEFINITIVA DUPLICADA POR LICENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA DEFINITIVA TRIPLICADA POR LICENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'INCIDENTES CON PRUEBAS (SENTENCIA 6M DUPLICADO)', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NOTIFICACION PERSONAL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PUBLICAR EDICTO NOTIFICACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DILIGENCIA NOTIFICACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REQUERIMIENTO NOTIFICACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'GESTIÓN COPIAS AUTORIZADAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RECTIFICACION DE ESCRITO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'GESTION DE OFICIOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'LISTA NOTIFICACION 1 DIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RENDIR INFORME JUSTIFICADO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PUBLICAR EDICTOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DEVOLUCION NOTIFICADO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'COMPARECENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'GESTION DE COPIAS OFICIOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DEVOLUCION DE DOCUMENTOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'TRAMITE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PROYECTO DE SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA INTERLOCUTORIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA TERMINO DUPLICADO SOLICITADO POR EL JUZGADO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'OTROS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));

-- TERMINOS DE ACUERDO MATERIA ORALIDAD FAMILIAR
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACUERDO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ARCHIVO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA AVENENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA DE CONCILIACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA CONTESTACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA COMPARECENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA ESPECIAL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA DESAHOGO DE PRUEBAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CITACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DEVOLUCION DE DOCUMENTOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DIGITALIZACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ELABORACION DE CITATORIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ELABORACION DE EXHORTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ELABORACION DE OFICIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EMPLAZAMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ENTREGA DE COPIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ENTREGA DE DISCO DVD', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ENTREGA DE OFICIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'GESTION DE AMPARO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NOTIFICACION DOMICILIARIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NOTIFICACION MINISTERIO PUBLICO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NOTIFICACION POR LISTA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA DEFINITIVA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA INTERLOCUTORIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));

-- TERMINOS DE ACUERDO MATERIA MERCANTIL
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACEPTACION DE CARGO DEPOSITARIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACEPTACION Y PROTESTA DE CARGO PERITO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACLARACION DE PETICION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACLARACION DE PRUEBAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACLARACION DE SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADJUDICACION DIRECTA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADJUDICACION POR REMATE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE DEMANDA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE GASTOS Y COSTAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE INCIDENTE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE LIQUIDACION DE SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE PERITAJE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE PRUEBAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE PROVIDENCIA PRECAUTORIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE RECURSO DE APELACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE TERCERIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AGREGAR DICTAMEN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AMPARO DIRECTO 5 DIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AMPARO DIRECTO 8 DIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'APROBACION DE HONORARIOS DE PERITO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA INCIDENTAL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA DE MEDIOS PREPARATORIOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO DE DILIGENCIADO EXHORTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO DE NO DILIGENCIADO EXHORTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO QUE ADMITE INCIDENTE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO QUE ADMITE RECURSO DE REVOCACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO QUE AUTORIZA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO QUE CONTESTA RECURSO DE REVOCACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO QUE DECLARA EJECUTORIADA LA SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO QUE FIJA FIANZA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO QUE RATIFICA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO QUE TURNA PARA RESOLVER RESOLUCION DE COMPUTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTO RESERVA DE ESCRITO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CERTIFICACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'COMPARECENCIA DE PERITO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'COMPUTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONCLUIDO JUICIO POR DESISTIMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONTESTACION DE APELACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONTESTACION DE DEMANDA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONTESTACION TERCERIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONTESTACION DE VISTA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'COPIAS CERTIFICADAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'COPIAS POR COMPARECENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'COPIAS SIMPLES', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CUMPLIMIENTO DE REQUERIMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DAR VISTA CON CONTESTACION DE DEMANDA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DAR VISTA CON MANIFESTACIONES', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DECRETAR CADUCIDAD', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DECRETAR REMATE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESAHOGO DE PRUEBAS (1 DIA)', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESECHAMIENTO DE DEMANDA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESECHAMIENTO DE PETICION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESECHAMIENTO DE PROVIDENCIA PRECAUTORIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESIGNACION DE APODERADO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESIGNACIÓN DE ENDOSATARIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESIGNACION DE PERITO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESISTIMIENTO DE ACCION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESISTIMIENTO DE EMBARGO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESISTIMIENTO DE INSTANCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DEVOLUCION DE DOCUMENTOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DEVOLUCION DE EXPEDIENTE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DOCUMENTAR SENTENCIA EN ORALIDAD', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EMPLAZAMIENTO POR EDICTOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EXHIBICION DE ACUSES', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EXHIBICION DE BOLETA DE INSCRIPCION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EXHIBICIÓN DE CERTIFICADO DE GRAVAMEN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EXHIBICION DE CESION DE DERECHOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EXHIBICION DE FIANZA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EXHIBICION DE FICHA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EXHIBICION DE PAGO DE HONORARIOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'GESTION DE COPIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'GESTION DE OFICIOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'GIRAR OFICIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'INFORME SIARA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'JUNTA DE PERITOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'LIQUIDACION DE SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'LLEGA EXHORTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NO ES PARTE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NOMBRAMIENTO DE PERITO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NOMBRAMIENTO DE PERITO TERCERO EN DISCORDIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NOTARIO DEVUELVE EXPEDIENTE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'OBJECION DE DICTAMEN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'OFICIO AL REGISTRO PUBLICO DE LA PROPIEDAD Y DEL COMERCIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PERDIDO DERECHO PARA CONTESTAR DEMANDA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PETICION ACORDADA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RATIFICACION CONVENIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REASIGNACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REANUDACION DE PROCEDIMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REMISION A NOTARIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RENUNCIA ABOGADO AUTORIZADO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REQUERIMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RESOLUCIÓN INCIDENTAL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REVOCACION DE DEPOSITARIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SE ADMITE AVALUO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SE ADMITE DICTAMEN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SE APERCIBE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SE APERSONA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SE HACE EFECTIVO APERCIBIMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SE ORENA EMPLAZAMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA EJECUTIVO MERCANTIL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA ORDINARIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SEÑALAR CORREO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SEÑALAR DIA Y HORA PARA AUDIENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SEÑALAR DOMICILIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SOLICITAR EXPEDIENTE', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SUSPENSION DEL PROCEDIMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SUSTITUCION DE TESTIGO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'TURNAR PARA RESOLVER LIQUIDACION DE SENTENCIA DILIGENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'VISTOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'OTROS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);

-- TERMINOS DE ACUERDO MATERIA CIVIL (PENDIENTE CON LA SECRETARIA)
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACEPTACIÓN AL CARGO DE PERITO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL);

-- TERMINOS DE ACUERDO MATERIA LABORAL
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACUERDO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA ASUNTOS COLECTIVOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ADMISION DE DEMANDA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA ESPECIAL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA DE JUICIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AMPARO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA PARA DESAHOGO DE PRUEBA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUDIENCIA PRELIMINAR', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CERTIFICACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'COPIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DESISTIMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DEVOLUCION DE DOCUMENTOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'DILIGENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EJECUCION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ELABORACION DE OFICIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'FIRMA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'NOTIFICACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SENTENCIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);

-- TERMINOS DE ACUERDO MATERIA PENAL
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACCIÓN PENAL POR PARTICULAR', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ACUMULACION DE CAUSAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AMPARO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AMPARO INDIRECTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'APELACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUTORIZACION DE CUENTAS BANCARIAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'AUXILIO JUDICIAL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CALIFICATIVA DE TRASLADO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CATEO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONTROL DE DETENCION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONTROL JUDICIAL DE ACUERDO REPARATORIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONTROL JUDICIAL DE INVESTIGACIÓN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CONTROL JUDICIAL PREVIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'CUMPLIMIENTO DE AMPARO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EXHIBICIÓN DE GARANTÍA ECONÓMICA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'EXHUMACIÓN DE CADÁVERES', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'FORMULACION DE IMPUTACION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'INFORME JUSTIFICADO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'INFORME PREVIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'INHIBITORIA O DECLINATORIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'INTERMEDIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'MEDIDAS CAUTELARES', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'ORDEN DE APREHENSION', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PROCEDENCIA DE ACCIÓN PENAL POR PARTICULAR', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PROCEDIMIENTO ABREVIADO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PROCEDIMIENTO DE EJECUCIÓN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PRÓRROGA DE PLAZO DE CIERRE DE LA INVESTIGACIÓN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'PRUEBA ANTICIPADA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'QUEJA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RADICACION DE ACUERDO POR CONTROL DE DETENCIÓN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RADICACIÓN DE ACUERDO POR FORMULACIÓN DE IMPUTACIÓN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RADICACION DE EJECUCIÓN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RADICACION DE JUICIO ORAL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RADICACIÓN POR SOLICITUD DE ORDEN DE APREHENSIÓN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RATIFICACIÓN DE PERDÓN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REANUDACIÓN POR PROCEDIMIENTO (POR CUMPLIMIENTO DE ORDEN DE APREHENSION)', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RECONOCIMIENTO O EXAMEN FÍSICO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REDUCCIÓN DE SANCIÓN PRIVATIVA DE LIBERTAD', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'RENUNCIA DE PLAZO CONSTITUCIONAL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REPOSICIÓN DE PLAZO CONSTITUCIONAL', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REVISIÓN DE CONDICIONES', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REVISIÓN DE MEDIDAS CAUTELARES', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'REVOCACIÓN', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SANEAMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SOLICITUD DE CONTROL JUDICIAL PREVIO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SOLICITUD PARA DILIGENCIAR EXHORTOS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'),NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SOBRESEIMIENTO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SUSPENSIÓN CONDICIONAL DEL PROCESO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SUSPENSIÓN DE PROCESO', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'SUSTRACCIÓN DE LA JUSTICIA', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'TOMA DE MUESTRAS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
INSERT INTO TRIALS.TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (nextval('TRIALS.SEQ_ACUERDO_RUBROS_ID'), 'OTROS', (SELECT PN_ID FROM TRIALS.TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);
