DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID;

CREATE SEQUENCE TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID START WITH 10;
ALTER SEQUENCE TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID INCREMENT BY 10;

DROP TABLE IF EXISTS TRIALS.TBL_DOCUMENTOS_IDENTIFICACION;

CREATE TABLE TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(
    PN_ID              INT          NOT NULL PRIMARY KEY,
    N_VERSION          INT          NULL,
    S_IDENTIFICACION   VARCHAR(250) NOT NULL,
    T_FECHA_ALTA       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA     VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA    VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Sin identificación', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Gafete Institucional defensoría pública', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Gafete Institucional centro de meditación', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Copia certificada de cédula profesional', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Credencial para votar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Pasaporte', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Credencial del Instituto Nacional de las Personal Adultas Mayores (INAPAM)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Cartilla del Servicio Militar Nacional', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Licencia de conducir', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Cédula profesional', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Cartilla del Servicio Militar Nacional', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Certificado de primaria, secundaria o bachillerato con fotografía y sello oficial', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Credencial del IMSS, ISSSTE o ISSFAM con fotografía', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID, N_VERSION, S_IDENTIFICACION, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES( nextval('TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID'), 1, 'Carta de naturalización', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);
