DROP SEQUENCE IF EXISTS TRIALS.SEQ_PERSONADETALLE_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_PERSONADETALLE_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_PERSONADETALLE_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_PERSONADETALLE;

CREATE TABLE TRIALS.TBL_PERSONA_DETALLE
(
    PN_ID INT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('TRIALS.SEQ_PERSONADETALLE_ID'),
    FN_PERSONA_DOCUMENTO INT NOT NULL REFERENCES TRIALS.TBL_PERSONAS_DOCUMENTOS(PN_ID),
    FN_LENGUA_INDIGENA INT NOT NULL REFERENCES TRIALS.TBL_LENGUAS_INDIGENAS(PN_ID),
    FN_NACIONALIDAD INT NOT NULL REFERENCES TRIALS.TBL_NACIONALIDADES(PN_ID),
    FN_ESCOLARIDAD INT NOT NULL REFERENCES TRIALS.TBL_ESCOLARIDADES(PN_ID),
    FN_DOCUMENTO_IDENTIFICACION INT NOT NULL REFERENCES TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID),
    S_RAZON_SOCIAL VARCHAR(255),
    S_SEXO VARCHAR(10),
    D_FECHA_NACIMIENTO DATE,
    N_PAIS_NACIMIENTO INT,
    S_ENTIDAD_NACIMIENTO VARCHAR(100),
    S_MUNICIPIO_NACIMIENTO VARCHAR(100),
    N_EDAD INT,
    N_TIPO_DOMICILIO INT,
    S_RFC VARCHAR(13),
    N_DISCAPACIDAD INT, 
    N_ESTADO_CIVIL INT, 
    N_CONDICION_MIGRATORIA INT, 
    B_HABLA_ESPANOL BOOLEAN,
    S_LENGUA_EXTRANJERA VARCHAR(100),
    N_GRUPO_VULNERABLE INT, 
    B_SABE_LEER_ESCRIBIR BOOLEAN,
    N_PROFESION_OFICIO INT, 
    N_INGRESO_MENSUAL_NETO INT, 
    N_FRECUENCIA_INGRESO INT, 
    S_LUGAR_TRABAJO VARCHAR(100),
    N_CANTIDAD_DEPENDIENTES_ECONOMICOS INT,
    S_DETALLE_DEPENDIENTES VARCHAR(255),
    N_BIENES INT,
    S_RELIGION VARCHAR(100),
    S_SENIAS_PARTICULARES VARCHAR(100),
    S_GRUPO_ETNICO VARCHAR(100),
    B_DATOS_PRIVADOS BOOLEAN,
    S_CEDULA VARCHAR(13),
    N_TIPO_DEFENSOR INT, 
    S_ADSCRIPCION VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS IDX_FN_PERSONA_DOCUMENTO ON TRIALS.TBL_PERSONA_DETALLE (FN_PERSONA_DOCUMENTO);
CREATE INDEX IF NOT EXISTS IDX_FN_LENGUA_INDIGENA ON TRIALS.TBL_PERSONA_DETALLE (FN_LENGUA_INDIGENA);
CREATE INDEX IF NOT EXISTS IDX_FN_NACIONALIDAD ON TRIALS.TBL_PERSONA_DETALLE (FN_NACIONALIDAD);
CREATE INDEX IF NOT EXISTS IDX_FN_ESCOLARIDAD ON TRIALS.TBL_PERSONA_DETALLE (FN_ESCOLARIDAD);
CREATE INDEX IF NOT EXISTS IDX_FN_DOCUMENTO_IDENTIFICACION ON TRIALS.TBL_PERSONA_DETALLE (FN_DOCUMENTO_IDENTIFICACION);
