DROP TABLE IF EXISTS TRIALS.TBL_MENUS;

CREATE TABLE TRIALS.TBL_MENUS
(
    PN_ID       INT             NOT NULL PRIMARY KEY,
    S_NOMBRE    VARCHAR(250)    NOT NULL,
    S_ROL       VARCHAR(250)    NOT NULL,
    S_LINK      VARCHAR(250)    NOT NULL,
    N_ORDER     VARCHAR(250)    NOT NULL,
    FN_PARENT   INT             NULL,

    FOREIGN KEY (FN_PARENT) REFERENCES TRIALS.TBL_MENUS (PN_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IDX_MENUS1 ON TRIALS.TBL_MENUS (FN_PARENT);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (2, 'Catálogo', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO', '', 2, null);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (3, 'Registro', 'OFICIAL_MAYOR,CAPTURISTA', '', 3, null);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (4, 'Bandeja', 'OFICIAL_MAYOR,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO,OFICIAL_MAYOR_JUZGADO,SECRETARIO,TECNICO_JUZGADO,ADMINISTRADOR,ADMINISTRADOR_JUZGADO', '', 4, null);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (5, 'Sedes', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO', 'api/core/sedes', 1, 2);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (6, 'Instituciones', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO', 'api/core/instituciones', 2, 2);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (7, 'Oficialías', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO', 'api/core/oficialias', 3, 2);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (8, 'Juzgados', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO', 'api/core/juzgados', 4, 2);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (9, 'Personal', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO', 'api/core/personas', 5, 2);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (10, 'Salas', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO', 'api/core/salas', 6, 2);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (11, 'Bloques', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO', 'api/core/bloques', 7, 2);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (12, 'Historial', 'ADMINISTRADOR,ADMINISTRADOR_JUZGADO,OFICIAL_MAYOR,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO', 'api/bandeja/historial', 6, 4);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (13, 'Entrada', 'OFICIAL_MAYOR,CAPTURISTA,DIGITALIZADOR', 'api/bandeja/entrada', 1, 4);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (14, 'Demandas', 'OFICIAL_MAYOR,CAPTURISTA', 'api/workflow/demanda', 1, 3);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (15, 'Apelaciones', 'OFICIAL_MAYOR,CAPTURISTA', 'api/workflow/apelacion', 2, 3);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (16, 'Promociones', 'OFICIAL_MAYOR,CAPTURISTA', 'api/workflow/promocion', 3, 3);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (17, 'Exhortos', 'OFICIAL_MAYOR,CAPTURISTA', 'api/workflow/exhorto', 4, 3);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (18, 'Oficios', 'OFICIAL_MAYOR,CAPTURISTA', 'api/workflow/oficio', 2, 3);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (19, 'Salida', 'ENCARGADO_CARRITO', 'api/bandeja/salida', 2, 4);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (20, 'Recepción', 'OFICIAL_MAYOR_JUZGADO,TECNICO_JUZGADO,SECRETARIO', 'api/bandeja/recepcion', 3, 4);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (21, 'Asignado', 'OFICIAL_MAYOR_JUZGADO,TECNICO_JUZGADO,SECRETARIO', 'api/bandeja/asignados', 4, 4);

INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (22, 'Oficios', 'TODOS', 'api/bandeja/oficios', 5, 4);
