DROP SEQUENCE IF EXISTS TRIALS.SEQ_CARPETA_DETALLE_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_CARPETA_DETALLE_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_CARPETA_DETALLE_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_CARPETA_DETALLE;
CREATE TABLE TRIALS.TBL_CARPETA_DETALLE
(
   PN_ID                             INT          NOT NULL PRIMARY KEY,
   FN_CARPETA                        INT          NOT NULL REFERENCES TRIALS.TBL_CARPETAS (PN_ID),
   T_FECHA_ADMISION                  TIMESTAMP,
   T_FECHA_DESECHADO                 TIMESTAMP,
   S_ASUNTO                          VARCHAR(150),
   S_OBSERVACIONES                   VARCHAR(300),
   S_PROMOVENTE                      VARCHAR(150),
   S_NUMERO_CARPETA_INVESTIGACION    VARCHAR(50),
   S_NUMERO_OFICIO                   VARCHAR(50),
   S_LUGAR_HECHO                     VARCHAR(150),
   T_FECHA_HECHO                     DATE,
   N_CANTIDAD_PRINCIPAL              INT,
   S_MONEDA                          VARCHAR(10),
   N_HIJOS                           INT,
   N_HIJOS_MENORES_EDAD              INT,
   S_NUMERO_ACTA_MATRIMONIO          VARCHAR(50),
   S_LUGAR_ACTA_MATRIMONIO           VARCHAR(150),
   S_ENTIDAD                         VARCHAR(150),
   S_MUNICIPIO                       VARCHAR(150),
   S_LOCALIDAD                       VARCHAR(150),
   T_FECHA_REGISTRO                  TIMESTAMP,
   T_HORA_REGISTRO                   TIME,
   T_HORA_MATERIAL                   TIME,
   S_LUGAR_DISPOSICION               VARCHAR(150),
   N_PRESENTACION_IMPUTADO           INT,
   N_SOLICITUD_AUDIENCIA             INT,
   T_FECHA_PRESENTACION_IMPUTADO     TIMESTAMP,
   FN_TIPO_JUICIO                    INT         REFERENCES TRIALS.TBL_TIPO_JUICIO (PN_ID)
);
CREATE INDEX IF NOT EXISTS IDX_CARPETA_DETALLE_CARPETA ON TRIALS.TBL_CARPETA_DETALLE (FN_CARPETA);
CREATE INDEX IF NOT EXISTS IDX_CARPETA_DETALLE_TIPO_JUICIO ON TRIALS.TBL_CARPETA_DETALLE (FN_TIPO_JUICIO);