
INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (24, 'Expedientes antiguos', 'OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO', 'api/workflow/registro', 5, 3);

INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (13, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Gustavo', 'Auxiliar', '', '', 1, 'auxiliar@sala.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, 'cc6581af-c792-4255-9331-ead71c3235c3', 12, 1
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';
