DROP SEQUENCE IF EXISTS TRIALS.SEQ_TIPO_PIEZA_ID;

CREATE SEQUENCE TRIALS.SEQ_TIPO_PIEZA_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_TIPO_PIEZA_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_TIPO_PIEZA;

CREATE TABLE TRIALS.TBL_TIPO_PIEZA(
    PN_ID              INT          NOT NULL PRIMARY KEY,
    N_VERSION          INT          NULL,
    S_TIPO             VARCHAR(250) NOT NULL,
    S_CLAVE            VARCHAR(25)  NOT NULL,
    T_FECHA_ALTA       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA     VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA    VARCHAR(50) NOT NULL DEFAULT CURRENT_USER
);


INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    1, 0, 'INCIDENTE DE NULIDAD', 'IN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    2, 0, 'AMPARO', 'AM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    3, 0, 'PRUEBAS ACTOR', 'PA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    4, 0, 'PRUEBAS DEMANDADO', 'PD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    5, 0, 'TERCERIAS ', 'TE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    6, 0, 'ACTUACION', 'AC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    7, 0, 'RECLAMACION', 'RE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    8, 0, 'QUEJA', 'QU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    9, 0, 'APELACION', 'AP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    10, 0, 'P. TERCERIA ACTOR', 'TA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    11, 0, 'P. TERCERIA DEMANDADO', 'TD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    12, 0, 'PROVIDENCIA PRECAUTORIA', 'PP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    13, 0, 'RESPONSABILIDAD', 'ER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    14, 0, 'I. FALTA DE PERSONALIDAD', 'IF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    15, 0, 'I. CANCELACION DE EMBARGO', 'IC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    16, 0, 'I.  LANZAMIENTO', 'IL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    17, 0, 'AMPARO DIRECTO', 'AD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    18, 0, 'I. DE MODIFICACION', 'IM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    19, 0, 'TERCERIA EXCLUYENTE DE DOMINIO', 'TX', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    20, 0, 'I. DE TACHAS', 'IT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    21, 0, 'I. PENAL', 'IP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    22, 0, 'I. PETICION DE HERENCIA ', 'IH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    23, 0, 'I. REMOCION ALBACEA', 'IA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    24, 0, 'I. OBJECION', 'IO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    25, 0, 'I. INNOMINADO', 'II', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    26, 0, 'I. REDUCCION', 'IR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    27, 0, 'I. REMOCION', 'IZ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    28, 0, 'MODIFICACION DE PENSION', 'MP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    29, 0, 'ACUMULACION', 'IU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    30, 0, 'I. ERRORES Y ATENTADOS', 'RA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    31, 0, 'I. OBJECION DE PRUEBAS', 'OP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    32, 0, 'I. DECLINATORIA', 'ID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    33, 0, 'I. IMPROCEDENCIA DE LA VIA', 'IV', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    34, 0, 'DECLARATORIA POR INCOMPETENCIA', 'DI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    35, 0, 'SENTECIA DE NULIDAD DE ACTUACIONES', 'SN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    36, 0, 'PRUEBAS ACTOR EXCLUYENTE', 'PE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    37, 0, 'LIQUIDACION DE SENTENCIA', 'LS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    38, 0, 'TERCERIA COADYUGANTE', 'TC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    39, 0, 'PLANILLA DE GASTOS Y COSTOS', 'GC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    40, 0, 'TERCERIA EXCLUYENTE DE PREFERENCIAS', 'TP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    41, 0, 'LEGAJO DE PERSONAL', 'LP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    42, 0, 'LEGAJO DE OFICIOS', 'LO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    43, 0, 'I. REDUCCION DE EMBARGO', 'IE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    44, 0, 'T. AUTORIZACION JUDICIAL', 'AJ', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    45, 0, 'I. AMPLIACION DE EMBARGO', 'AE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    46, 0, 'I. FALTA DE PERSONALIDAD', 'PR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    47, 0, 'I. PRESCRIPCION', 'PC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    48, 0, 'I. REPOSICION DE DOCUMENTO', 'RD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    49, 0, 'ACLARACION SENTENCIA', 'AS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    50, 0, 'I. INMATRICULACION', 'NM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    51, 0, 'PRUEBAS COLIDANTE', 'CD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    52, 0, 'SENTENCIA DEFINITIVA', 'SD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    53, 0, 'OTORGAMIENTO DE ESCRITURA PUBLICA', 'ES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    54, 0, 'FALTA DE LEGITIMIDAD', 'FL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    55, 0, 'MEDIOS PREPARATORIOS A JUICIO', 'PG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    56, 0, 'PROYECTO DE PARTICIPACION', 'PY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    57, 0, 'I. VENTA DE MENORES', 'VM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    58, 0, 'I. DEDUCCION DE PENSION ALIMENTICIA', 'DP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    59, 0, 'I. AUMENTO DE PENSION ALIMENTICIA', 'AL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    60, 0, 'I. SUSTITUCION DE GARANTIAS', 'IG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    61, 0, 'I. EXCEPCION Y PRUEBAS S.', 'YP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    62, 0, 'TOMO', 'TM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    63, 0, 'R. REVOCACION', 'RR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    64, 0, 'I. CANCELACION PENSION ALIMENTICIA', 'CP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    65, 0, 'I. INVENTARIOS Y AVALUOS', 'AN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    66, 0, 'I.CANCELACION DE HIPOTECA POR PRESCRIPCION', 'CH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    67, 0, 'I.CANCELACION DE EMBARGO POR PRESCRIPCION', 'CE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    68, 0, 'DOCUMENTOS', 'DO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    69, 0, 'LEGAJO DE ACUERDOS', 'LA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    70, 0, 'LEGAJO DE SENTENCIAS', 'SL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    71, 0, 'INCIDENTE DE FALSEDAD', 'FA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    72, 0, 'INCIDENTE DE INEJECUCION DE SENTENCIA POR PRESCIPCION', 'SP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    73, 0, 'EXPEDIENTILLO DE ACTUACION', 'EX', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    74, 0, 'I.DE HOMONIMIA', 'HO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    75, 0, 'EXP. PRINCIPAL', 'EP', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    76, 0, 'INCIDENTE DE LIQUIDACIÓN DE SOCIEDAD CONYUGAL', 'CY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    77, 0, 'INCIDENTE DE SUSPENSION', 'SU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    78, 0, 'REPOSICION DE AUTOS', 'RT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    79, 0, 'RECURSO DE RECONSIDERACIÓN', 'RC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    80, 0, 'DUPLICADO DEL EXPEDIENTE PRINCIPAL', 'DU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    81, 0, 'COPIAS CERTIFICADAS DE EXPEDIENTE', 'CC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);

INSERT INTO TRIALS.TBL_TIPO_PIEZA (PN_ID, N_VERSION, S_TIPO, S_CLAVE, T_FECHA_ALTA, T_FECHA_EDITA, S_USUARIO_ALTA, S_USUARIO_EDITA) VALUES (
    82, 0, 'INCIDENTE DE RECUSACIÓN', 'RU', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER);