--Insertar tipo de juicio Padre faltantes
INSERT INTO trials.tbl_tipo_juicio (pn_id, n_version, s_nombre, n_estado, fn_tipo_sistema, fn_materia, t_fecha_alta, t_fecha_edita, s_usuario_alta, s_usuario_edita, fn_tipo_juicio_padre_oral, fn_tipo_juicio_padre_trad)
VALUES (nextval('trials.seq_tipo_juicio_id'), 0, 'Penal', 0, null, (SELECT pn_id FROM trials.tbl_materias WHERE s_nombre = 'PENAL'),
CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, NULL);

--Insertar tipo de juicio hijos
INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Causas Penales con Detenido', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Causas Penales sin Detenido', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Causas Penales por Orden De Aprehensión', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo de Control Judicial', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo de Control De Actos De Investigación', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo De Exhorto', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Carpetas De Ejecución', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Carpetas De Juicio', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Expedientillo De Actuaciones S/N', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA, FN_TIPO_JUICIO_PADRE_ORAL, FN_TIPO_JUICIO_PADRE_TRAD)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Otros', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', NULL, M.PN_ID,
(SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal'), (SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Penal')
FROM TRIALS.TBL_MATERIAS AS M WHERE M.S_NOMBRE = 'PENAL';
