INSERT INTO TRIALS.TBL_MENUS (PN_ID, S_NOMBRE, S_ROL, S_LINK, N_ORDER, FN_PARENT)
VALUES (23, 'Amparo', 'OFICIAL_MAYOR_JUZGADO', 'api/workflow/amparo', 6, 3);

UPDATE TRIALS.TBL_MENUS SET S_ROL = S_ROL || ',OFICIAL_MAYOR_JUZGADO' WHERE S_NOMBRE = 'Registro';