ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE ADD COLUMN S_TIPO_ACUERDO VARCHAR;
ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE ADD COLUMN T_FECHA_RESOLUCION DATE;
ALTER TABLE TRIALS.TBL_DOCUMENTO_DETALLE ADD COLUMN S_ETAPA_PROCESAL VARCHAR;