DROP SEQUENCE IF EXISTS TRIALS.SEQ_CARPETA_ETAPAS_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_CARPETA_ETAPAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_CARPETA_ETAPAS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_CARPETA_ETAPAS;
CREATE TABLE TRIALS.TBL_CARPETA_ETAPAS
(
   PN_ID                 INT            NOT NULL PRIMARY KEY,
   FN_CARPETA_ID         INT            NOT NULL REFERENCES TRIALS.TBL_CARPETAS (PN_ID),
   FN_ETAPA_ID           INT            NOT NULL REFERENCES TRIALS.TBL_ETAPA_PROCESAL (PN_ID),
   T_FECHA_REGISTRO      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
   S_OBSERVACIONES       VARCHAR(300)
);
CREATE INDEX IF NOT EXISTS IDX_CARPETA_ETAPAS_CARPETA ON TRIALS.TBL_CARPETA_ETAPAS (FN_CARPETA_ID);
CREATE INDEX IF NOT EXISTS IDX_CARPETA_ETAPAS_ETAPA_PROCESAL ON TRIALS.TBL_CARPETA_ETAPAS (FN_ETAPA_ID);
