ALTER TABLE TRIALS.TBL_DOCUMENTOS
ADD COLUMN FN_ACUERDO_RESPUESTA INT;

ALTER TABLE TRIALS.TBL_DOCUMENTOS
ADD CONSTRAINT FK_ACUERDO_RESPUESTA 
FOREIGN KEY (FN_ACUERDO_RESPUESTA) 
REFERENCES TRIALS.TBL_DOCUMENTOS(PN_ID);
