ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD S_INE varchar(25);

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD S_CURP varchar(18);

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD S_CELULAR varchar(25);

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD S_EMAIL varchar(100);

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD FN_DOMICILIO varchar(120);