
DROP SEQUENCE IF EXISTS TRIALS.SEQ_CONCEPTOS_ID;
CREATE SEQUENCE TRIALS.SEQ_CONCEPTOS_ID START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_CONCEPTOS;
CREATE TABLE TRIALS.TBL_CONCEPTOS (
    PN_ID INT NOT NULL PRIMARY KEY,
    N_VERSION INT NOT NULL,
    S_NOMBRE VARCHAR(100) NOT NULL,
    N_DIAS INT NOT NULL,
    N_TIPO_CONCEPTO INT NOT NULL,
    FN_JUZGADO INT NOT NULL,
    N_ESTADO INT NOT NULL,
    S_USUARIO_ALTA VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    S_USUARIO_EDITA VARCHAR(50) DEFAULT CURRENT_USER NOT NULL,
    T_FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    T_FECHA_EDITA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_juzgados FOREIGN KEY (FN_JUZGADO) REFERENCES TRIALS.TBL_JUZGADOS (PN_ID)
);

CREATE INDEX IDX_CONCEPTOS_JUZGADOS1 ON TRIALS.TBL_CONCEPTOS (FN_JUZGADO);

INSERT INTO TRIALS.TBL_CONCEPTOS (PN_ID, N_VERSION, S_NOMBRE, N_DIAS, N_TIPO_CONCEPTO, FN_JUZGADO, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (NEXTVAL('TRIALS.SEQ_CONCEPTOS_ID'), 1, 'Distribución', 1, 0, 150, 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');

INSERT INTO TRIALS.TBL_CONCEPTOS (PN_ID, N_VERSION, S_NOMBRE, N_DIAS, N_TIPO_CONCEPTO, FN_JUZGADO, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA)
VALUES (NEXTVAL('TRIALS.SEQ_CONCEPTOS_ID'), 1,'Adjuntar', 1, 1, 200, 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7');

