DROP SEQUENCE IF EXISTS TRIALS.SEQ_TIPO_AUDIENCIA_ID;
CREATE SEQUENCE TRIALS.SEQ_TIPO_AUDIENCIA_ID START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_TIPO_AUDIENCIA;

CREATE TABLE trials.TBL_TIPO_AUDIENCIA (
	pn_id INT NOT NULL,
	n_version INT NOT NULL,
	s_nombre VARCHAR NOT NULL,
	n_estado INT NOT NULL,
	s_usuario_alta VARCHAR DEFAULT CURRENT_USER NOT NULL,
	s_usuario_edita varchar DEFAULT CURRENT_USER NOT NULL,
	t_fecha_alta timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	t_fecha_edita timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (pn_id)
);

