ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD S_INE varchar(25);

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD S_CURP varchar(18);

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD S_CELULAR varchar(25);

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD S_EMAIL varchar(100);

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD FN_DOMICILIO INT;

ALTER TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
ADD CONSTRAINT fk_fn_domicilio
FOREIGN KEY (FN_DOMICILIO) 
REFERENCES TRIALS.TBL_DOMICILIOS(PN_ID) ON DELETE CASCADE;