
ALTER TABLE TRIALS.TBL_TIPO_JUICIO ALTER COLUMN FN_TIPO_SISTEMA DROP NOT NULL;

INSERT INTO TRIALS.TBL_TIPO_JUICIO (PN_ID, N_VERSION, S_NOMBRE, N_ESTADO, S_USUARIO_ALTA, S_USUARIO_EDITA, FN_TIPO_SISTEMA, FN_MATERIA)
SELECT nextval('TRIALS.SEQ_TIPO_JUICIO_ID'), 0, 'Exhorto', 0, '6b13785f-d213-4585-a76b-437ffe57c9c7', '6b13785f-d213-4585-a76b-437ffe57c9c7', S.PN_ID, M.PN_ID
FROM TRIALS.TBL_TIPO_SISTEMA AS S, TRIALS.TBL_MATERIAS AS M WHERE S.S_NOMBRE = 'Tradicional' AND M.S_NOMBRE = 'EXHORTO';