DROP TABLE IF EXISTS TRIALS.TBL_LISTA_VALOR;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_TIPOJUICIO_ETIQUETAS;
CREATE TABLE TRIALS.TBL_TIPOJUICIO_ETIQUETAS
(
    PN_ID            INT            NOT NULL PRIMARY KEY,
    S_NOMBRE         VARCHAR(100)   NOT NULL,
    S_VALUE          VARCHAR(100)   NOT NULL,
    FN_TIPO_JUICIO   INT            NOT NULL,
    T_FECHA_ALTA     TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA   VARCHAR(50)    DEFAULT CURRENT_USER,
    S_USUARIO_EDITA  VARCHAR(50)    DEFAULT CURRENT_USER,

    FOREIGN KEY (FN_TIPO_JUICIO) REFERENCES TRIALS.TBL_TIPO_JUICIO(PN_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Laboral (Tradicional)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Demanda', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Laboral (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Laboral (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Laboral (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Laboral (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Laboral (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Laboral (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Laboral (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Laboral (Tradicional)';

-- Familiar (Tradicional)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Demanda', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar (Tradicional)';

-- Mercantil (Tradicional)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Demanda', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Mercantil (Tradicional)';

-- Oralidad Mercantil (Oral)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral)';

-- Oralidad Mercantil (Oral Ejecutivo)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral Ejecutivo)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral Ejecutivo)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral Ejecutivo)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral Ejecutivo)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral Ejecutivo)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral Ejecutivo)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral Ejecutivo)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Oral Ejecutivo)';

-- Oralidad Mercantil (Providencia precautoria)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Providencia precautoria)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Providencia precautoria)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Providencia precautoria)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Providencia precautoria)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Providencia precautoria)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Providencia precautoria)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Providencia precautoria)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Providencia precautoria)';

-- Oralidad Mercantil (Medios preparatorios)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Medios preparatorios)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Medios preparatorios)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Medios preparatorios)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Medios preparatorios)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Medios preparatorios)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Medios preparatorios)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Medios preparatorios)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Oralidad Mercantil (Medios preparatorios)';

-- Civil (Tradicional)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Demanda', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Tradicional)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Tradicional)';

-- Civil (Juicio de extincion de dominio)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Demanda', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Juicio de extincion de dominio)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Juicio de extincion de dominio)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Juicio de extincion de dominio)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Juicio de extincion de dominio)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Juicio de extincion de dominio)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Juicio de extincion de dominio)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Juicio de extincion de dominio)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Juicio de extincion de dominio)';

-- Civil (Oral)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

-- Civil (Oral)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Civil (Oral)';

-- Familiar Oralidad
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpActor', 'CURP del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineActor', 'INE del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioActor', 'Domicilio del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'celularActor', 'Celular del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoActor', 'Correo del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpDemandado', 'CURP del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineDemandado', 'INE del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'cedulaAbogado', 'Cedula Profesional del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoAbogado', 'Correo Electrónico del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad';

-- Familiar Oralidad (Alimentos)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpActor', 'CURP del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineActor', 'INE del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioActor', 'Domicilio del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'celularActor', 'Celular del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoActor', 'Correo del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpDemandado', 'CURP del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineDemandado', 'INE del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'cedulaAbogado', 'Cedula Profesional del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoAbogado', 'Correo Electrónico del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Alimentos)';

-- Familiar Oralidad (Divorcio Incausado Unilateral)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpActor', 'CURP del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineActor', 'INE del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioActor', 'Domicilio del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'celularActor', 'Celular del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoActor', 'Correo del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpDemandado', 'CURP del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineDemandado', 'INE del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'cedulaAbogado', 'Cedula Profesional del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoAbogado', 'Correo Electrónico del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Divorcio Incausado Unilateral)';

-- Familiar Oralidad  (Divoricio Incausado Bilateral)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpActor', 'CURP del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineActor', 'INE del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioActor', 'Domicilio del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'celularActor', 'Celular del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoActor', 'Correo del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpDemandado', 'CURP del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineDemandado', 'INE del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'cedulaAbogado', 'Cedula Profesional del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoAbogado', 'Correo Electrónico del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad  (Divoricio Incausado Bilateral)';

-- Familiar Oralidad (Guardia y Custodia)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioNino', 'Domicilio del niño, niña o adolescente', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpActor', 'CURP del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineActor', 'INE del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioActor', 'Domicilio del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'celularActor', 'Celular del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoActor', 'Correo del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpDemandado', 'CURP del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineDemandado', 'INE del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'cedulaAbogado', 'Cedula Profesional del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoAbogado', 'Correo Electrónico del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Guardia y Custodia)';

-- Familiar Oralidad (Visita y Convivencia)
INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioNino', 'Domicilio del niño, niña o adolescente', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'documento', 'Solicitud de Audiencia', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreActor', 'Nombre del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoActor', 'Apellido Paterno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoActor', 'Apellido Materno del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpActor', 'CURP del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineActor', 'INE del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'domicilioActor', 'Domicilio del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'celularActor', 'Celular del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoActor', 'Correo del Actor', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'nombreDemandado', 'Nombre del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoPaternoDemandado', 'Apellido Paterno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'apellidoMaternoDemandado', 'Apellido Materno del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'curpDemandado', 'CURP del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'ineDemandado', 'INE del Demandado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'cedulaAbogado', 'Cedula Profesional del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'correoAbogado', 'Correo Electrónico del Abogado', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';

INSERT INTO TRIALS.TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
SELECT nextval('TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID'), 'anexos', 'Anexos', TJ.PN_ID
FROM TRIALS.TBL_TIPO_JUICIO AS TJ WHERE TJ.S_NOMBRE = 'Familiar Oralidad (Visita y Convivencia)';
