
DELETE FROM TRIALS.TBL_PERSONAS_DOCUMENTOS;
DELETE FROM TRIALS.TBL_DOCUMENTOS;
DROP TABLE IF EXISTS TRIALS.TBL_DOCUMENTOS CASCADE;
DROP TABLE IF EXISTS TRIALS.TBL_CARPETAS CASCADE;

CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_CARPETAS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_CARPETAS_ID INCREMENT BY 50;

CREATE TABLE TRIALS.TBL_CARPETAS
(
    PN_ID               INT         NOT NULL PRIMARY KEY,
    N_VERSION           INT,
    S_FOLIO             VARCHAR(15) NOT NULL,
    S_EXPEDIENTE        VARCHAR(20) NOT NULL,
    S_RUTA              VARCHAR(50),
    N_IMPRESION_SELLO   INT         NOT NULL,
    N_ESTADO            INT         NOT NULL,
    FN_JUZGADO          INT         NOT NULL,
    FN_TIPO_JUICIO      INT         NOT NULL,
    T_FECHA_ALTA        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA      VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA     VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    FOREIGN KEY (FN_TIPO_JUICIO) REFERENCES TRIALS.TBL_TIPO_JUICIO (PN_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (FN_JUZGADO) REFERENCES TRIALS.TBL_JUZGADOS (PN_ID) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IDX_CARPETA_JUZGADO1 ON TRIALS.TBL_CARPETAS (FN_JUZGADO);
CREATE INDEX IDX_CARPETA_TIPOJUICIO2 ON TRIALS.TBL_CARPETAS (FN_TIPO_JUICIO);

CREATE TABLE TRIALS.TBL_DOCUMENTOS
(
    PN_ID              INT         NOT NULL PRIMARY KEY,
    N_VERSION          INT,
    N_TIPO_DOCUMENTO   INT         NOT NULL,
    J_DATA             JSONB,
    FN_DOCUMENTO       INT,
    FN_CARPETA         INT         NOT NULL,
    T_FECHA_ALTA       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA     VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA    VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    FOREIGN KEY (FN_DOCUMENTO) REFERENCES TRIALS.TBL_DOCUMENTOS (PN_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (FN_CARPETA) REFERENCES TRIALS.TBL_CARPETAS (PN_ID) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IDX_DOCUMENTOS_DOCUMENTO1 ON TRIALS.TBL_DOCUMENTOS (FN_DOCUMENTO);
CREATE INDEX IDX_DOCUMENTOS_CARPETA2 ON TRIALS.TBL_DOCUMENTOS (FN_CARPETA);

DROP TABLE IF EXISTS TRIALS.TBL_PERSONAS_DOCUMENTOS CASCADE;
CREATE TABLE TRIALS.TBL_PERSONAS_DOCUMENTOS
(
    PN_ID               INT         NOT NULL PRIMARY KEY,
    S_NOMBRES           VARCHAR(50) NOT NULL,
    S_APELLIDO_PATERNO  VARCHAR(40),
    S_APELLIDO_MATERNO  VARCHAR(40),
    S_PSEUDONIMO        VARCHAR(40),
    S_TIPO_PERSONA      VARCHAR(40),
    FN_CARPETA          INT         NOT NULL,
    FN_TIPO_PARTE       INT         NOT NULL,
    T_FECHA_ALTA        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA      VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA     VARCHAR(50) NOT NULL DEFAULT CURRENT_USER,
    FOREIGN KEY (FN_CARPETA) REFERENCES TRIALS.TBL_CARPETAS (PN_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (FN_TIPO_PARTE) references TRIALS.TBL_TIPO_PARTES (PN_ID) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IDX_PERSONASDOCUMENTOS_CARPETA1 ON TRIALS.TBL_PERSONAS_DOCUMENTOS (FN_CARPETA);
CREATE INDEX IDX_PERSONASDOCUMENTOS_TIPOPARTE2 ON TRIALS.TBL_PERSONAS_DOCUMENTOS (FN_TIPO_PARTE);
