CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_JUZGADO_FOLIOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_JUZGADO_FOLIOS_ID INCREMENT BY 1 ;

DROP TABLE IF EXISTS TRIALS.TBL_JUZGADO_FOLIOS;
CREATE TABLE TRIALS.TBL_JUZGADO_FOLIOS
(
    PN_ID             INT   NOT NULL PRIMARY KEY,
    FN_JUZGADO_ID     INT   NOT NULL,
    N_TIPO_CARPETA    INT   NOT NULL,
    N_VALUE           INT   NOT NULL DEFAULT (1),
    N_YEAR            INT   NOT NULL DEFAULT (EXTRACT(YEAR FROM CURRENT_TIMESTAMP)),

    FOREIGN KEY (FN_JUZGADO_ID) REFERENCES TRIALS.TBL_JUZGADOS(PN_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IDX_JUZGADO_FOLIOS1 ON TRIALS.TBL_JUZGADO_FOLIOS (FN_JUZGADO_ID);