DROP SEQUENCE IF EXISTS TRIALS.SEQ_INSTITUCIONES_ID;
CREATE SEQUENCE TRIALS.SEQ_INSTITUCIONES_ID START WITH 1;
ALTER SEQUENCE TRIALS.SEQ_INSTITUCIONES_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_INSTITUCIONES;
CREATE TABLE TRIALS.TBL_INSTITUCIONES
(
    PN_ID                   INT          NOT NULL PRIMARY KEY,
    S_NOMBRE                VARCHAR(100) NOT NULL,
    N_VERSION               INT          NOT NULL,
    FN_DOMICILIO            INT          NOT NULL,
    FN_DISTRITO             INT          NOT NULL,
    N_ESTADO                INT          NOT NULL,
    S_TELEFONO              VARCHAR(20)  NOT NULL,
    S_EXTENSION             VARCHAR(6)   NOT NULL,
    T_FECHA_ALTA            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA          VARCHAR(50)  NOT NULL DEFAULT CURRENT_USER,
    S_USUARIO_EDITA         VARCHAR(50)  NOT NULL DEFAULT CURRENT_USER,
    
    CONSTRAINT fk_domicilio FOREIGN KEY (FN_DOMICILIO) 
    REFERENCES TRIALS.TBL_DOMICILIOS (PN_ID) ON DELETE CASCADE 
);
