DROP SEQUENCE IF EXISTS TRIALS.SEQ_AUDIENCIA_ID;
CREATE SEQUENCE TRIALS.SEQ_AUDIENCIA_ID START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_AUDIENCIAS;

CREATE TABLE trials.TBL_AUDIENCIAS (
	n_id INT NOT NULL PRIMARY KEY,
	n_version INT NOT NULL,
	t_fecha_audiencia TIMESTAMP NOT NULL,
	n_asistencia_actor INT NULL,
	n_asistencia_demandado INT NULL,
	t_hora_inicio TIMESTAMP,
	t_hora_fin TIMESTAMP,
	n_estatus_audiencia INT NOT NULL,
	fn_sala INT NOT NULL,
	fn_carpeta INT NOT NULL,
	fn_bloque INT NOT NULL,
	fn_tipo_audiencia INT NOT NULL,
	t_fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	t_fecha_edita TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	t_usuario_alta VARCHAR DEFAULT CURRENT_USER NOT NULL,
	t_usuario_edita VARCHAR DEFAULT CURRENT_USER NOT NULL,
	n_status INT NULL
);

ALTER TABLE trials.TBL_AUDIENCIAS ADD CONSTRAINT fk_salas FOREIGN KEY (fn_sala) REFERENCES trials.TBL_SALAS(pn_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE trials.TBL_AUDIENCIAS ADD CONSTRAINT fk_bloque FOREIGN KEY (fn_bloque) REFERENCES trials.TBL_BLOQUES(pn_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE trials.TBL_AUDIENCIAS ADD CONSTRAINT fk_carpeta FOREIGN KEY (fn_carpeta) REFERENCES trials.TBL_CARPETAS(pn_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE trials.TBL_AUDIENCIAS ADD CONSTRAINT fk_tipo_audiencia FOREIGN KEY (fn_tipo_audiencia) REFERENCES trials.TBL_TIPO_AUDIENCIA(pn_id) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE INDEX IDX_AUDIENCIAS1 ON TRIALS.TBL_AUDIENCIAS (FN_SALA);
CREATE INDEX IDX_AUDIENCIAS2 ON TRIALS.TBL_AUDIENCIAS (FN_BLOQUE);
CREATE INDEX IDX_AUDIENCIAS3 ON TRIALS.TBL_AUDIENCIAS (FN_CARPETA);
CREATE INDEX IDX_AUDIENCIAS4 ON TRIALS.TBL_AUDIENCIAS (FN_TIPO_AUDIENCIA);