SPRING_FLYWAY_ENABLED=true
SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=https://latest.pjptrials.link/kc/realms/trials-realm
KEYCLOAK_SERVERURL=https://latest.pjptrials.link/kc
SPRING_DATASOURCE_URL=jdbc:postgresql://trials-alpha-latest.postgres.database.azure.com:5432/trialsdb?currentSchema=trials