ALTER TABLE TRIALS.TBL_CARPETAS ADD FN_CONCEPTO INT NULL;

ALTER TABLE TRIALS.TBL_CARPETAS
ADD FOREIGN KEY (FN_CONCEPTO)
REFERENCES TRIALS.TBL_CONCEPTOS (PN_ID);

CREATE INDEX IDX_CARPETAS6 ON TRIALS.TBL_CARPETAS (FN_CONCEPTO);

ALTER TABLE TRIALS.TBL_CARPETAS ADD N_HORAS INT NULL;

ALTER TABLE TRIALS.TBL_DOCUMENTOS DROP COLUMN N_HORAS;

ALTER TABLE TRIALS.TBL_DOCUMENTOS DROP COLUMN N_HORAS;

ALTER TABLE TRIALS.TBL_CARPETAS ADD N_PRIORIDAD INT NULL;