DROP SEQUENCE IF EXISTS TRIALS.SEQ_PLACEHOLDERS_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_PLACEHOLDERS_ID START WITH 50;
ALTER SEQUENCE TRIALS.SEQ_PLACEHOLDERS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_PLACEHOLDERS;
CREATE TABLE TRIALS.TBL_PLACEHOLDERS (
    PN_ID INT NOT NULL PRIMARY KEY,
    S_NOMBRE VARCHAR(250) NOT NULL,
    S_VALOR TEXT,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER
);
