UPDATE TRIALS.TBL_MENUS SET S_ROL = S_ROL || ',OFICIAL_MAYOR_OFICIALIA' WHERE S_NOMBRE = 'Salida';

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'OFICIAL_MAYOR_OFICIALIA,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO' WHERE S_NOMBRE = 'Historial';

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'OFICIAL_MAYOR_OFICIALIA,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO,OFICIAL_MAYOR_JUZGADO,SECRETARIO,TECNICO_JUZGADO,DILIGENCIARIO,PROYECTISTA,ENCARGADO_SALA,ADMINISTRADOR_JUZGADO' WHERE S_NOMBRE = 'Bandeja';

UPDATE TRIALS.TBL_MENUS SET S_ROL = S_ROL || ',AUXILIAR_OFICIAL_MAYOR_JUZGADO' WHERE S_NOMBRE = 'Amparo';

UPDATE TRIALS.TBL_MENUS SET S_ROL = S_ROL || ',AUXILIAR_OFICIAL_MAYOR_JUZGADO,ENCARGADO_SALA' WHERE S_NOMBRE = 'Registro';

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,SECRETARIO,PROYECTISTA,TECNICO_JUZGADO,ENCARGADO_SALA,DILIGENCIARIO' WHERE S_NOMBRE = 'Recepción';

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'CAPTURISTA,OFICIAL_MAYOR_OFICIALIA,DIGITALIZADOR,OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,TECNICO_JUZGADO,SECRETARIO,ENCARGADO_SALA,DILIGENCIARIO,JUEZ,ADMINISTRADOR_JUZGADO,PROYECTISTA' WHERE PN_ID = 22;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,SECRETARIO,PROYECTISTA,TECNICO_JUZGADO,SECRETARIO,ENCARGADO_SALA,ADMINISTRADOR_JUZGADO,CAPTURISTA,OFICIAL_MAYOR_OFICIALIA' WHERE PN_ID = 18;

UPDATE TRIALS.TBL_MENUS SET S_NOMBRE = 'Libro de gobierno' WHERE PN_ID = 26;

INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (15, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Armando', 'Pérez Juez', '', '', 1, 'juez@juez.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, '37c467af-6f04-4a81-9dc1-f4565cbb5278', 15, 1
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

INSERT INTO TRIALS.TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO, S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (16, '', '','','','','','','', '');

INSERT INTO TRIALS.TBL_PERSONAS (PN_ID, N_VERSION, S_NOMBRES, S_APELLIDO_PATERNO, S_CURP, S_RFC, N_SEXO, S_CORREO_ELECTRONICO, S_TELEFONO, S_CELULAR, T_FECHA_NACIMIENTO, FN_ESTADO_CIVIL, S_OCUPACION, FN_ESCOLARIDAD, N_ESTADO, S_USUARIO, FN_DOMICILIO, FN_JUZGADO)
SELECT nextval('TRIALS.SEQ_PERSONAS_ID'), 0, 'Silvia', 'Rodriguez Comisario', '', '', 1, 'comisario@comisario.dev', '', '', '1992-10-10', EC.PN_ID, '', E.PN_ID, 0, '9a8cbb8a-945c-4efa-9871-c66d730a38df', 16, 1
FROM TRIALS.TBL_ESTADO_CIVIL AS EC, TRIALS.TBL_ESCOLARIDADES AS E WHERE EC.S_NOMBRE = 'Soltero/a' AND E.S_NOMBRE = 'No especificado';

DROP SEQUENCE IF EXISTS TRIALS.SEQ_LISTA_ESTRADOS_ID;
CREATE SEQUENCE TRIALS.SEQ_LISTA_ESTRADOS_ID START WITH 50;
ALTER SEQUENCE TRIALS.SEQ_LISTA_ESTRADOS_ID INCREMENT BY 1;

ALTER TABLE TRIALS.TBL_NOTIFICACIONES DROP COLUMN IF EXISTS FN_CARPETA;