UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_SISTEMA,ADMINISTRADOR_JUZGADO' WHERE PN_ID = 2;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_SISTEMA,ADMINISTRADOR_JUZGADO' WHERE PN_ID = 5;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_SISTEMA,ADMINISTRADOR_JUZGADO' WHERE PN_ID = 6;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_SISTEMA,ADMINISTRADOR_JUZGADO' WHERE PN_ID = 7;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_SISTEMA,ADMINISTRADOR_JUZGADO' WHERE PN_ID = 8;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_SISTEMA,ADMINISTRADOR_JUZGADO' WHERE PN_ID = 9;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_SISTEMA,ADMINISTRADOR_JUZGADO' WHERE PN_ID = 10;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_SISTEMA,ADMINISTRADOR_JUZGADO' WHERE PN_ID = 11;
