DROP SEQUENCE IF EXISTS TRIALS.SEQ_PERSONAL_ASIGNACIONES_ID;

CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_PERSONAL_ASIGNACIONES_ID START WITH 50;

ALTER  SEQUENCE TRIALS.SEQ_PERSONAL_ASIGNACIONES_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_PERSONAL_ASIGNACIONES;
CREATE TABLE TRIALS.TBL_PERSONAL_ASIGNACIONES (
    PN_ID INT NOT NULL PRIMARY KEY,
    FN_PERSONA INT NOT NULL,
    FN_CARPETA INT,
    FN_DOCUMENTO INT,
    FOREIGN KEY (FN_PERSONA) REFERENCES TRIALS.TBL_PERSONAS(PN_ID),
    FOREIGN KEY (FN_CARPETA) REFERENCES TRIALS.TBL_CARPETAS(PN_ID),
    FOREIGN KEY (FN_DOCUMENTO) REFERENCES TRIALS.TBL_DOCUMENTOS(PN_ID)
);

CREATE INDEX IDX_PERSONAL_ASIGNACIONES1 ON TRIALS.TBL_PERSONAL_ASIGNACIONES (FN_PERSONA);
CREATE INDEX IDX_PERSONAL_ASIGNACIONES2 ON TRIALS.TBL_PERSONAL_ASIGNACIONES (FN_CARPETA);
CREATE INDEX IDX_PERSONAL_ASIGNACIONES3 ON TRIALS.TBL_PERSONAL_ASIGNACIONES (FN_DOCUMENTO);

--Agregar index a las tablas faltantes
CREATE INDEX IDX_ANEXOS1 ON TRIALS.TBL_ANEXOS (FN_DOCUMENTO);

CREATE INDEX IDX_CARPETAS3 ON TRIALS.TBL_CARPETAS (FN_PERSONA);
CREATE INDEX IDX_CARPETAS4 ON TRIALS.TBL_CARPETAS (FN_CARPETA_PADRE);
CREATE INDEX IDX_CARPETAS5 ON TRIALS.TBL_CARPETAS (FN_TIPO_PIEZA);

CREATE INDEX IDX_DOCUMENTOS4 ON TRIALS.TBL_DOCUMENTOS (FN_PERSONA);
CREATE INDEX IDX_DOCUMENTOS5 ON TRIALS.TBL_DOCUMENTOS (FN_INSTITUCION);
CREATE INDEX IDX_DOCUMENTOS6 ON TRIALS.TBL_DOCUMENTOS (FN_DOCUMENTO_RELACIONADO);

CREATE INDEX IDX_ETAPA_PROCESAL1 ON TRIALS.TBL_ETAPA_PROCESAL (FN_TIPO_JUICIO);
CREATE INDEX IDX_ETAPA_PROCESAL2 ON TRIALS.TBL_ETAPA_PROCESAL (FN_PROCEDIMIENTO);

CREATE INDEX IDX_EVENTOS1 ON TRIALS.TBL_EVENTOS (FN_JUZGADO);
CREATE INDEX IDX_EVENTOS2 ON TRIALS.TBL_EVENTOS (FN_OFICIALIA);

CREATE INDEX IDX_INSTITUCIONES1 ON TRIALS.TBL_INSTITUCIONES (FN_DOMICILIO);

CREATE INDEX IDX_JUZGADOS1 ON TRIALS.TBL_JUZGADOS (FN_MATERIA);
CREATE INDEX IDX_JUZGADOS2 ON TRIALS.TBL_JUZGADOS (FN_SEDE);

CREATE INDEX IDX_LISTA_ESTRADOS1 ON TRIALS.TBL_LISTA_ESTRADOS (FN_PERSONA);

CREATE INDEX IDX_MOVIMIENTOS6 ON TRIALS.TBL_MOVIMIENTOS (FN_PERSONA_DESTINO);

CREATE INDEX IDX_OFICIALIAS1 ON TRIALS.TBL_OFICIALIAS (FN_TIPO);
CREATE INDEX IDX_OFICIALIAS2 ON TRIALS.TBL_OFICIALIAS (FN_SEDE);

CREATE INDEX IDX_PERSONAS_DOCUMENTOS3 ON TRIALS.TBL_PERSONAS_DOCUMENTOS (FN_DOMICILIO);

CREATE INDEX IDX_SALAS1 ON TRIALS.TBL_SALAS (FN_JUEZ_ID);
CREATE INDEX IDX_SALAS2 ON TRIALS.TBL_SALAS (FN_BLOQUE_ID);
CREATE INDEX IDX_SALAS3 ON TRIALS.TBL_SALAS (FN_JUZGADO_ID);

CREATE INDEX IDX_SEDES1 ON TRIALS.TBL_SEDES (FN_DISTRITO);
CREATE INDEX IDX_SEDES2 ON TRIALS.TBL_SEDES (FN_DOMICILIO);

CREATE INDEX IDX_TIPO_ACUERDO1 ON TRIALS.TBL_TIPO_ACUERDO (FN_MATERIA);
CREATE INDEX IDX_TIPO_ACUERDO2 ON TRIALS.TBL_TIPO_ACUERDO (FN_TIPO_SISTEMA);

CREATE INDEX IDX_TIPO_JUICIO1 ON TRIALS.TBL_TIPO_JUICIO (FN_MATERIA);
CREATE INDEX IDX_TIPO_JUICIO2 ON TRIALS.TBL_TIPO_JUICIO (FN_TIPO_SISTEMA);
CREATE INDEX IDX_TIPO_JUICIO3 ON TRIALS.TBL_TIPO_JUICIO (FN_TIPO_JUICIO_PADRE_ORAL);
CREATE INDEX IDX_TIPO_JUICIO4 ON TRIALS.TBL_TIPO_JUICIO (FN_TIPO_JUICIO_PADRE_TRAD);

CREATE INDEX IDX_TIPO_PARTES1 ON TRIALS.TBL_TIPO_PARTES (FN_TIPO_JUICIO);

CREATE INDEX IDX_TIPOJUICIO_ETIQUETAS1 ON TRIALS.TBL_TIPOJUICIO_ETIQUETAS (FN_TIPO_JUICIO);

