UPDATE TRIALS.TBL_MENUS SET S_ROL ='OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,SECRETARIO,PROYECTISTA,SECRETARIO,ENCARGADO_SALA,ADMINISTRADOR_JUZGADO,CAPTURISTA,OFICIAL_MAYOR_OFICIALIA' WHERE PN_ID = 18;

UPDATE TRIALS.TBL_MENUS SET S_ROL ='OFICIAL_MAYOR_OFICIALIA,CAPTURISTA,OFICIAL_MAYOR_JUZGADO,SECRETARIO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,ENCARGADO_SALA' WHERE PN_ID = 3;

