INSERT INTO TRIALS.TBL_MENUS (pn_id, s_nombre, s_rol, s_link, n_order, fn_parent)
VALUES
(31, 'Calendarios', 'ADMINISTRADOR_JUZGADO,ADMINISTRADOR_SISTEMA,AUXILIAR_OFICIAL_MAYOR_JUZGADO,CAPTURISTA,COMISARIO,DIGITALIZADOR,DILIGENCIARIO,ENCARGADO_CARRITO,ENCARGADO_SALA,JUEZ,OFICIAL_MAYOR_JUZGADO,OFICIAL_MAYOR_OFICIALIA,PROYECTISTA,SECRETARIO,TECNICO_JUZGADO', '/api/core/calendarios', 8, 2);