DROP SEQUENCE IF EXISTS TRIALS.SEQ_COMENTARIOSASISTENTES_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_COMENTARIOSASISTENTES_ID START WITH 50;
ALTER SEQUENCE TRIALS.SEQ_COMENTARIOSASISTENTES_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_COMENTARIOS_ASISTENTES;

CREATE TABLE TRIALS.TBL_COMENTARIOS_ASISTENTES
(
    PN_ID INT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('TRIALS.SEQ_COMENTARIOSASISTENTES_ID'),
    FN_PERSONA_DOCUMENTO INT NOT NULL REFERENCES TRIALS.TBL_PERSONAS_DOCUMENTOS(PN_ID),
    S_COMENTARIO VARCHAR(500),
    T_FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	T_FECHA_EDITA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	S_USUARIO_ALTA VARCHAR DEFAULT CURRENT_USER NOT NULL,
	S_USUARIO_EDITA VARCHAR DEFAULT CURRENT_USER NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_FN_PERSONA_DOCUMENTO ON TRIALS.TBL_COMENTARIOS_ASISTENTES (FN_PERSONA_DOCUMENTO);
