DROP SEQUENCE IF EXISTS TRIALS.SEQ_AUDIENCIAS_PRUEBAS_ID;
CREATE SEQUENCE TRIALS.SEQ_AUDIENCIAS_PRUEBAS_ID START WITH 50 INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_AUDIENCIAS_PRUEBAS;

CREATE TABLE TRIALS.TBL_AUDIENCIAS_PRUEBAS (
  PN_ID INT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('TRIALS.SEQ_AUDIENCIAS_PRUEBAS_ID'),
  FN_AUDIENCIA INT NOT NULL REFERENCES TRIALS.TBL_AUDIENCIAS(PN_ID),
  FN_TIPO_PRUEBA INT NOT NULL REFERENCES TRIALS.TBL_TIPO_PRUEBAS(PN_ID),
  FN_MATERIA_PERICIAL INT NULL REFERENCES TRIALS.TBL_MATERIA_PERICIAL(PN_ID),
  S_NOMBRE_DECLARANTE VARCHAR(60),
  S_DESCRIPCION_INSTRUMENTO VARCHAR(150),
  S_ABSOLVENTE VARCHAR(60),
  S_DESCRIPCION_DOCUMENTO VARCHAR(150),
  S_OBJETO VARCHAR(70),
  S_URL_DOCUMENTO VARCHAR(255)
);


CREATE INDEX IDX_FN_AUDIENCIAS ON TRIALS.TBL_AUDIENCIAS_PRUEBAS (FN_AUDIENCIA);
CREATE INDEX IDX_FN_TIPO_PRUEBA ON TRIALS.TBL_AUDIENCIAS_PRUEBAS (FN_TIPO_PRUEBA);
CREATE INDEX IDX_FN_MATERIA_PERICIAL ON TRIALS.TBL_AUDIENCIAS_PRUEBAS (FN_MATERIA_PERICIAL);

