DROP SEQUENCE IF EXISTS TRIALS.SEQ_TRANSFERENCIA_ID;
CREATE SEQUENCE TRIALS.SEQ_TRANSFERENCIA_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_PERSONAS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_TRANSFERENCIAS;
CREATE TABLE TRIALS.TBL_TRANSFERENCIAS (
	pn_id int NOT NULL,
	fn_persona_entrega int NOT NULL,
	fn_persona_recibe int NULL,
	fn_persona_autoriza int NOT NULL,
	fn_juzgado int NOT NULL,
	t_fecha_transferencia timestamp NULL,
	n_estatus int DEFAULT 0 NOT NULL,
	s_observaciones varchar NULL,
	n_total_expedientes int DEFAULT 0 NULL,
	s_uuid_movimiento uuid NULL,
	t_fecha_alta timestamp NOT NULL,
	t_fecha_edita timestamp NOT NULL,
	s_usuario_alta varchar NOT NULL,
	s_usuario_edita varchar NOT NULL,
	PRIMARY KEY(pn_id)
);

ALTER TABLE TRIALS.TBL_TRANSFERENCIAS ADD CONSTRAINT fk_persona_recibe FOREIGN KEY (fn_persona_recibe) REFERENCES trials.tbl_personas(pn_id);
ALTER TABLE TRIALS.TBL_TRANSFERENCIAS ADD CONSTRAINT fk_persona_entrega FOREIGN KEY (fn_persona_entrega) REFERENCES trials.tbl_personas(pn_id);
ALTER TABLE TRIALS.TBL_TRANSFERENCIAS ADD CONSTRAINT fk_persona_autoriza FOREIGN KEY (fn_persona_autoriza) REFERENCES trials.tbl_personas(pn_id);
ALTER TABLE TRIALS.TBL_TRANSFERENCIAS ADD CONSTRAINT fk_juzgado_transferencia FOREIGN KEY (fn_juzgado) REFERENCES trials.tbl_juzgados(pn_id);

CREATE INDEX IDX_TRANSFERENCIAS1 ON TRIALS.TBL_TRANSFERENCIAS(FN_PERSONA_ENTREGA);
CREATE INDEX IDX_TRANSFERENCIAS2 ON TRIALS.TBL_TRANSFERENCIAS(FN_PERSONA_RECIBE);
CREATE INDEX IDX_TRANSFERENCIAS3 ON TRIALS.TBL_TRANSFERENCIAS(FN_PERSONA_AUTORIZA);
CREATE INDEX IDX_TRANSFERENCIAS4 ON TRIALS.TBL_TRANSFERENCIAS(FN_JUZGADO);