--DROP SEQUENCE IF EXISTS TRIALS.SEQ_ACUERDO_RUBROS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_ACUERDO_RUBROS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_ACUERDO_RUBROS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_ANEXOS_ID;
--CREATE SEQUENCE TRIALS.SEQ_ANEXOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_ANEXOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_ASISTENCIAAUDIENCIA_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_ASISTENCIAAUDIENCIA_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_ASISTENCIAAUDIENCIA_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_AUDIENCIA_ID;
--CREATE SEQUENCE TRIALS.SEQ_AUDIENCIA_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_AUDIENCIA_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_BLOQUE_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_BLOQUE_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_BLOQUE_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_CARPETA_DETALLE_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_CARPETA_DETALLE_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_CARPETA_DETALLE_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_CARPETA_ETAPAS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_CARPETA_ETAPAS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_CARPETA_ETAPAS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_CARPETAS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_CARPETAS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_CARPETAS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_CARPETAS_RUBROS;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_CONCEPTOS_ID;
--CREATE SEQUENCE TRIALS.SEQ_CONCEPTOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_CONCEPTOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_DESAHOGO_AUD_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DESAHOGO_AUD_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_DESAHOGO_AUD_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_DISTRITOS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DISTRITOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_DISTRITOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOC_CONTENIDO_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DOC_CONTENIDO_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_DOC_CONTENIDO_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOC_DETALLE_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DOC_DETALLE_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_DOC_DETALLE_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOCUMENTO_FOLIO_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DOCUMENTO_FOLIO_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_DOCUMENTO_FOLIO_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOCUMENTOS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DOCUMENTOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_DOCUMENTOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_DOCUMENTOS_IDENTIFICACION_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_DOMICILIOS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_DOMICILIOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_DOMICILIOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_ESCOLARIDADES_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_ESCOLARIDADES_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_ESCOLARIDADES_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_ESTADO_CIVIL_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_ESTADO_CIVIL_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_ESTADO_CIVIL_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_ETAPA_PROCESAL_ID;
--CREATE SEQUENCE TRIALS.SEQ_ETAPA_PROCESAL_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_ETAPA_PROCESAL_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_EVENTOS_ID;
--CREATE SEQUENCE TRIALS.SEQ_EVENTOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_EVENTOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_INSTITUCIONES_ID;
--CREATE SEQUENCE TRIALS.SEQ_INSTITUCIONES_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_INSTITUCIONES_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_JUZGADO_FOLIOS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_JUZGADO_FOLIOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_JUZGADO_FOLIOS_ID START WITH 50 INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_JUZGADOS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_JUZGADOS_ID START WITH 50 INCREMENT BY 50;
ALTER SEQUENCE TRIALS.SEQ_JUZGADOS_ID INCREMENT BY 50;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_LISTA_ESTRADOS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_LISTA_ESTRADOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_LISTA_ESTRADOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_MATERIA_PERICIAL_ID;
--CREATE SEQUENCE TRIALS.SEQ_MATERIA_PERICIAL_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_MATERIA_PERICIAL_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_MATERIAS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_MATERIAS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_MATERIAS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_MOVIMIENTOS_ID;
--CREATE SEQUENCE TRIALS.SEQ_MOVIMIENTOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_MOVIMIENTOS_ID START WITH 50 INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_NOTIFICACIONES_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_NOTIFICACIONES_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_NOTIFICACIONES_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_NOTIFICACIONES_DETALLES_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_NOTIFICACIONES_DETALLES_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_NOTIFICACIONES_DETALLES_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_OFICIALIAS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_OFICIALIAS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_OFICIALIAS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_ORGANISMOS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_ORGANISMOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_ORGANISMOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_PERSONADETALLE_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_PERSONADETALLE_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_PERSONADETALLE_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_PERSONAL_ASIGNACIONES_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_PERSONAL_ASIGNACIONES_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_PERSONAL_ASIGNACIONES_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_PERSONAS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_PERSONAS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_PERSONAS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_PERSONAS_DOCUMENTOS_ID;
--CREATE SEQUENCE TRIALS.SEQ_PERSONAS_DOCUMENTOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_PERSONAS_DOCUMENTOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_PROCEDIMIENTOS_ID;
--CREATE SEQUENCE TRIALS.SEQ_PROCEDIMIENTOS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_PROCEDIMIENTOS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_RELIGIONES_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_RELIGIONES_ID START WITH 10 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_RELIGIONES_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_RUBROS_ID;
--CREATE SEQUENCE TRIALS.SEQ_RUBROS_ID START WITH 100 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_RUBROS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_SALA_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_SALA_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_SALA_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_SEDES_ID;
--CREATE SEQUENCE TRIALS.SEQ_SEDES_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_SEDES_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_TIPO_ACUERDO_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_ACUERDO_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_TIPO_ACUERDO_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_TIPO_AUDIENCIA_ID;
--CREATE SEQUENCE TRIALS.SEQ_TIPO_AUDIENCIA_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_TIPO_AUDIENCIA_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_TIPO_JUICIO_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_JUICIO_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_TIPO_JUICIO_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_TIPO_OFICIALIAS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_OFICIALIAS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_TIPO_OFICIALIAS_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_TIPO_PARTES_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_PARTES_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_TIPO_PARTES_ID INCREMENT BY 1;

--DROP SEQUENCE IF EXISTS TRIALS.SEQ_TIPO_SISTEMA_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_SISTEMA_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_TIPO_SISTEMA_ID INCREMENT BY 1;

--DROP TABLE IF EXISTS TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID;
--CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID START WITH 50 INCREMENT BY 1;
ALTER SEQUENCE TRIALS.SEQ_TIPOJUICIO_ETIQUETAS_ID INCREMENT BY 1;
