CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_MATERIA_PERICIAL_ID
START WITH 10;

ALTER SEQUENCE TRIALS.SEQ_MATERIA_PERICIAL_ID
INCREMENT BY 10;

DROP TABLE IF EXISTS TRIALS.TBL_MATERIA_PERICIAL;

CREATE TABLE TRIALS.TBL_MATERIA_PERICIAL (
    PN_ID INT NOT NULL PRIMARY KEY,
    S_NOMBRE VARCHAR(150) NOT NULL
);



INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Actuaría');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Administración');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Agrimensura');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Agronomía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Análisis de Videos');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Anestesiología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Arquitectura');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Auditoría y Contaduría');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'),'Bioquímica');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Caligrafía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Cardiología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Cirugía General');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Criminalística');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Criminología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Dactiloscopía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Daños a edificios, Construcción, Cimentaciones, Estructuras y por Siniestros.');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Documentoscopía y Grafoscopía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Economía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Fotografía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Genética');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Gineco-obstétrica');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Grafología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Grafometría');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Grafoscopía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Impacto Ambiental');

INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Informática');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Ingeniería Civil');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Ingeniería Industrial');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Ingeniería Mecánica');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Medicina');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Medicina Genética Molecular');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Medios Electrónicos');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Neurología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Odontología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Oftalmología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Ortopedia');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Paidología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Pedagogía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Psicología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Psicología (con especialización en Adopción)');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Psicología Infantil');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Psiquiatría');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Química');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Sexología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Topografía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Trabajo Social');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Trabajo Social (con especialización en Adopción)');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Traductores e Intérpretes de Lenguas Indígenas');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Traductores e intérpretes en lenguas extranjeras: Alemán');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Traductores e intérpretes en lenguas extranjeras: Francés');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Traductores e intérpretes en lenguas extranjeras: Inglés');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Traductores e intérpretes en lenguas extranjeras: Italiano');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Traductores e Intérpretes para Sordomudos y problemas de lenguaje');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Tránsito Terrestre');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Bienes Inmuebles');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Bienes Muebles');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Derechos de Autor');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Joyas');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Obras de Arte');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Vialidad Terrestre');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Hechos de Tránsito');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Mecánica de Hechos');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Balística');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Serología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Daños Automotrices');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Construcción');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Ingeniería Eléctrica');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Instalación Eléctrica');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Química Industrial');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Explosivos y Siniestro');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Toxicología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Psicología Criminal');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Medicina Forense');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Medicina General');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Lofoscopía');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Bienes Agropecuarios');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Equipos y Procesos Industriales');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Maquinaria y Herramienta');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Vehículos Automotrices');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Instalaciones Eléctricas');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Perito Social');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Medios Electrónicos e Informática');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Radiocomunicación');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Teleinformática');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Químico Farmacobiólogo');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Contabilidad');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Vehículos');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Traductor en Lengua Indígena Náhuatl');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Psicología Clínica');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Traductor en Lengua Indígena Totonaca Variante Central del Sur');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Psicología Social en Materia de Perspectiva de Género');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Traductores e Intérpretes en Lenguas Extranjeras: Inglés y Francés');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Urbanismo');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Derechos de Autor');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Tanatología');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Finanzas');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Equipos y Procesos Industriales');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Vehículos Automotrices y Diesel');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Siniestro');
INSERT INTO TRIALS.TBL_MATERIA_PERICIAL (PN_ID, S_NOMBRE) VALUES (nextval('SEQ_MATERIA_PERICIAL_ID'), 'Valuación de Bienes Agropecuarios');


