DROP SEQUENCE IF EXISTS TRIALS.SEQ_ASISTENCIAAUDIENCIA_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_ASISTENCIAAUDIENCIA_ID START WITH 50;
ALTER SEQUENCE TRIALS.SEQ_ASISTENCIAAUDIENCIA_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_ASISTENCIA_AUDIENCIA;

CREATE TABLE TRIALS.TBL_ASISTENCIA_AUDIENCIA
(
    PN_ID INT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('TRIALS.SEQ_ASISTENCIAAUDIENCIA_ID'),
    FN_PERSONA_DOCUMENTO INT NOT NULL REFERENCES TRIALS.TBL_PERSONAS_DOCUMENTOS(PN_ID),
    FN_AUDIENCIA INT NOT NULL REFERENCES TRIALS.TBL_AUDIENCIAS(PN_ID),
    N_ASISTENCIA INT NULL,
    FN_DOCUMENTO_IDENTIFICACION INT NOT NULL REFERENCES TRIALS.TBL_DOCUMENTOS_IDENTIFICACION(PN_ID),
    S_URL_DOCUMENTO VARCHAR(255),
    T_FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	T_FECHA_EDITA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	S_USUARIO_ALTA VARCHAR DEFAULT CURRENT_USER NOT NULL,
	S_USUARIO_EDITA VARCHAR DEFAULT CURRENT_USER NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_FN_PERSONA_DOCUMENTO ON TRIALS.TBL_ASISTENCIA_AUDIENCIA (FN_PERSONA_DOCUMENTO);
CREATE INDEX IF NOT EXISTS IDX_FN_AUDIENCIA ON TRIALS.TBL_ASISTENCIA_AUDIENCIA (FN_AUDIENCIA);
CREATE INDEX IF NOT EXISTS IDX_FN_DOCUMENTO_IDENTIFICACION ON TRIALS.TBL_ASISTENCIA_AUDIENCIA (FN_DOCUMENTO_IDENTIFICACION);
