UPDATE TRIALS.TBL_MENUS SET S_ROL = S_ROL || ',AUXILIAR_OFICIAL_MAYOR_JUZGADO,OFICIAL_MAYOR_JUZGADO' WHERE PN_ID = 16;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO,ENCARGADO_SALA,JUEZ,OFICIAL_MAYOR_JUZGADO,OFICIAL_MAYOR_OFICIALIA,SECRETARIO,TECNICO_JUZGADO,PROYECTISTA' WHERE PN_ID = 26;

UPDATE TRIALS.TBL_MENUS SET S_ROL = 'ADMINISTRADOR_JUZGADO,AUXILIAR_OFICIAL_MAYOR_JUZGADO,CAPTURISTA,DIGITALIZADOR,ENCARGADO_CARRITO,ENCARGADO_SALA,JUEZ,OFICIAL_MAYOR_JUZGADO,OFICIAL_MAYOR_OFICIALIA,SECRETARIO,TECNICO_JUZGADO,PROYECTISTA' WHERE PN_ID = 27;
