DROP SEQUENCE IF EXISTS TRIALS.SEQ_DERECHOS_ID;
CREATE SEQUENCE TRIALS.SEQ_DERECHOS_ID START WITH 100;
ALTER SEQUENCE TRIALS.SEQ_DERECHOS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_DERECHOS;
CREATE TABLE TRIALS.TBL_DERECHOS(
    PN_ID INT NOT NULL,
    S_NOMBRE VARCHAR,
    N_DERECHOS INT,
    PRIMARY KEY(PN_ID)
);

-- Inserción de Derechos de la persona (N_DERECHOS = 0)
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Acceso a la información pública', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Asilo politico (Derecho al) ', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Igualdad ante la ley (Derecho al)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Igualdad de género (Derecho a la)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'La no discriminación (Derecho a)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Libertad (Derecho a la)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Libertad de asociación (Derecho a la)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Libertad de expresión (Derecho a la)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Libertad de tránsito y residencia (Derecho a la)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Migrantes (Derechos de los)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Protección de datos (Derecho a la)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Seguridad e integridad de la persona (Derecho a la)', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Sistema penitenciario', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Tortura', 0);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Vida (Derecho a la)', 0);

-- Inserción de Derechos económicos, sociales y culturales (N_DERECHOS = 1)
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Acceso a los servicios públicos (Derecho al)', 1);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Agua (Derecho al)', 1);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Asistencia social y médica (Derecho a la)', 1);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Educación (Derecho a la)', 1);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Medio ambiente saludable (Derecho al)', 1);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Propiedad (Derecho a la)', 1);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Trabajo (Derecho al)', 1);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Trabajo (Derecho del)', 1);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Vivienda (Derecho a la)', 1);

-- Inserción de Derechos de los pueblos indígenas (N_DERECHOS = 2)
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Autodeterminación (Derecho a la)', 2);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Igualdad y no discriminación por razón de origen racial o étnico, religión o convicciones', 2);

-- Inserción de Protección de grupos específicos (N_DERECHOS = 3)
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Adolescentes (Derechos de los)', 3);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Comunidades LGBTTTI (Derechos de las)', 3);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Extranjeros (Derechos de los)', 3);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Mujeres (Derechos de las)', 3);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Niños (Derechos de los)', 3);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Personas adultas mayores (Derechos de las)', 3);
INSERT INTO TRIALS.TBL_DERECHOS(PN_ID, S_NOMBRE, N_DERECHOS)
VALUES (nextval('TRIALS.SEQ_DERECHOS_ID'), 'Personas con capacidades diferentes (Derechos de las)', 3);
