DROP SEQUENCE IF EXISTS TRIALS.SEQ_TIPO_PRUEBAS_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TIPO_PRUEBAS_ID START WITH 50;
ALTER SEQUENCE TRIALS.SEQ_TIPO_PRUEBAS_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_TIPO_PRUEBAS;

CREATE TABLE TRIALS.TBL_TIPO_PRUEBAS (
  PN_ID INT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('TRIALS.SEQ_TIPO_PRUEBAS_ID'),
  FN_TIPO_JUICIO INT NULL REFERENCES TRIALS.TBL_TIPO_JUICIO(PN_ID),
  S_NOMBRE VARCHAR(100),
  S_DATO VARCHAR(100),
  FN_PRUEBA_PADRE_ID INT NULL REFERENCES TRIALS.TBL_MATERIA_PERICIAL(PN_ID)
);

CREATE INDEX IDX_FN_TIPO_JUICIO ON TRIALS.TBL_TIPO_PRUEBAS (FN_TIPO_JUICIO);
CREATE INDEX IDX_PRUEBA_PADRE_ID ON TRIALS.TBL_TIPO_PRUEBAS (FN_PRUEBA_PADRE_ID);

INSERT INTO TRIALS.TBL_TIPO_PRUEBAS (FN_TIPO_JUICIO, S_NOMBRE, S_DATO, FN_PRUEBA_PADRE_ID)
VALUES
  ((SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Oralidad Mercantil (Oral)'), 'Confesional', NULL, NULL),
  ((SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Oralidad Mercantil (Oral)'), 'Pericial', NULL, NULL),
  ((SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Oralidad Mercantil (Oral)'), 'Instrumento Público', NULL, NULL),
  ((SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Oralidad Mercantil (Oral)'), 'Documento Privado', NULL, NULL),
  ((SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Oralidad Mercantil (Oral)'), 'Reconocimiento de contenido y firma', NULL, NULL),
  ((SELECT PN_ID FROM TRIALS.TBL_TIPO_JUICIO WHERE S_NOMBRE = 'Oralidad Mercantil (Oral)'), 'Inspección judicial', NULL, NULL);
