DROP SEQUENCE IF EXISTS TRIALS.SEQ_TEMPLATES_ID;
CREATE SEQUENCE IF NOT EXISTS TRIALS.SEQ_TEMPLATES_ID START WITH 50;
ALTER SEQUENCE TRIALS.SEQ_TEMPLATES_ID INCREMENT BY 1;

DROP TABLE IF EXISTS TRIALS.TBL_TEMPLATES;
CREATE TABLE TRIALS.TBL_TEMPLATES (
    PN_ID INT NOT NULL PRIMARY KEY,
    S_NOMBRE VARCHAR(250) NOT NULL,
    N_TIPO INT,
    S_CONTENIDO TEXT,
    FN_JUZGADO INT NOT NULL,
    T_FECHA_ALTA    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    T_FECHA_EDITA   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    S_USUARIO_ALTA  VARCHAR(50)  DEFAULT CURRENT_USER,
    S_USUARIO_EDITA VARCHAR(50)  DEFAULT CURRENT_USER,
    FOREIGN KEY (FN_JUZGADO) REFERENCES TRIALS.TBL_JUZGADOS(PN_ID)
);

CREATE INDEX IDX_TEMPLATES_JUZGADO ON TRIALS.TBL_TEMPLATES (FN_JUZGADO);
