INSERT INTO TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
VALUES (1, 'documento', 'Demanda', 100);

INSERT INTO TBL_TIPOJUICIO_ETIQUETAS (PN_ID, S_NOMBRE, S_VALUE, FN_TIPO_JUICIO)
VALUES (2, 'nombreActor', 'Nombre del Actor', 100);

