INSERT INTO TBL_PERSONA_DETALLE (
    PN_ID, FN_PERSONA_DOCUMENTO, FN_LENGUA_INDIGENA, FN_NACIONALIDAD, FN_ESCOLARIDAD, FN_DOCUMENTO_IDENTIFICACION,
    S_SEXO, D_FECHA_NACIMIENTO, FN_PAIS_NACIMIENTO, S_ENTIDAD_NACIMIENTO, S_MUNICIPIO_NACIMIENTO, N_EDAD, S_TIPO_DOMICILIO,
    S_RFC, S_DISCAPACIDAD, S_ESTADO_CIVIL, S_CONDICION_MIGRATORIA, B_HABLA_ESPANOL, S_LENGUA_EXTRANJERA, S_GRUPO_VULNERABLE,
    B_SABE_LEER_ESCRIBIR, S_PROFESION_OFICIO, S_INGRESO_MENSUAL_NETO, S_FRECUENCIA_INGRESO, S_LUGAR_TRABAJO,
    N_CANTIDAD_DEPENDIENTES_ECONOMICOS, S_DETALLE_DEPENDIENTES, N_BIENES, S_RELIGION, S_SENIAS_PARTICULARES, S_GRUPO_ETNICO,
    B_DATOS_PRIVADOS, S_CEDULA, S_TIPO_DEFENSOR, S_ADSCRIPCION, B_RECIBE_PERCEPCIONES, B_HABLA_LENGUA_INDIGENA, 
    B_PERTENECE_GRUPO_VULNERABLE, B_TIENE_BIENES, B_TIENE_SENIAS_PARTICULARES, B_PERTENECE_GRUPO_ETNICO, B_TIENE_RELIGION, 
    B_TIENE_DEPENDIENTES_ECONOMICOS, B_HABLA_LENGUA_EXTRANJERA
)
VALUES (
    1, 1, 1, 3, 2, 10, 'M', '1990-05-15', 1, 'Puebla', 'Puebla', 34, 'Casa', 'ABC1234567890', 'Ninguna', 'Soltero', 'Regular',
    true, 'Inglés', 'Ninguno', true, 'Ingeniero', '15000', 'Mensual', 'Empresa XYZ', 2, 'Hijos, esposa', true, 'Católica',
    'Ninguna', 'Mestizo', true, 'C1234567890', 'Jefe de Departamento', 'Oficina Central', true, false, false, true, false, 
    false, true, true, true
);
