INSERT INTO TBL_TIPO_ACUERDO (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (701, 'ACCIÓN PENAL POR PARTICULAR', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);

INSERT INTO TBL_TIPO_ACUERDO (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (702, 'SENTENCIA', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);

INSERT INTO TBL_TIPO_ACUERDO (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (703, 'ACEPTACIÓN AL CARGO DE PERITO', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL);

INSERT INTO TBL_TIPO_ACUERDO (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (704, 'OTROS', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);

INSERT INTO TBL_TIPO_ACUERDO (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (705, 'SENTENCIA INTERLOCUTORIA', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Oral'));

INSERT INTO TBL_TIPO_ACUERDO (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (706, 'OTROS', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));
