INSERT INTO TBL_RELIGIONES (PN_ID, S_NOMBRE) VALUES (1, 'Católico Apostólico Romano');
INSERT INTO TBL_RELIGIONES (PN_ID, S_NOMBRE) VALUES (2, 'Católico Romano');
INSERT INTO TBL_RELIGIONES (PN_ID, S_NOMBRE) VALUES (3, 'Católico');