INSERT INTO TBL_DOCUMENTO_FOLIO (PN_ID, N_TIPO_DOCUMENTO, N_CENTRO_TRABAJO_ID, N_TIPO_CENTRO_TRABAJO, N_FOLIO, N_YEAR)
VALUES (1, 1, 51, 1, 1, EXTRACT('YEAR' FROM CURRENT_DATE));

INSERT INTO TBL_DOCUMENTO_FOLIO (PN_ID, N_TIPO_DOCUMENTO, N_CENTRO_TRABAJO_ID, N_TIPO_CENTRO_TRABAJO, N_FOLIO, N_YEAR)
VALUES (2, 1, 51, 0, 1, EXTRACT('YEAR' FROM CURRENT_DATE));