INSERT INTO TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (100, 'ACEPTACION DE CARGO', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'FAMILIAR'), (SELECT PN_ID FROM TBL_TIPO_SISTEMA WHERE S_NOMBRE = 'Tradicional'));

INSERT INTO TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (150, 'AUDIENCIA INCIDENTAL', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'MERCANTIL'), NULL);

INSERT INTO TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (200, 'ACEPTACIÓN AL CARGO DE PERITO', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'CIVIL'), NULL);

INSERT INTO TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (250, 'ACUERDO', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'LABORAL'), NULL);

INSERT INTO TBL_ACUERDO_RUBROS (PN_ID, S_NOMBRE, FN_MATERIA, FN_TIPO_SISTEMA)
VALUES (300, 'CONTROL DE DETENCION', (SELECT PN_ID FROM TBL_MATERIAS WHERE S_NOMBRE = 'PENAL'), NULL);