INSERT INTO TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO,
                            S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (1, '', '', '', '', '', '', '', '', '');

INSERT INTO TBL_DOMICILIOS (PN_ID, S_CALLE, S_INTERIOR, S_EXTERIOR, S_COLONIA, S_CODIGO_POSTAL, S_MUNICIPIO,
                            S_ESTADO_REPUBLICA, S_REFERENCIA, S_LOCALIDAD)
VALUES (2, '', '', '', '', '', '', '', '', '');
