INSERT INTO TBL_DOCUMENTO_DETALLE(PN_ID, FN_DOCUMENTO, S_ASUNTO, T_FECHA_EMISION)
VALUES(1, 1, 'PRUEBA ASUNTO', NOW());

INSERT INTO TBL_DOCUMENTO_DETALLE(PN_ID, FN_DOCUMENTO, S_ASUNTO, T_FECHA_EMISION)
VALUES(2, 5, 'PRUEBA ACUERDO', NOW());

INSERT INTO TBL_DOCUMENTO_DETALLE(PN_ID, FN_DOCUMENTO, S_ASUNTO, T_FECHA_PUBLICACION, T_FECHA_RESOLUCION)
VALUES(3, 6, 'PRUEBA ACUERDO', '1990-10-10', '1990-10-10');