INSERT INTO TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
VALUES (51, 100);

INSERT INTO TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
VALUES (51, 101);

INSERT INTO TBL_JUZGADO_TIPOJUICIO (FN_JUZGADO, FN_TIPOJUICIO)
VALUES (51, 106);
