UPDATE TBL_CARPETAS SET N_ESTADO = 1 WHERE PN_ID = 1;

INSERT INTO TBL_MOVIMIENTOS (PN_ID, FN_CARPETA, FN_DOCUMENTO, FN_PERSONA, FN_OFICIALIA, FN_JUZGADO, N_TIPO, S_UUID)
VALUES (nextval('SEQ_MOVIMIENTOS_ID'), 1, 1, 1, 51, 51, 0, 'd8945bc4-af8e-4eb0-b742-7ee13beb43e0');